### ISSUE TITLE
Caricamenti e audio

### ISSUE THREAD

**Issue by LovatoTomas** [italia/design-comuni-wordpress-theme#100]
Buongiorno, con il passaggio alla versione 1.3.0 del tema, le pagine impiegano diversi secondi per essere visualizzate completamente (il testo è l'ultima cosa che compare). 
Inoltre volevo segnalare che la funzione "Ascolta" non viene eseguita da PC (in particolare io l'ho provata da Microsoft Edge).
Confermo invece che da dispositivo mobile funziona correttamente.

**Comment by astagi** [comment]
Buongiorno @LovatoTomas potresti per favore fornire un video che mostri questo ritardo? se possibile magari anche un link a un'istanza staging in modo da fare delle verifiche con gli strumenti. La funzione ascolta è stata testata con Microsoft Edge, il tuo sistema è Windows?

**Comment by mariantanase** [comment]
Io non riscontro un delay.
Per quanto mi riguarda, la funzione "Ascolta" ho notato che viene eseguita correttamente con Edge e Chrome. 
Non viene eseguita invece su Firefox.

**Comment by astagi** [comment]
@mariantanase che sistema operativo utilizzi?

**Comment by mariantanase** [comment]
Windows 10 Pro x64, Firefox v107
Escono dei errori di downloadable fontfailed però credo che per il fatto  che sono su ambiente in locale. 
Quello che potrebbe essere utile ai fini di debug:

![errore-ascolta](https://user-images.githubusercontent.com/3976174/203018229-7b3fcd3b-46a5-4492-92e0-f7cd87c1bfaa.png)

**Comment by astagi** [comment]
Molto strano, grazie @mariantanase ... potresti provare a cambiare in `actions.php`  alla riga 101

```html
onclick="window.listenElements(this, '[data-audio]')"
```

su Mac non riesco a riprodurre l'errore con nessun file. Vediamo se aggiungendo window riparte.

**Comment by mariantanase** [comment]
> Molto strano, grazie @mariantanase ... potresti provare a cambiare in `actions.php` alla riga 101
> 
> ```
> onclick="window.listenElements(this, '[data-audio]')"
> ```
> 
> su Mac non riesco a riprodurre l'errore con nessun file. Vediamo se aggiungendo window riparte.

Perfetto !
Questo è il fix e funziona anche con Firefox
Grazie

**Comment by astagi** [comment]
Ottimo! Grazie @mariantanase ! @LovatoTomas hai modo di provare anche tu per Edge? Intanto preparo una patch per la giornata di oggi!

**Comment by astagi** [comment]
@mariantanase @LovatoTomas versione 1.3.1 rilasciata con il fix e con miglioramenti degli asset a livello di performance :) per qualsiasi cosa fatemi sapere! Grazie ancora!

**Comment by LovatoTomas** [comment]
https://user-images.githubusercontent.com/59308506/203321262-831ebefc-46fd-42d7-abde-52040fba2726.mp4

Buongiorno,
ho effettuato un acquisizione del problema (Windows 11 21H2, Microsoft Edge Versione 107.0.1418.52).ù
Il sito in produzione utilizza l'ultima versione del tema: 1.3.1

Come potete notare, il primo secondo di caricamento della pagina è caratterizzato dall'assenza dei caratteri e successivi errori sui font. Anche il comando Ascolta lancia un errore, nonostante le correzioni di ieri.

Ringrazio per la celere risposta ieri.
