### ISSUE TITLE
Payload valutazioni, appuntamenti e richiesta assistenza

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#105]
Buongiorno,
in caso di aggancio ad un servizio API REST di un comune, come si deve procedere nella modifica dei file che si trovano in asset/js (rating.js, booking.js e assistenza.js)?
Questi file risultano minimizzati e compressi e quindi estremamente difficili da editare.
Non sarebbe il caso di avere anche la versione estesa?

Grazie.

**Comment by marco-nanni** [comment]
Questo problema è presente solo in questa versione. 
Nella versione precedente (1.3.0) sono presenti sia i file estesi che quelli minimizzati.

**Comment by astagi** [comment]
@marco-nanni ottimo punto il tuo. Al di là della minificazione o meno servirebbe una documentazione su cosa estendere in un proprio file js per agganciarsi alle API. Tecnicamente non andrei a toccare i codici sorgenti, ad una modifica dello stream principale del tema stesso occorrerebbe gestire i conflitti. Riporto al team la questione, grazie!

**Comment by marco-nanni** [comment]
@astagi Assolutamente. Infatti pensavo di usare il child del tema.
Grazie per l'attenzione.

**Comment by astagi** [comment]
@marco-nanni intanto ho ripristinato il sorgente dimmi se può tornarti come soluzione https://github.com/italia/design-comuni-wordpress-theme/pull/117

**Comment by marco-nanni** [comment]
@astagi Li vedo uguali a prima.

**Comment by astagi** [comment]
@marco-nanni ho cambiato il fatto che adesso stanno nella cartella `assets-src` dove sono non minificati. Per minificarli occorre installare le dipendenze npm con `npm i` e poi lanciare `npm run build` per crearli minificati.. Ovviamente se ci sono delle modifiche dal repo vanno gestiti i conflitti però adesso il sorgente in `assets-src` è ripristinato e facilmente modificabile

**Comment by marco-nanni** [comment]
@astagi ok, visto.
Il problema che noi non abbiamo installato npm, ne tanto meno yarn (che da una serie di problemi su Windows) ne tanto meno sass.  Per poter effettuare delle imnplementazioni semplici, come il cambio di colore su css e/o eventuali modifiche su file js, mi sembra un procedimento estremamente complesso.

**Comment by astagi** [comment]
Capisco @marco-nanni però non saprei come risolvere l'altro problema, ovvero garantire la minificazione degli asset. In realtà puoi anche prendere il codice di asset-src e portartelo in asset con le tue modifiche senza installare niente, funziona lo stesso, solo che non sarà minificato..

**Comment by astagi** [comment]
@marco-nanni ho aggiunto la seguente dicitura giusto per essere chiari nel caso non si voglia usare npm

- se non abbiamo modo di minificare il file (scelta sconsigliata) possiamo copiare e incollare i file da `assets-src` verso `assets` così come sono e modificarli.
