### ISSUE TITLE
Pagine Senza Contenuti

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#106]
Salve, sto configurando il mio sito inserendo le informazioni come richieste dalla documentazione.

Ho trovato delle difficoltà nella modifica di alcune pagine.
Nella scelta del template per la singola pagina mi sono trovato limitato, perchè diverse pagine al momento sono prive di contenuti

In particolare ho notato questo nelle pagine della sezione "**Esplora l'amministrazione**" della pagina "**Amministrazione**".
Questo è dovuto alla mancanza di template? Come posso aggiungerne di nuovi e fare in modo che compaiono tra quelli disponibili negli "attributi della pagina".

Sono disposto a mettermi d'impegno per realizzare le mie mancanze, però avrei bisogno appunto di uno spunto per iniziare.
Grazie in anticipo per l'aiuto.

**Comment by astagi** [comment]
Buonasera @danieledexter si è dovuto alla mancanza di template, qualche PR è già aperta (https://github.com/italia/design-comuni-wordpress-theme/pulls) e risolvono alcuni template mancanti, adesso è in corso una review dei designer per correggere eventuali parti. Chiudo questa issue, se hai delle sezioni specifiche che mancano anche tra le PR aperte crea una segnalazione ad hoc oppure ben venga la contribuzione con la creazione di un template dedicato :) grazie!
