### ISSUE TITLE
Stemma (logo) alternativa

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#107]
Stavo combattendo con un logo (stemma) bianco sullo sfondo trasparente.
Ho provato sia con un'immagine png che con svg, ma quando si attiva l'offcanvas (hamburger menu), l'immagine bianca sullo sfondo bianco ovviamente non si vede. Non so come avete risolto questo aspetto.
Però ho cercato di sviluppare una soluzione in cui viene utilizzata un'immagine alternativa.
Fatemi sapere se può interessare, oppure l'approccio e sbagliato.

![screenshot-admin-config](https://user-images.githubusercontent.com/3976174/203594983-21fc862c-580a-4657-a6d9-c9196379e353.png)

![screenshot-desktop-logo-bianco](https://user-images.githubusercontent.com/3976174/203595025-a0f07607-8309-4f6d-9559-c3974d19b4a6.png)

![screenshot-mobile-logo-scuro](https://user-images.githubusercontent.com/3976174/203595047-bf90a9e2-067f-4fdc-8c03-14a0152e4902.png)

**Comment by astagi** [comment]
Buonasera @mariantanase , se adottiamo una svg è possibile volendo anche cambiare il colore programmaticamente, però se l'utente carica una png la cosa si fa più complessa in effetti. La tua soluzione mi sembra un miglioramento molto interessante, chiedo anche a @zetareticoli che ne pensa, se vede qualche controindicazione a livello di design, per me è ok.

**Comment by zetareticoli** [comment]
ciao @mariantanase, mi sembra una buona integrazione.

Dovremmo solo verificare che non ci siano regole CSS che fanno override del tag `<svg class="icon">`. 
Ad esempio, vedo che nel file `style.css` c'è questa regola:

```css
.it-header-wrapper .navbar-collapsable .logo-hamburger .icon {
  fill: #007a52;
  margin-right: 16px;
}
```

Hai previsto già la sua rimozione?

**Comment by mariantanase** [comment]
> Hai previsto già la sua rimozione?

Quel codice css che hai menzionato è presente solo nel `style.css` dei statici, nel tema WP non esiste.
Comunque, nella nuova pagina logo-mobile ho eliminato il riferimento alla classe icon e le modifiche sembra che non influiscono in alcun modo. 
Devo fare altri test anche per la compatibilità cross-browser.
P.S. Ho notato che anche altri comuni utilizzano 2 svg diversi per lo stemma.

**Comment by astagi** [comment]
@mariantanase ottimo! Grazie del contributo! quando hai pronta la modifica puoi aprire una PR in modo da poterla revisionare cc @zetareticoli
