### ISSUE TITLE
Scheda Servizio, sezione Contatti

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#109]
Nel tema per Wordpress, il content-type "single-servizio", nella sezione **Contatti** ho notato che vengono mostrati i dettagli dell'unità organizzativa in versione ridotta (**card**).
Nei statici vedo che carica tutto (**card-full**)
https://italia.github.io/design-comuni-pagine-statiche/sito/template-dettaglio-servizio.html
Non è che mi cambia molto, sarebbe una piccola modifica, ma c'è qualche ragione per visualizzarla così?
Grazie

**Comment by astagi** [comment]
Su questo lascio la parola a @zetareticoli non so se è una scelta di design o una mancanza, in teoria il tema dovrebbe rispettare gli statici.

**Comment by zetareticoli** [comment]
Ciao @mariantanase, 
confrontando le due versione, quella statica e WP (installazione dev in locale), sembra però che sia lo stesso codice:

**WP**
```html

<div class="card card-teaser card-teaser-info rounded shadow-sm p-3">
    <div class="card-body pe-3">
        <p class="card-title text-paragraph-regular-medium-semi mb-3">
            <a class="text-decoration-none" href="http://sb01.eurobeta.it:8080/amministrazione/unita_organizzativa/unita-organizzativa/" data-element="service-area">Dipartimento Attività Culturali</a>
        </p>
        <div class="card-text">
            <p class="u-main-black">Corso Como, 20131</p>        
        </div>
    </div>
    </div>
  ```
  
  **Statico**
```html

<div class="card card-teaser card-teaser-info rounded shadow-sm p-3">
    <div class="card-body pe-3">
      <p class="card-title text-paragraph-regular-medium-semi mb-3">
        <a class="text-decoration-none" href="#" data-element="service-area">Ufficio Scuola</a>
      </p>
      <div class="card-text">
        <p class="u-main-black">Via Dei Transiti 21, 50302</p>
        <p class="u-main-black"><a href="tel:+39055052334">(+39) 05 505 2334</a></p>
        <p class="u-main-black"><a href="mailto:ufficioscuola@email.it">ufficioscuola@email.it</a></p>
      </div>
    </div>
    <div class="avatar size-xl">
      <img src="https://picsum.photos/200/200" alt="Immagine">
    </div>
</div>
```

La differenza non è nel template della card utilizzata, ma nei contenuti che sono inseriti. Ti torna?

**Comment by mariantanase** [comment]
Purtroppo non mi torna. 

Non è un problema dei contenuti, io ho già inserito 3, indirizzo, telefono, e email, ma solo l'indirizzo lo mostra.
Avevo notato però che nel template `single-servizio.php` alla riga 396 viene chiamata :

`get_template_part("template-parts/unita-organizzativa/card");`

e questa mostra solo la variabile `$indirizzo` .
Ti risulta ?

invece, se faccio rirerimento alla card-full, vengono visualizzate tutte le info del contatto, come nei statici.
`get_template_part("template-parts/unita-organizzativa/card-full");`

**Comment by astagi** [comment]
cc @zetareticoli
