### ISSUE TITLE
Gestione aggiornamento tema (manuale e/o automatico)

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#11]
Buongiorno,

E' previsto (se fattibile) aggiungere la possibilità di notificare in backend se la versione del tema installato è diversa del tema corrente ? Intendo come avvieve adesso per i vari plugin di WordPress.
Secondo, quali sono le best practices per aggiornare il tema Design comuni ?

Grazie

**Comment by mariantanase** [comment]
> @mariantanase hai avuto modo di provare quel plugin? :)

Ancora no, perché non ho capito il funzionamento.
Lo installo sul sito di produzione, e poi ? Mi avvisa lui di ogni rilascio di versione ?
Credo che sarebbe utile di scrivere 2 righe nella documentazione del tema sul argomento dell'aggiornamento del tema, e le casistiche (es. Installazione esistente con child theme personalizzato).

**Comment by astagi** [comment]
Ciao @mariantanase si dovrebbe comportarsi così, forse andando a pescare i tag. Sinceramente devo provarlo anch'io, chiedevo appunto se avessi fatto prima tu qualche prova. Provo a metterlo su una piattaforma di staging e vedere che succede. Per l'aggiornamento manuale (sempre in staging) per ora stiamo procedendo al semplice pull del tema dal repository.

**Comment by mariantanase** [comment]
Ciao @astagi ,
Nella configurazione del plugin oltre all'inserimento di una token github personale, non chiede altro. Credo che l'aggiornamento manuale alla fine va meglio.
Siccome Wordpress non mi sta molto simpatico :) voglio chiederti come procedere per un caso concretto.
Tipo, installazione WP con il tema 1.2.0 sopra e child personalizzata.
Adesso, la 1.2.1 come va installata ? Non ho mai capito se sovrascrivere tramite ftp il tema master o no.
Con Joomla gli aggiornamenti sono indolori e sicuri. Mi piacerebbe se trovassimo qualche programmatore per sviluppare un tema anche per Joomla.
Grazie

**Comment by astagi** [comment]
Su questo @mariantanase devo sentire qualcuno più esperto di Wordpress, intanto ti aggiorno che un contributor della community sta analizzando e creando della documentazione per far girare tutto tramite Gitupdater. Insomma, ti tengo aggiornato :) 

P.S. Nuova release disponibile, grazie del prezioso contributo, come sempre e buon weekend!
