### ISSUE TITLE
Prenotazione Appuntamento

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#110]
Riscontrato che nella pagine "Prenotazione Appuntamento" nella scelta dell'ufficio compare del codice anomalo.

Esempio:
\n","id":"tv"}' onclick="saveAnswerById('place', 69, () => setSelectedPlace())" />

Sembra essere dovuto a qualcosa all'interno del file **design-comuni-wordpress-theme-main/assets/js/booking.js**
Potete verificare?

Grazie

**Comment by astagi** [comment]
Grazie della segnalazione @danieledexter da che versione ti ha cominciato a dare questo errore?

**Comment by astagi** [comment]
Inoltre @danieledexter questo errore ti appare sul template? se si puoi fornire uno screenshot?

**Comment by astagi** [comment]
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/537363/203847139-d905cc5d-dda5-46f2-91bd-787b31ac25bc.png">

se questa è la pagina di riferimento, non riesco a riprodurre l'errore.

**Comment by danieledexter** [comment]
Si la pagina indicata è corretta.
Ecco cosa mi compare:
![image](https://user-images.githubusercontent.com/115085709/203929368-9e676bf1-691c-4db0-86c9-f1c7a0e64aac.png)

**Comment by astagi** [comment]
@danieledexter che versione stai usando del tema? Hai percaso modificato il file booking.js?

**Comment by danieledexter** [comment]
Dovrebbe essere la versione 1.3.0
Ho aggiunto una tema child per non perdere le modifiche.
In questa cartella ho aggiunto i file che ho trovato nelle pull request per testare i nuovi template, ma non ho modificato il booking.js

**Comment by danieledexter** [comment]
Questo è quello che mi compare:
![image](https://user-images.githubusercontent.com/115085709/203994596-0433377b-4f47-4950-bb20-6d5b7d72655a.png)
Però per esempio se seleziono un altro ufficio, questo anomalia non c'è.

**Comment by astagi** [comment]
@danieledexter nel child theme hai modificato qualcosa alla struttura html? il tema lo vedo diverso anche nei dati che fa vedere
<img width="489" alt="image" src="https://user-images.githubusercontent.com/537363/203996462-0f365c3a-bb8e-4f59-bc77-557e1ab05704.png">


non vorrei che questa alterazione andasse a far impallare il JavaScript di booking.js

**Comment by danieledexter** [comment]
Ho fatto delle modifiche ai css principalmente per vedere i layout di colore blu, altre cose non ho fatto.
Non so se ci possono essere delle dipendenze con i file che ho trovato nelle pull request.

**Comment by danieledexter** [comment]
Vorrei aggiungere che ora ho riattivato il tema come fornito da voi.
Anche ora noto la stessa cosa:
![image](https://user-images.githubusercontent.com/115085709/204020429-9b1697ca-4096-4a53-b880-2fdcffbe2641.png)

**Comment by astagi** [comment]
@danieledexter secondo me c'è un errore di formattazione all'interno del backoffice, forse qualche tag html non chiuso nei dati dell'elemento "Municipio"

**Comment by danieledexter** [comment]
Il problema credo sia proprio a livello di Luogo, perchè sull'unità organizzativa selezionata se metto un altro luogo che ho aggiunto, la selezione è corretta.

Ho un secondo Luogo che mi mostra lo stesso problema.
Lato Back Office questi Luoghi sono stati inseriti con testi molto semplici, senza l'utilizzo di html e con le voci obbligatorie, fin qui sembrerebbe tutto normale.

Proverò a creare un nuovo luogo al pari del comune per vedere se è un caso unico oppure no.

**Comment by danieledexter** [comment]
Confermo che il problema è il luogo, creato "comune 2" con informazioni inserite allo stesso modo.
Così compare la selezione del luogo:
![image](https://user-images.githubusercontent.com/115085709/204027822-81bb7007-b4fc-41eb-ba75-3f72dc3606a9.png)

**Comment by astagi** [comment]
Grazie @danieledexter segnalo allora la problematica come bug

**Comment by zetareticoli** [comment]
Ciao @danieledexter, vedo dal tuo screen che è ancora presente il campo "Sportello" rimosso invece in una delle ultime release del tema. Forse puoi provare ad aggiornarlo all'ultima versione?

**Comment by danieledexter** [comment]
Va bene, grazie per la risposta.
Provvedo ad aggiornare e vi informo.

**Comment by astagi** [comment]
Grazie @danieledexter 👍  great catch @zetareticoli !!!

**Comment by danieledexter** [comment]
Ho aggiornato, ma senza notare differenze.
Nel file booking.js c'è ancora il campo "Sportello" anche sull'ultima versione.

**Comment by astagi** [comment]
@danieledexter strano... è presente ancora l'errore?

**Comment by astagi** [comment]
@danieledexter abbiamo rimosso da booking.js la voce sportello, dimmi se tutto ti funziona https://github.com/italia/design-comuni-wordpress-theme/commit/fe5d06e33ca2ba4ccf4e4d280423027c59d7e548
