### ISSUE TITLE
Problemi con il file comuni.css

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#118]
Buongiorno,
abbiamo riscontrato delle anomalie con il file "comuni.css", una volta ricompilato il file "bootstrap-italia-min.css" divenuto "bootstrap-italia-custom.min.css" tramite comando yarn per cambio di colore come da Vostre specifiche, riguardanti il tag <LI> relative al calendario (.splide) che invece nei template di esempio online sono presenti. Oltre al fatto che i colori di "comuni.css" sono rimasti verdi. Abbiamo risolto utilizzando lo style.css del tema child per ripristinarne il corretto comportamento.

**Comment by astagi** [comment]
@marco-nanni perdonami potresti illustrare la procedura da voi eseguita? Non capisco il problema dalla issue

**Comment by marco-nanni** [comment]
@astagi 
a) Ho ricompilato il progetto bootstrap-italia per portare il colore a blu (in questo caso) come spiegato qui: https://github.com/italia/bootstrap-italia-playground
b) Ho fatto in modo che il file ottenuto ("bootstrap-italia-custom.min.css" e relativo map) fossero caricati dal tema child.
c) Il problema è sorto con il file "comuni.css" che è rimasto impostato sul colore verde di base. Quindi è stato modificato e caricato dallo style.css del tema child. In questo modo abbiamo ottenuto un colore del tema uniforme.

Abbiamo rilevato anche un altro problema e cioè che le classi .splide non erano presenti mentre nel sito del template statica lo erano. Questo problema faceva in modo che il dtario degli eventi fossero caricate verticalmente e non orizzontalmente come avrebbe dovuto essere.

Rimango a disposizione per eventuali chiarimenti sulle operazioni da noi svolte.

Grazie.

**Comment by astagi** [comment]
Grazie mille chiaro @marco-nanni ! Direi che insieme al problema js e payload anche questo diventa un problema di chiarimento della documentazione! Ovviamente se volete contribuire anche alla modifica della documentazione ben venga!!

**Comment by marco-nanni** [comment]
@astagi Grazie. 
Ma la domanda che mi/ci (alla mia collega) sorge spontane è: la procedura che abbiamo eseguito è corretta (per il cambio di colore, etc) del tema?

**Comment by mariantanase** [comment]
Mi aggiungo alla richiesta di chiarire quest'aspetto (almeno) della personalizzazione dei colori, che secondo me è la prima cosa che va personalizzata in base alle esigenze del proprio comune.
Non so se si può aggiungere (in backend) una sorta di picker per la scelta dei colori...

**Comment by zetareticoli** [comment]
La procedura consigliata è quella di agire in _override_ rispetto ai files del tema, usando files CSS separati.

In questo modo sarà più semplice (e sicuro) scaricare i futuri aggiornamenti senza rischiare di perdere il vostro lavoro di personalizzazione.

Stiamo lavorando ad un'ottimizzazione delle risorse, il nostro obiettivo è quello di avere uno style.css del tema più "asciutto" insieme ad un file bootstrap-italia.min.css che contiene la base dei componenti utilizzati.

**Comment by marco-nanni** [comment]
Ed è esattamente quello che stiamo facemdo.
Ho ricompilato tramite il comando yarn il tema bootstrap-italia come da documentazione e abbiamo caricato il css ottenuto dal child del tema. In più abbaimo caricato, sempre dal child, il resto delle classi css che non hanno subito il cambiamento del colore. Allacciandomi a questo tema ci sarebbe anche il problema della cartella "inc" del tema che non è gestibile da child. Quindi alcune modifiche le ho dovute implementare direttamente nel tema principale. So che non è la pratica corretta, ma visto che oggi abbiamo una demo ho dovutro "accorciare" i tempi.

**Comment by zetareticoli** [comment]
Ciao @marco-nanni, resta qualche altro punto da discutere o possiamo considerare chiusa questa _issue_?

**Comment by marco-nanni** [comment]
@zetareticoli puoi chiudere, grazie.
