### ISSUE TITLE
Mappa del Luogo non visibile

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#119]
Buonasera,
ho notato che nelle pagine delle unità organizzative non compare la mappa del luogo associato.
A primo impatto c'è uno spazio vuoto:
![image](https://user-images.githubusercontent.com/115085709/204331507-4ac32007-30d2-4542-95d9-eebf172053a2.png)
Nel luogo in questione ho messo la posizione sulla mappa in quanto campo obbligatorio.
Nella pagina di un evento con lo stesso luogo invece compare:
![image](https://user-images.githubusercontent.com/115085709/204332085-964011ca-a17c-44f2-a886-bc9f825670c7.png)

Devo quindi intervenire sul template delle unità organizzative? O meglio, è una mancanza o un errore?

Grazie

**Comment by astagi** [comment]
@danieledexter immagino questa https://github.com/italia/design-comuni-wordpress-theme/pull/99 ? in questo caso segnalo a @giannicozzolino al di là poi del refactoring che sarà necessario dopo il passaggio di design potrebbe essere una funzionalità mancante, intanto chiudo e direi di risolverla lato PR aperta riportando il commento sotto la PR, grazie! cc @zetareticoli
