### ISSUE TITLE
Unità organizzative e luoghi: problema visualizzazione dati

### ISSUE THREAD

**Issue by lullabyweb** [italia/design-comuni-wordpress-theme#12]
Buongiorno,
se creo una unità organizzativa e la implemento di tutti i campi obbligatori oltre che del campo responsabile, in front end la pagina mi presenta solo descrizione breve e competenze, senza contatti, sede principale, persone che compongolo la struttura e responsabile.

Idem sui luoghi: implementando il luogo con tutti i campi obbligatori in front end non si visualizzano modalità di accesso, indirizzo, immagine

Sbaglio qualcosa?

Grazie
Alessandra

**Comment by mariantanase** [comment]
Per quanto riguarda i luoghi, ad oggi non è stato implementato il template per questo content-type. (vedi #6 )

**Comment by zetareticoli** [comment]
Ciao @lullabyweb, ti ha risposto correttamente @mariantanase 

Non abbiamo ancora un piano di rilasci definito che preveda l'aggiunta dei templates per altri content-type. Nel frattempo, posso solo suggerirti di crearli in autonomia seguendo le indicazioni del [documento di Architettura dell'Informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=1529184526). 

Nel caso decidessi di realizzarli, puoi mettere a riuso della community eventuali sviluppi :)
