### ISSUE TITLE
Servizi di richiesta assistenza e appuntamento non invia la mail di riepilogo

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#120]
Buongiorno,
ho effettuato un test relativo al servizio di richiesta assistenza.
Funzona tutto, tranne l'invio della mail di riepilogo.
Il servizio SMTP è raggiungibile e correttamente configurato.
Servono altre impostazioni oppure è un bug?

Grazie.

**Comment by astagi** [comment]
Buongiorno @marco-nanni nella console avviene qualche errore? potrebbe essere un bug verifichiamo

**Comment by marco-nanni** [comment]
@astagi sembra funzionare tutto regolarmente e anche il log non segnala nulla.
![richiesta_assistenza_email_1](https://user-images.githubusercontent.com/118733111/204549981-b7de7949-8378-4827-b716-e5abf0d548b9.PNG)
![richiesta_PA_2026_2](https://user-images.githubusercontent.com/118733111/204550009-c37040b2-5448-4024-a312-a8e74c0cc18c.PNG)

**Comment by astagi** [comment]
Bene, grazie @marco-nanni giro la richiesta allora e indaghiamo!

**Comment by mariantanase** [comment]
> Buongiorno, ho effettuato un test relativo al servizio di richiesta assistenza. Funzona tutto, tranne l'invio della mail di riepilogo. Il servizio SMTP è raggiungibile e correttamente configurato. Servono altre impostazioni oppure è un bug?
> 
> Grazie.

Ciao,
Come hai configurato nel backend l'SMTP ?
E poi, non mi permette di selezionare alcun servizio, sembra disabilitato. 
Quardando nel codice mi pare che nel template "assistenza" non è implementata quella parte.

**Comment by marco-nanni** [comment]
@mariantanase Ciao, allora per tutta una serie di motivi tecnici ho installato un plugin SMTP e l'ho configurato con il nostro server di posta. Ho effettuato degli invii di prova per capire se funzionava tutto a dovere e poi ho fatto dei test con le Richieste di Assistenza. In effetti pendso anch'io che non vi sia del codice. Perché esegue tutto regolarmente enza errori e la mail di fatto non arriva.

**Comment by mariantanase** [comment]
Ma il campo ti permette di scegliere il servizio ? A me sembra disabilitato. 
Quindi non ci arrivo manco a cliccare su "Invia".
Ti risulta ?

![nessun-servizio-visualizzato](https://user-images.githubusercontent.com/3976174/204788899-351f4fda-d97e-4df2-9a99-6cc2f74bd958.png)

**Comment by marco-nanni** [comment]
@mariantanase No, a me funziona. Carica i servizi regolarmente.

**Comment by mariantanase** [comment]
> @mariantanase No, a me funziona. Carica i servizi regolarmente.

@marco-nanni 
che versione del tema utilizzi ?
puoi fornire più dettagli sulla configurazione ?
puoi fornire un link al sito?

grazie

**Comment by marco-nanni** [comment]
@mariantanase 
L'ultima.
E' una configurazione SMTP - TLS (plugin WP Mail SMTP).
Il sito è in ambiente di sviluppo non raggiungible dall'esterno.

**Comment by mariantanase** [comment]
Non per l'SMTP, tanto non ci arrivo a fare invio, mi riferivo alle modifiche fatte al codice in particolare al file assistenza.php

**Comment by marco-nanni** [comment]
Nessuna modifica. E' il codice standard. 
Stesso problema per la prenotazione. 
Esegue tutto, ma non invia nulla. 
Anche in questo caso il codice è standard.

**Comment by mariantanase** [comment]
Molto strano, però vedo che non sono l'unico con questo problema, vedi #135 
Ho fatto e rifato molte installazioni pulite WP + tema ma non funziona lo stesso su nessuno.
Spero che qualche sviluppatore del tema ci può aiutare.

**Comment by marco-nanni** [comment]
Per il il momento ho risolto aggiungento nella funzione "dci_save_richiesta_assistenza()" situata nel file "/inc/funzionalita_trasversali.php". Purtroppo non sono riuscito a riposrtare questo file nel cild quindi ho dovuto riportare questa modifica direttamente nel tema principale.
Il codice è il seguente:

	$to = $params['email'];
	$subject = 'Richiesta Assistenza';
	$message = "Buongiorno " . $params['nome'] . " " . $params['cognome'] . 
				",<br> di seguito sono riepilogati i dettagli della sua richiesta: <br><br>" . 
				"<b>Categoria</b> " . $categoria->name ."<br>" .
				"<b>Servizio</b> " . $params['servizio'] . "<br>" . 
				"<b>Dettagli</b> " . $params['dettagli'] . "<br><br>" .
				"La sua richiesta sarà presa in carico al più presto.<br><br>" .
				"Cordiali saluti";
	$headers = "Content-Type: text/html; charset=UTF-8";
	
	if (!wp_mail( $to, $subject, $message, $headers )) {
        echo json_encode(array(
            "success" => false,
            "error" => array(
                "code" =>  500,
                "message" => "Oops, qualcosa è andato storto nell'invio della mail!"
            )));
        wp_die();
	}

Lo devi aggiungere al termine del salvataggio dei dati della richiesta.
Ovviamente è il codice è provvisorio e serve solo per capire se effttivamente viene inviata una mail dal sito.

Stessa cosa penso anrà impostata per la prenotazione che si trova nello stesso file.

**Comment by astagi** [comment]
@marco-nanni grazie! Si ho avuto conferma dagli sviluppatori di questa parte

```
L'invio email non è stato implementato in quanto riguarda funzionalità da completare con l'implementazione di servizi esterni. 
```

Se posso dare un consiglio, se ti è possibile, per evitare più possibile conflitti in un aggiornamento del tema, meglio riportare questo codice in una funzione in un file esterno e lasciare in quel file solo la chiamata alla funzione che manda la mail.

Grazie a tutti!

**Comment by marco-nanni** [comment]
@astagi Consiglio giusto. Infatti sto procedendo in questo modo. 
Per ora nel functions.php del child poi diventerà un plugin. 
Perché oltre all'invio della mail di riepilogo c'è anche l'invio dei dati JSON ai servizi esterni.

add_action("wp_ajax_save_appuntamento" , "dci_email_appuntamento", 10);
add_action("wp_ajax_nopriv_save_appuntamento" , "dci_email_appuntamento", 10);

In questo modo prima scrive nel proprio custom post trmite le action originali, manda la mail ed infine invia i dati.

**Comment by marco-nanni** [comment]
@astagi Ora sono io a dare un consiglio se non scoccia. 
Forse questi servizi vi conviene trasformarli in plugin in modo che, in caso di bisogno, possano essere disattivati e rimpiazzati con quelli custom. Perché se rimancono integrati nel tema diventa quasi impossibile non metterci le mani. Perché le richioeste saranno parecchie secondo me.

**Comment by marco-nanni** [comment]
@astagi Quando sarà pronta la macchina definitiva di sviluppo più che volentieri. 
Ora sto lavorando su una macchhina AWS approntata alla veloce, giusto per la demo che avevamo in programma.

**Comment by astagi** [comment]
Perfetto grazie @marco-nanni !

**Comment by fnori77** [comment]
Salve, volevo chiedere se è stato risolto il problema dell'invio email perché il sistema registra gli appuntamenti ma non invia alcuna comunicazione. Grazie.
