### ISSUE TITLE
Unità organizzativa non carica i contenuti inseriti

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#121]
Salve, 

non riesco a capire come popolare la pagina "nomesito/amministrazione/organi-di-governo/".

Sembrerebbe che il Template amministrazione non visualizzi i contenuti icorrelati.
ecco la mia organizzazione
![Screenshot 2022-11-29 at 14-35-35 Organi di Governo – Demo PA 2026](https://user-images.githubusercontent.com/119422587/204542960-e8693bd0-dd4c-47f2-86ba-f51ac03023e7.png)

ecco invece la medesima organizzazione sul sito del Comune di Cagliari
[/amministrazione/organi-di-governo/](https://www.comune.cagliari.it/portale/page/it/organi_governo)
![Screenshot 2022-11-29 at 14-36-41 Organi di governo](https://user-images.githubusercontent.com/119422587/204543348-337104ad-9eb1-403a-9fb1-b67b835b35df.png)

Cosa sbaglio? Come faccio a vedere tutte le info che ho inserito dell'organizzazione?

**Comment by astagi** [comment]
@cristina-pontarolo in realtà il template è in corso di sviluppo qua: #97 Attualmente quella parte viene visualizzata così 

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/537363/204553008-100aaf29-15b0-4c7b-a1aa-14ef16f1f641.png">

**Comment by danieledexter** [comment]
Il comune di Cagliare da quello che ho visto è stato personalizzato.
I template sono stati aggiunti a parte.
Non so a chi si sono state affidate le modifiche, però ognuno effettivamente è libero di personalizzarsi il tema a piacimento.

Sarebbe bello che chi lo avesse fatto, mettese qui il codice a disposizione di tutti.

L'installazione attuale del tema non prevede diversi contenuti, in quanto pagine come questa sono associate ancora al template di default.

Consiglio a chi vuole procedere con le personalizzazioni di seguire questo link: https://developer.wordpress.org/themes/basics/template-hierarchy/

**Comment by danieledexter** [comment]
Ovviamente è possibile fare le aggiunte seguendo la documentazione, non proprio a piacimento.

**Comment by astagi** [comment]
Chiudo come duplicato https://github.com/italia/design-comuni-wordpress-theme/issues/29
