### ISSUE TITLE
Luogo - da MACOS catalna - nessun browser visulaizza la mappa

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#122]
Non posso creare i Luoghi, perchè dal mio Mac non visualizzo la MAPPA in Posizione GPS:

![Screenshot 2022-11-29 at 14-49-31 Aggiungi un Luogo ‹ Demo PA 2026 — WordPress](https://user-images.githubusercontent.com/119422587/204546291-bf34ee1d-e6ce-4e64-adc9-9d201ed05d93.png)

dunque non posso salvare il luogo e procedere con l'inserineto dei contenuti.

**Comment by astagi** [comment]
Ciao @cristina-pontarolo hai qualche errore in console? magari qualche libreria javascript che non viene caricata?

**Comment by cristina-pontarolo** [comment]
![Schermata 2022-11-29 alle 14 54 52 (2)](https://user-images.githubusercontent.com/119422587/204547732-10dd9432-ef01-4a8b-bf00-5d6c28cb544f.png)
Caricamento non riuscito per lo <script> con sorgente “https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.2/leaflet.js?ver=0.1.3”. [post-new.php:2603:1](https://wptest.ecohmedia.com/wp-admin/post-new.php?post_type=luogo)
Uncaught Leaflet must be loaded first [geocoder.js:14:7](https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js?ver=0.1.3)
    <anonima> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js?ver=0.1.3:14
    <anonima> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js?ver=0.1.3:17
Uncaught ReferenceError: L is not defined
    initMap https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:84
    <anonymous> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:139
    jQuery 2
    <anonymous> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:137
    <anonymous> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:168
[main.js:84:9](https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3)
    initMap https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:84
    <anonima> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:139
    jQuery 2
    <anonima> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:137
    <anonima> https://wptest.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/main.js?ver=0.1.3:168

**Comment by astagi** [comment]
Sembra quasi non carichi Leaflet, sta utilizzando l'ultima versione del tema @cristina-pontarolo ?

Io dalla mia installazione riesco a vedere la mappa

<img width="979" alt="image" src="https://user-images.githubusercontent.com/537363/204551801-84379a02-b865-4027-8cff-ea6523379ff4.png">

**Comment by cristina-pontarolo** [comment]
SI stò utilizzando l'ultima versione del tema

**Comment by astagi** [comment]
Non saprei @cristina-pontarolo chiudo perchè non riesco a riprodurlo. MacOS Catalina non dovrebbe più essere supportato non vorrei ci fossero dei problemi ad aggiornare i browser. Provato sul mio Mac con Montrey e utilizzando broweser Firefox, tutto funziona 

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/537363/204807108-ed80444d-42ba-4912-ac85-ea0d32bf238f.png">
