### ISSUE TITLE
Hai un’identità digitale SPID o CIE? - Richiesta Assistenza

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#123]
Buongiorno,
nella pagina iniziale della Richiest Assistenza appare questa dicitura: "Hai un’identità digitale SPID o CIE? Accedi".
Cliccando su "Accedi" non accade nulla.
L'accesso tramite CIE e SPID farà parte dello sviluppo del tema?

Grazie.

**Comment by zetareticoli** [comment]
Ciao @marco-nanni, 
la parte di integrazione con SPID e CIE non è inclusa nel tema, va fatta separatamente.
