### ISSUE TITLE
Punto di contatto - non vedo gli altri dati inseriti

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#124]
Pur avendo inserito nei campi idnicati i dati Telefono e mail,
![Screenshot 2022-11-29 at 15-33-20 Modifica il Punto di contatto “Ufficio Tributi” ‹ Demo PA 2026 — WordPress](https://user-images.githubusercontent.com/119422587/204557437-acb99358-e863-41bb-8511-de883bfb7520.png)

Tali dati non vengono visualizzati nella pagina del servizio
![Screenshot 2022-11-29 at 15-33-33 Regolamento per l’applicazione dell’Imposta comunale sugli immobili (ICI) – Demo PA 2026](https://user-images.githubusercontent.com/119422587/204557459-6ffbb405-68db-4023-85c5-da33ca6e7529.png)

**Comment by mariantanase** [comment]
#109

**Comment by astagi** [comment]
Chiudo come duplicato grazie @mariantanase
