### ISSUE TITLE
Luoghi - dettaglio Luogo

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#125]
/vivere-il-comune/luoghi/sede-comune-demo/
in questa pagina non vedo la mappa.
![Screenshot 2022-11-29 at 15-38-22 Sede del Comune Demo – Demo PA 2026](https://user-images.githubusercontent.com/119422587/204558283-d72ffe72-2839-4f4f-b467-4f01aaa59dc9.png)

**Comment by astagi** [comment]
Grazie @cristina-pontarolo ne abbiamo già parlato in questa issue https://github.com/italia/design-comuni-wordpress-theme/issues/119 scrivete pure sulla PR di riferimento. Chiudo come duplicato.
