### ISSUE TITLE
Aree Amministrative - dettaglio della pagina

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#126]
Buon guorno, nella pagina /amministrazione/aree-amministrative/
![Screenshot 2022-11-29 at 16-26-53 Aree amministrative – Demo PA 2026](https://user-images.githubusercontent.com/119422587/204571122-f4c3c967-336d-423f-af91-4d221025d8f2.png)

non vedo l'elenco delle UNITà Organizative crete come AREE.
![Screenshot 2022-11-29 at 16-27-11 Unità Organizzative ‹ Demo PA 2026 — WordPress](https://user-images.githubusercontent.com/119422587/204571160-9fc3429b-1f28-4ee5-b1fe-ed18bd599260.png)

**Comment by astagi** [comment]
Buongiorno @cristina-pontarolo manca ancora il tema purtroppo per tale pagina. Ci stiamo lavorando.
