### ISSUE TITLE
Argomento - tassonomia - associare icona

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#128]
Buongiorno, 

Come posso visualizzare l'icona relativa subito sopra al titolo?

![Screenshot 2022-11-30 at 09-53-27 Argomento](https://user-images.githubusercontent.com/119422587/204751151-2f940a3d-e8ee-4936-af4b-6db0592b0223.png)

Oppure come si vede qui sempre nel sito del comune di cagliari

![Screenshot 2022-11-30 at 10-05-12 Argomenti](https://user-images.githubusercontent.com/119422587/204753548-fd7b7435-3321-4171-8fcd-2abcb1dd9a07.png)

**Comment by astagi** [comment]
@cristina-pontarolo non capisco la domanda, l'icona si vede subito sopra al titolo "Sport".

**Comment by cristina-pontarolo** [comment]
> 

L'immagine è del sito di Cagliari, non del mio sito. Volevo avere la stessa icona ma mi hanno già risposto che non è prevista nel tema.

**Comment by astagi** [comment]
Capisco grazie @cristina-pontarolo no, esatto, sono customizzazioni di tema. Chiudo la issue.
