### ISSUE TITLE
tipi di evento - link errato al dettaglio del tipo di evento

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#130]
Buongiorno,
se clicco qualsiasi tipo di evento (evento religioso per esempio, vedi foto)
![Screenshot 2022-11-30 at 10-18-37 Vivere il Comune – Demo PA 2026](https://user-images.githubusercontent.com/119422587/204756735-01f63223-0329-491c-b6a2-ecbd5764eae3.png)

atterro in /tipi_evento/evento-religioso/ ma visualizzo lo stesso contenuto della HOME PAGE.
![Screenshot 2022-11-30 at 10-19-47 Demo PA 2026](https://user-images.githubusercontent.com/119422587/204756917-34c62b11-98e0-4b12-b8b9-d205b0125e29.png)

**Comment by astagi** [comment]
@cristina-pontarolo molto strano, sicura di non aver modificato il permalink in qualche modo? io nel backoffice ho questo

<img width="637" alt="image" src="https://user-images.githubusercontent.com/537363/204808370-b40fae7e-ba3a-49f3-bb51-f97ae20186cc.png">

e funziona

**Comment by cristina-pontarolo** [comment]
non sono stata chiara
 devi cliccare sulla TIPOLOGIA e non sul lnk dell'evento.

 /tipi_evento/evento-religioso/  questo è il link della tipologia di evento.

/vivere-il-comune/eventi/363-festa-di-santefisio/ questo è il dell'evento in se
