### ISSUE TITLE
home page - argomentio in evidenza

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#131]
vorrei visualizzare gli arcomenti in evidenza in home page come nel Comune di Cagliari, come faccio?
![Screenshot 2022-11-30 at 11-08-25 Comune di Cagliari](https://user-images.githubusercontent.com/119422587/204768225-75800848-ca69-46ea-89cb-b1079e42c1b0.png)

Io non riesco a vedere icone ne dell'argomento ne della news, come si associano per poi poterle vedere?
![Screenshot 2022-11-30 at 11-08-05 Demo PA 2026](https://user-images.githubusercontent.com/119422587/204768426-0a8bbf81-0077-4159-a102-ca634cceb4ba.png)

**Comment by mariantanase** [comment]
Devi personalizzare il tema in base alle tue esigenze.
Secondo me il sito del Comune di Cagliari non utilizza questo tema per WP, invece hanno implementato una soluzione propria partendo dalle librerie di Bootstrap Italia.

**Comment by astagi** [comment]
Grazie @mariantanase si si tratta sempre di personalizzazioni che uno deve fare.
