### ISSUE TITLE
Problema caricamento font per tema bootstrap-italia

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#132]
Buongiorno,
mentre eseguivo dei test sul caricamento delle pagine ho notato questo:
![wptest_errore_carimanto_font_bootstrap-italia_1](https://user-images.githubusercontent.com/118733111/204770096-d27c55ad-0f66-46c0-bbb8-d7b3368dca4a.PNG)

Penso sia dovuto al fatto che ho ricompilato bootstrap-italia per il cambio del colore e quindi, caricandolo dal child del tema, cerca di caricare i font dalla cartella "bottstrap-italia/dist/font" alla root del sito e quindi non trova nulla.
Ho risolto ricreando la cartella "bootstrap-italia" nella root del sito e copiando la cartella "dist\fonts" dal proggetto bootstrap-italia situata sotto "node_modules". Non so se è il metodo corretto, ma al momento funziona.

**Comment by mariantanase** [comment]
Confermo, anch'io ricevo questi messaggi nella console.

**Comment by marco-nanni** [comment]
@mariantanase tu hai ricompilato il boostrap-italia oppure stai utilizzando la versione di default? 
Perché in quest'ultimo caso allora il problema è a monte e non è dovuto alla ricompilazione del css in questione.

**Comment by mariantanase** [comment]
Versione di default, nessuna ricompilazione

**Comment by marco-nanni** [comment]
@mariantanase vero, Ma io l'ho fatto per ridurre i tempi dic aricamento. Infatti ora il sito viaggia più veloce.

**Comment by zetareticoli** [comment]
@marco-nanni 
perdonami non ho ben inquadrato la problematica e come hai risolto, potresti per favore descrivermi tutti i passaggi in modo più chiaro?

**Comment by marco-nanni** [comment]
@zetareticoli 
Al momento mi sono limitato a ricreare nella root del sito il percorso riportato nella segnalazione di errore e cioè:
"bootstrap-italia/dist/fonts"
Il percorso originale si trova nella cartella "node_modules" situata nel progetto "bootstrap-italia-playground-main".

**Comment by garagiu** [comment]
ho creato anch'io la cartella bootstrap-italia/dist/fonts inserendovi i tre font LORA, ROBOTO MONO e TITILLIUM WEB. In console non ho più errori e il sito carica velocemente. Però in prospettiva andrebbe aggiornato il bootstrap-italia.bundle.min.js con un percorso all'interno della root del tema

**Comment by marco-nanni** [comment]
@astagi ok. Finita la demo farò qualche prova.

**Comment by marco-nanni** [comment]
@astagi Ok. La tua soluzione funziona.

Ho eliminato la cartella che avevo copiato nella root del sito e ho richimato un js dal child con all'interno :
window.__PUBLIC_PATH__ = '/wp-content/themes/design-comuni-wordpress-theme-main/assets/fonts';

**Comment by astagi** [comment]
Perfetto grazie del riscontro @marco-nanni ! Nel brevissimo futuro implementeremo in Bootstrap-Italia questa parte sia in lazy che tramite css, ad ogni modo lasceremo questo fallback. Chiudo la segnalazione.

Grazie a tutti!

**Comment by mariantanase** [comment]
> 

Ciao @marco-nanni 
Non riesco a implementare la tua soluzione. Puoi spiegare meglio ?
Grazie

**Comment by marco-nanni** [comment]
@mariantanase certo.
a) Gnerare il child del tema **design-comuni-wordpress-theme-main-child**
b) Creare la cartella js
c) nella catella js, creare il file **bootstrap-italia-custom-config.js**
d) All'interno scrivere **window.PUBLIC_PATH = '/wp-content/themes/design-comuni-wordpress-theme-main/assets/fonts';**
e) Allinterno di'**functions.php** aggiungere:

add_action( 'wp_enqueue_scripts', 'bootstrap_italia_custom_config' );
function bootstrap_italia_custom_config() {
	wp_enqueue_script( 'bootstrap-italia-custom-config', get_template_directory_uri() . '-child'  . '/js/bootstrap-italia-custom-config.js');
}

**Comment by mariantanase** [comment]
Grazie

**Comment by astagi** [comment]
Si forse ha senso inserirla direttamente nel tema @marco-nanni @mariantanase è possibile aprire una PR a riguardo?

**Comment by mattiadevigus** [comment]
Buongiorno

Si ha qualche novità riguardo alla soluzione definitiva? Bisogna applicare il metodo di @marco-nanni o verrà rilasciato qualcosa nel tema padre?

**Comment by zetareticoli** [comment]
Ciao @mattiadevigus, @astagi ha spiegato in un commento sopra come impostare la variabile per il path dei font
https://github.com/italia/design-comuni-wordpress-theme/issues/132#issuecomment-1338968936

**Comment by mariantanase** [comment]
> Ciao @mattiadevigus, @astagi ha spiegato in un commento sopra come impostare la variabile per il path dei font [#132 (comment)](https://github.com/italia/design-comuni-wordpress-theme/issues/132#issuecomment-1338968936)

Purtroppo da me non funziona, e spero che verrà implementata il fix direttamente nel core.

**Comment by mattiadevigus** [comment]
Si, ho visto il commento sopra. L'ho provato anche io ma attualmente non funziona.  Lo eviterei nel caso venisse inserito direttamente nel tema padre.

**Comment by astagi** [comment]
Aggiornato @mattiadevigus @mariantanase  https://github.com/italia/design-comuni-wordpress-theme/commit/ddaaf81a64fdb9dbe810ca0796c32d44b9bb49a3
