### ISSUE TITLE
Form Richiedi assistenza, impossibile scegliere il servizio

### ISSUE THREAD

**Issue by MarcoEmme** [italia/design-comuni-wordpress-theme#135]
Nel mio form "Richiedi assistenza" qualunque categoria di servizio io scelga la dropdown "Servizio" rimane disabilitata, anche laddove accertato che dovrebbe esserci un servizio attivo.
Infatti, quando provo a cliccare "Avanti" mi si blocca informandomi che manca questo dato che. però, non posso impostare.
Forse mi sono perso qualche impostazione preliminare?
M.

**Comment by mariantanase** [comment]
Lo stesso comportamento capita anche a me. Vedi #120

**Comment by MarcoEmme** [comment]
Ho atteso qualche giorno per una prova dopo una nuova installazione WP presso altro comune e altro hosting.
Forse sono io che non comprendo bene il funzionamento...?
Ho creato il servizio "Cambiare residenza" associandolo alla categoria "Anagrafe e stato civile". Il servizio è attivo.
Entro nella pagina "Richiedi assistenza" e la dropdown "Servizio" è inizialmente attiva, giustamente, con la sola option "Scegli il servizio". Seleziono la categoria nella tendina "Categoria di servizio", l'unica al momento presente, "Anagrafe e stato civile".
Ora non dovrei trovarmi la tendina "Servizio" attiva e popolata del servizio "Cambiare residenza"? Invece diventa non selezionabile.
M.

**Comment by mariantanase** [comment]
Ciao @astagi ,
Purtroppo non funziona, nel senso che i file js vengono caricati correttamente, ma il problema è che l ascelta del servizio rimane disabilitata.

**Comment by astagi** [comment]
@mariantanase @MarcoEmme riapro la issue e direi di darle più priorità.

**Comment by astagi** [comment]
@mariantanase @MarcoEmme questa PR dovrebbe sistemare la problematica definitivamente https://github.com/italia/design-comuni-wordpress-theme/pull/148
