### ISSUE TITLE
pagina novita - Esplora tutte le novità - notizie trovate in ordine alfabetico 

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#136]
Scusate, ma l'elenco delle novità mi aspetterei che fosse in ordine di data decrescente.

Come si può risolvere la questione?
No perchè mai viste le notizie in ordine alfabetico.

**Comment by mariantanase** [comment]
In effetti ho notato anch'io e ho segnalato questo aspetto qui: #17

**Comment by astagi** [comment]
Grazie @mariantanase chiudo come duplicato
