### ISSUE TITLE
Numero verde

### ISSUE THREAD

**Issue by MarcoEmme** [italia/design-comuni-wordpress-theme#137]
Nessuno dei comuni che assisto ha il numero verde, così come nessuno ha né avrai mai il sito bilingue.
Ora, per quanto il riguarda il numero verde, si può impostare in configurazione > Assistenza e contatti. Secondo me, se questo campo non è compilato in home la relativa riga nel box "Contatta il comune" non dovrebbe comparire.
Non vedo da nessuna parte, invece, dove gestire/nascondere la dropdown della lingua.
Naturalmente potrei intervenire io sui sorgenti, volevo solo sapere se questi aspetti potrebbero avere uno sviluppo.

M.

**Comment by mariantanase** [comment]
Io avevo eliminato quel pezzo di codice per multilingua da slimheader in child theme. Non mi risulta che ci sono altre soluzioni soft.

**Comment by MarcoEmme** [comment]
> Io avevo eliminato quel pezzo di codice per multilingua da slimheader in child theme. Non mi risulta che ci sono altre soluzioni soft.

Sì, alla fine è quello che ho fattom grazie del suggerimento.

**Comment by astagi** [comment]
@MarcoEmme non sono così sicuro che nessun comune avrà il sito multilingua (ad esempio https://opencity.comune.bolzano.it/). Direi che se quella parte di template non è necessaria la soluzione di @mariantanase per ora è un valido workaround.

**Comment by MarcoEmme** [comment]
> @MarcoEmme non sono così sicuro che nessun comune avrà il sito multilingua (ad esempio https://opencity.comune.bolzano.it/). Direi che se quella parte di template non è necessaria la soluzione di @mariantanase per ora è un valido workaround.

Non ho detto che nessun comune in Italia avrà il sito multilingua, so benissimo che in alcune aree e in zone ad attrattività turistica sarà indispensabile. Ho detto che i comuni che sto assistendo io (in Pianura Padana, in aree non turistiche, di dimensioni modeste), anche valutando la sostenibilità post PNRR, non implementeranno siti multilingua e per l'appunto ho usato la soluzione di  @mariantanaseì.
