### ISSUE TITLE
LINK CATEGORIA NOTIZIA

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#138]
Buongiorno, 
quando clicco sulla categoria della notizia (avviso, comunicato stamona, notizia)

vedo questo contenuto (che è identico al contenuto in home page) ma la url è corretta ed è:
https://wptest.ecohmedia.com/tipi_notizia/comunicato-stampa/ dunque mi chiedo cosa ci sia di sbagliato.
![Screenshot 2022-12-02 at 09-54-27 Demo PA 2026](https://user-images.githubusercontent.com/119422587/205254432-3934d24b-2e5d-4466-9cc4-ee55df9e3000.png)

**Comment by mariantanase** [comment]
Ciao @cristina-pontarolo ,
Attualmente, quelle sezioni non hanno un template dedicato. 
Vedi #16

**Comment by cristina-pontarolo** [comment]
> Ciao @cristina-pontarolo , Attualmente, quelle sezioni non hanno un template dedicato. Vedi #16
OK, dunque cosa vuol dire? Che non posso avere un elenco di tutti i Comunicati Stampa? 
Che senso ha allora che ci sia la pagina? 
Abbiamo installato tutto l'ambiente Wordpress in base a quello che viene fornito da ITALIA DEGISN, 
pagine, tassonomie, categorie, sono quele fornite del KIT di installazione. CHhe cosa serve avere queste pagine se poi non funzionato?
Boh vabbe, e niente la eliminermeo, così è inutile.

**Comment by astagi** [comment]
@cristina-pontarolo chiudo come duplicato (grazie @mariantanase). I template dedicati non solo per questa parte sono attualmente in lavorazione e richiedono un processo di design e implementazione. Saranno presto disponibili nei rilasci successivi del tema.
