### ISSUE TITLE
Dettaglio Unità Organizzativa - non si vede la mappa ne i contatti

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#139]
nelle Unità Organizzative che ho creato, nel dettaglio della pagina non viene visuaizzata la MAPPA (nel dettaglio dell'evento invece si vede la mappa)

/amministrazione/unita_organizzativa/patrimonio-protezione-e-sicurezza/#contatti
questa è la url per farvi capire, e non vedo ne la mappa ne i contatti (anche se ho selezionato il Punto di contatto che per altro è obbligatorio).

![Screenshot 2022-12-02 at 10-00-53 Patrimonio protezione e sicurezza – Demo PA 2026](https://user-images.githubusercontent.com/119422587/205255555-d74f96f5-7cb1-4754-bffd-8dabf0c9eeb4.png)

**Comment by astagi** [comment]
@cristina-pontarolo buongiorno, in console ha qualche errore JavaScript?

**Comment by cristina-pontarolo** [comment]
Uncaught ReferenceError: L is not defined
    <anonymous> https://wptest.ecohmedia.com/amministrazione/unita_organizzativa/giunta-comunale/:835
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        $
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
[giunta-comunale:835:25](https://wptest.ecohmedia.com/amministrazione/unita_organizzativa/giunta-comunale/)
    <anonima> https://wptest.ecohmedia.com/amministrazione/unita_organizzativa/giunta-comunale/:835
    jQuery 13
        e
        t
        (Asinc.: setTimeout handler)
    l
        c
        fireWith
        fire
        c
        fireWith
        ready
        $
        (Asinc.: EventListener.handleEvent)
    <anonima>
        <anonima>
        <anonima>

**Comment by marco-nanni** [comment]
Ho risolto parzialmente il probklema. Mancava il caricamento della libreria assets/js/components/leaflet/leaflet.js
Nel child ho aggiunto il seguente codice:
`
add_action( 'wp_enqueue_scripts', 'load_leaflet' );
function load_leaflet() {
	wp_enqueue_script( 'leaflet', get_template_directory_uri() . '/assets/js/components/leaflet/leaflet.js');
}
`
Ora la mappa si vede, ma il probelma che questa pagina ne ha due e quindi l'errore è diventato il seguente:
**_Uncaught Error: Map container is already initialized._**

**Comment by marco-nanni** [comment]
Risolto.
![pa_2026_errore_mappa_2](https://user-images.githubusercontent.com/118733111/208622197-f6fb3485-1b3a-41ed-82ca-18c35170b214.PNG)

E' stato modificato il modulo **design-comuni-wordpress-theme-main/template-parts/luogo/map.php**:
`
<?php
global $luoghi;
$prefix = '_dci_luogo_';
$arr_luoghi = array();
$c=0;
foreach ($luoghi as $luogo) {
    $posizione_gps = dci_get_meta("posizione_gps", $prefix, $luogo->ID);
    if ($posizione_gps && $posizione_gps["lat"] && $posizione_gps["lng"]) {
        $indirizzo = dci_get_meta("indirizzo", $prefix, $luogo->ID);
        $arr_luoghi[$c]["post_title"] = $luogo->post_title;
        $arr_luoghi[$c]["permalink"] = get_permalink($luogo);
        $arr_luoghi[$c]["gps"] = $posizione_gps;
        $arr_luoghi[$c]["indirizzo"] = $indirizzo;
        $arr_luoghi[$c]["id"] = $luogo->ID;
        $c++;
    }
}

if($c) { ?>
    <div class="map-wrapper map-column mt-4">
        <div class="map-wrapper">
            <div class="map" id="map_all_<?php echo $arr_luoghi[0]["id"] ?>" style="width: 100%; padding-bottom: 56.25%;"></div>
        </div>
    </div>
    <script>
        jQuery(function() {
            var mymap = L.map('map_all_<?php echo $arr_luoghi[0]["id"] ?>', {
                zoomControl: true,
                scrollWheelZoom: false
            }).setView([<?php echo $arr_luoghi[0]["gps"]["lat"]; ?>, <?php echo $arr_luoghi[0]["gps"]["lng"]; ?>], 13);

            let marker;
            <?php foreach ($arr_luoghi as $marker){ ?>

            marker = L.marker([<?php echo $marker["gps"]["lat"]; ?>, <?php echo $marker["gps"]["lng"]; ?>, { title: '<?php echo addslashes($marker["post_title"]); ?>'}]).addTo(mymap);
            marker.bindPopup('<b><a href="<?php echo $marker["permalink"] ?>"><?php echo addslashes($marker["post_title"]); ?></a></b><br><?php echo addslashes($marker["indirizzo"]); ?>');

            <?php } ?>

            // add the OpenStreetMap tiles
            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '',
                maxZoom: 18,
            }).addTo(mymap);

            var arrayOfMarkers = [<?php foreach ($arr_luoghi as $marker){ ?> [ <?php echo $marker["gps"]["lat"]; ?>, <?php echo $marker["gps"]["lng"]; ?>], <?php } ?>];
            var bounds = new L.LatLngBounds(arrayOfMarkers);
            mymap.fitBounds(bounds);
        });
    </script>
<?php } ?>
`

**Comment by danieledexter** [comment]
Ciao, ho seguito entrambi i consigli:

- modificato il functions.php
- modificato map.php

Ora però la mappa viene visualizzata così:
![image](https://user-images.githubusercontent.com/115085709/209839087-3b6a7f0c-a12d-4df2-8b45-44d9420c3f1d.png)

Qualcuno ha riscontrato lo stesso problema?

Grazie

**Comment by danieledexter** [comment]
Non conosco bene il javascript, ma ho visto in debug che nel foreach l'array $marker veniva mostrato 2 volte.
Uno valorizzato e uno vuoto, che credo sia quello che veniva visualizzato.
Ho aggiunto un controllo nel foreach per mostrare solo dove ci sono dei valori e così ha funzionato.

Domanda: Se in un luogo ho associato un marker, per quale motivo dovrei vedere 2 array?

Grazie per l'aiuto

**Comment by astagi** [comment]
@danieledexter grazie! Da verificare che questo fix possa essere messo all'interno del tema principale, hai modo di aprire una PR?
