### ISSUE TITLE
Area Personale

### ISSUE THREAD

**Issue by eb-ai4** [italia/design-comuni-wordpress-theme#141]
E' stata implementata l'area personale nel tema? Non sembra essere presente. 

Attualmente sono stati presentati 2 diversi modelli. Quale è il modello corretto da utilizzare?

1. 
https://italia.github.io/bootstrap-italia/docs/esempi/comuni/template-area-personale/

2.
https://italia.github.io/design-comuni-pagine-statiche/servizi/servizi-pagamento-area-personale.html

**Comment by guidobuldrighini** [comment]
Buongiorno, c'è qualche novità a riguardo?

**Comment by astagi** [comment]
@eb-ai4 @guidobuldrighini questa evolutiva per il momento possiamo chiuderla. Per tale implementazione occorrerà un progetto ad hoc che ancora non abbiamo in cantiere.
