### ISSUE TITLE
Informazioni mancanti nella richiesta di appuntamento

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#144]
Buongiorno,
sto implementando la parte di invio dei dati per la richiesta di appuntamento e mi sono accorto che mancano delle informazioni rispetto al payload originale:

```json
{
	  "office": {
		"id": "117",
		"name": "Ufficio ambiente"
	  },
	  "place": {
		"nome": "Municipalità 1",
		"indirizzo": "Via Roma 1",
		"apertura": "lun, mar, mer 10:00 -12:00",
		"id": "id-luogo-123"
	  },
	  "appointment": {
		"startDate": "2022-07-04T09:00",
		"endDate": "2022-07-04T09:45"
	  },
	  "service": {
		"id": "101",
		"name": "Iscrizione alla Scuola dell’infanzia"
	  },
	  "moreDetails": "Dettagli aggiuntivi",
	  "name": "Mario",
	  "surname": "Rossi",
	  "email": "mario.rossi@mail.com"
}	
```
Mentre quello che ottengo è il seguente payload:
```json
{
    "office": {
        "id": "406",
        "name": "Bilancio e tributi"
    },
    "place": {
        "nome": "",
        "indirizzo": "",
        "apertura": "",
        "id": ""
    },
    "appointment": {
        "startDate": "2023-01-04T09:45",
        "endDate": "2023-01-04T10:30"
    },
    "service": {
        "id": "135",
        "name": "Informazioni sull\u2019Imu (Imposta municipale propria)"
    },
    "moreDetails": "",
    "name": "Marco",
    "surname": "Nanni",
    "email": "marco.nanni@ecohmedia.com"
}
```
Come potete notare mancano i dati relativi alla "place" e "moreDetails".

**Comment by marco-nanni** [comment]
Aggiornamento del problema.
Ho loggato i dati in arrivo dalla vairbile $_POST e ho scoperto che i dati relativi ai dettagli aggiuntivi e alla "place" sono presenti, tranne 'ID. Per l'apertura ho dovuto eliminare un po' di tag HTML che si porta appresso.
Quindi sono riuscito ad aggiungerli al payload.
    "place": {
        "nome": "Sede del Comune Demo",
        "indirizzo": "Via Milano 32",
        "apertura": "lun, mar, mer 08:30 -13:00",
        "id": ""
    }
    Ci siamo quasi.

**Comment by astagi** [comment]
Fantastico @marco-nanni grazie! Per qualsiasi cosa resto a disposizione

**Comment by zetareticoli** [comment]
@marco-nanni possiamo considerare chiusa la issue?

**Comment by marco-nanni** [comment]
@zetareticoli se volete, si. 
Rimmarrebbe da mettere a disposizione l'ID della place per completare i dati.

**Comment by astagi** [comment]
@marco-nanni ma per risolvere questa issue se non ricordo male hai fatto del codice custom giusto? c'è modo di metterlo all'interno del tema?

**Comment by marco-nanni** [comment]
@astagi Esatto. Ma naca l'id che proprio non è disponibile nei dai $_POST.

**Comment by astagi** [comment]
Ok vediamo di mettere a disposizione l'ID allora, lascerei aperta la issue. @marco-nanni se puoi girarci il codice che hai utilizzato per estrapolare gli altri dati possiamo metterlo intanto nel tema su un branch, e da lì facciamo passare anche l'ID

**Comment by marco-nanni** [comment]
@astagi Ok.

```
if(array_key_exists("place", $params) && $params['place'] != "null") {
	$place_obj = json_decode(stripslashes($params['place']), true);
}
```
Qui è il punto dove ho "ripulito" l'orario di apertura:
```
$apertura = strip_tags($place_obj['apertura']);
$apertura = str_replace("\t", '', $apertura);
$apertura = str_replace("\n", '', $apertura);
$apertura = str_replace("\r", '', $apertura);
```

**Comment by astagi** [comment]
@marco-nanni hai modo di condividere l'intero file invece dei pezzi di codice? almeno proviamo a fare una PR. Grazie!

**Comment by astagi** [comment]
Perdonami @marco-nanni ma su functions.php hai inserito questa parte di codice, ma dove la gestivi all'interno del tema generale?

**Comment by marco-nanni** [comment]
No. L'ho tolta da li. Proprio per ridurre al jminimo le modifche al tema principale.
Ho associato alla chiamata ajax origuinale in **funzioni_trasversali.php**:
`
add_action("wp_ajax_save_appuntamento" , "dci_save_appuntamento");
`
un'altra action in **functions.php** del child (li invio ache la mail e preparo il payload e in futuro vi sarà l'invio del payload:
`
add_action("wp_ajax_save_appuntamento" , "dci_email_appuntamento", 10);
`

**Comment by astagi** [comment]
ok @marco-nanni hai modificato anche `booking.js`?

**Comment by marco-nanni** [comment]
@astagi No, Per ora no. Altrimenti te lo avrei scritto.

**Comment by zetareticoli** [comment]
@marco-nanni se apri una PR con le tue modifiche, integriamo nel tema principale

**Comment by marco-nanni** [comment]
@zetareticoli come spiegavo qualche giorno fa ad @astagi non posso effettuare questa operazione al momento, putroppo.
