### ISSUE TITLE
Suggerimento: accentrare gli orari di apertura

### ISSUE THREAD

**Issue by MarcoEmme** [italia/design-comuni-wordpress-theme#145]
Questa mattina, compilando le schede "Area organizzativa" di un comune, mi accorgo di quanto sarebbe utile che gli orari di apertura fossero accentrati, per esempio tra i "Punti di contatto" e gestirli in maniera analoga.
Nel mio caso, a favore del cittadino stavo compilando le unità denominate "Anagrafe e stato civile", "Servizi elettorali" e "Servizi scolastici" i quali, tuttavia, essendo un piccolo comune, sono gestiti dallo stesso addetto, ovviamente, con gli stessi orari di apertura al pubblico.
In caso di modifiche bisogna rincorrere tutte le schede delle unità. Non un grosso problema, per carità, essendo solo tre nel mio caso, ma qualche persona poco pratica potrebbe dimenticarsi di aggiornare qualche pezzo di informazione.
Per la cronaca: gli orari li posiziono nella casella "Ulteriori informazioni".
M.

**Comment by astagi** [comment]
Grazie per il suggerimento @MarcoEmme !
