### ISSUE TITLE
Errore apparso sull'inserimento scheda "Documento pubblico"

### ISSUE THREAD

**Issue by MarcoEmme** [italia/design-comuni-wordpress-theme#147]
Segnalo un errore che mi è apparso creando una nuova scheda "Documento pubblico". Preciso che, apparentemente, tutto viene salvato correttamente.
M.

![Immagine14](https://user-images.githubusercontent.com/119533313/207379431-5a9e6ab6-72f4-407d-9367-0500fe8d795c.jpg)

**Comment by astagi** [comment]
@MarcoEmme segnalato il warning, puoi disabilitare comunque il fatto che Wordpress mostri gli errori, per ora lo segnamo come miglioramento ma in coda ci saranno delle verifiche.
