### ISSUE TITLE
Gestione dei dati relativi al rating della pagina (valutazione), richiesta assistenza e prenotazione appuntamento nel backend

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#149]
Buongiorno,
per la gestione dei dati che vengono attualmente memorizzati in WordPress, relativi al rating della pagina, alla richiesta di assistenza e richiesta di appuntamento, è previsto un ulteriore sviluppo da parte vostra per finalizzarne l'utilizzo da parte del personale del comune?!

Grazie.

**Comment by zetareticoli** [comment]
Ciao @marco-nanni,
no non sono previsti al momento ulteriori sviluppi. Resta il fatto che questi sistemi debbano essere integrati al meglio con i sistemi di backend dei singoli enti e pertanto non possa essere un modello a prevedere ogni singolo caso.

Le tre funzionalità da te citate comunque registrano nel _back-office_ di Wordpress i dati inviati, li trovi rispettivamente in:
- Appuntamenti
- Tickets
- Valutazioni

**Comment by marco-nanni** [comment]
@zetareticoli "**_non possa essere un modello a prevedere ogni singolo caso_**" 
Prevedere ogni singolo caso non è possibile ovviamente, ma predisporre uno standard anche minimale di gestione di questi dati si, però. Oltre tutto queste funzionalità non sono totalmente gestibili dal tema child. Quindi andrebbero trasformati in plugin. Questo per evitare di avere decine e decine di temi customizzati e doverli gestire uno a uno.

**Comment by danimog** [comment]
Scusate se "riapro" questa discussione ma stavo cercando di sviluppare un qualcosa che leggesse i dati di cui si parlava. I vari dati vengono registrati nel back-office come "draft". è corretto? (non si riesce neppure da back-office a trasformarli in publish)
Ho provato poi a registrare una di queste funzioni di modo che restituisca i valori come API ma non ottengo alcun risultato. 
Qualcuno ha suggerimenti?

**Comment by zetareticoli** [comment]
@marco-nanni in linea di principio sono d'accordo con te, ma la realizzazione del tema non aveva in "scope" anche lo sviluppo di plugins dedicati.
