### ISSUE TITLE
Inserimento e gestione Documento Pubblico

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#15]
Buongiorno,
Quando cerco di inserire un nuovo documento PDF attraverso "Documenti Pubblici" > "Aggiungi un Documento Pubblico", non mi è chiaro l'utilizzo dei campi: "URL Documento" (campo obbligatorio) e "Documento: Carica file".

![Screenshot 2022-08-08 at 15-25-09 Aggiungi un Documento Pubblico ‹ Comune di Valenzano — WordPress](https://user-images.githubusercontent.com/3976174/183432110-5f6cc2f2-8876-4f32-8f93-6c721eb96c8c.png)

Il documento che voglio inserire è un nuovo PDF e lo carico giustamente utilizzando il secondo campo "**Documento: Carica file**".
Dovrebbe essere sufficiente, ma il campo URL Documento è uno obbligatorio e lo devo compilare per forza.

L'obbligatorietà non dovrebbe essere o un campo o l'altro ?
Come la devo gestire ?

Grazie

**Comment by HshMatera** [comment]
Buongiorno,
anche io ho trovato ambigua la definizione dei due campi. Inoltre la pagina del documento non è completa rispetto ai contenuti inseriti. 
![Cattura](https://user-images.githubusercontent.com/82446929/186352831-e1a0c1fa-1986-47de-907f-5e88d80f7ba6.PNG)

mancano:

- protocollo
- immagine
- documento da scaricare
- ufficio responsabile
- autore
- formati disponibili
- licenza di distribuzione
- servizi
- temi e scadenze
- ulteriori informazioni

come se mancasse la parte della sidebar di sinistra.
Come mai?
Grazie

**Comment by zetareticoli** [comment]
Ciao @mariantanase , grazie per la segnalazione, effettivamente dovrebbe funzionare come da te descritto. Verifichiamo e in caso ti aggiorno qui.
