### ISSUE TITLE
pagina VIVERE IL COMUNE

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#151]
TEMA 1.4.2

Nella pagina nomecomune.it/vivere-il-comune/

ci siamo accorti che i PULSANTI, "tutti gli eventi" e "tutti i luoghi" non hanno il LINK all'interno del tag <a>, e questi pulsanti sono creati dinamicamente: gli eventi sono 4, e in anteprima ne vedo 3, mi aspettavo di poter vedere l'elenco degli eventi cliccando su TUTTI GLI EVENTI ma invece non esiste nessun link.
A me sembra che nella versione precedente del tema funzionasero.

Vi allego il CODICE HTML e un'anteprima della pagina:
![Schermata 2022-12-19 alle 16 19 52 (2)](https://user-images.githubusercontent.com/119422587/208459390-79882ad1-7dec-496d-9fd5-f29d67204fd1.png)

![Screenshot 2022-12-19 at 16-19-34 Vivere il Comune – Demo PA 2026](https://user-images.githubusercontent.com/119422587/208459482-9cb2719a-7c5c-4cb0-b17c-58b3b9613476.png)

**Comment by zetareticoli** [comment]
Ciao,
i templates ad oggi non sono disponibili. Prevediamo di rilasciarne la versione statica nel Q1 2023

**Comment by cristina-pontarolo** [comment]
> Ciao, i templates ad oggi non sono disponibili. Prevediamo di rilasciarne la versione statica nel Q1 2023

Il template "vivere-il-comune" associato alla pagina "Vivere ilcomune", è già presente nel tema base, non lo abbiamo creato noi. DUnque mi aspetterei che funzionasse.

Come è possibile rilsciare un TEMA in cui molti template non esistono ancora???
Comnque nella precedente versione del tema funzionava.
