### ISSUE TITLE
Amministrazione - Organi di Governo

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#152]
alle pagine 
nomecomune.it/amministrazione/
nomecomune.it/amministrazione/organi-di-governo/

non vedo ne il campo RICERCA, ne a destra il menu delle categorie relative alle AREE AMMINISTRATIVE.

vi allego due esempi: comune di Lecco che visualizza la ricerca e a destra il sottomenu
![Screenshot 2022-12-20 at 09-59-51 Organi di Governo - Provincia di Lecco](https://user-images.githubusercontent.com/119422587/208626878-811709c1-b00c-40f9-9e4b-1f1c3cc57ef2.png)

e qui l'anteprima della mia pagina di ORGANI DI GOVERNO
![Uploading Screenshot 2022-12-20 at 10-00-16 Organi di Governo – Demo PA 2026.png…]()

**Comment by zetareticoli** [comment]
Ciao @cristina-pontarolo, quella da te allegata è la versione precedente del modello. Dalla v2.0.0 infatti non sono più presenti le voci sulla sinistra (Aree in Amministrazione) né il campo di ricerca sotto il titolo della pagina.

Ad oggi, il tema non include il template dedicato al _content-type_ Unità Organizzativa. La fase di progettazione è conclusa e pensiamo di rilasciare il template statico a inizio Gennaio 2023.
