### ISSUE TITLE
Pagina Servizi - Esplora per categoria non mostra nulla

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#154]
Salve,
Ho ricreato una nuova pagina "Servizi e Prestazioni" al posto della "Servizi" e collegata al menu. Sostituite tutte le categorie di servizio con le altre personalizzate.
Adesso cliccando sulla voce di menu "Servizi e Prestazioni", la sezione "Esplora per categoria" non carica/mostra le nuove categorie. Nulla.

Abilitando il debug, mi esce questo:

```
Warning: Attempt to read property "term_id" on bool in 
D:\bearsampp\www\demo\wp-content\themes\design-comuni-wordpress-theme\template-parts\servizio\categorie.php
on line 21
```

Come posso risolvere ?

**Comment by astagi** [comment]
Ciao @mariantanase non saprei davvero :( non so quanto sia attinente al tema, forse è proprio un bug nella tua implementazione?

**Comment by mariantanase** [comment]
Credo che era un problema di PHP. Grazie
