### ISSUE TITLE
/punto_contatto/

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#156]
Nel mio sito demo
dal dettaglio del singolo punto di contatto https://wptest.comunedemo.com/punto_contatto/albo-pretorio/
posso cliccare sul breadcrumbs "punti di contatto", e atterrare in un contentuo generato dinamicamente che visualizza l'elenco di tutti i punti di contatto.
Graficamente la pagina appare disallineata.
Vedi allegato
![Screenshot 2022-12-21 at 15-14-12 Punti di contatto – Demo PA 2026](https://user-images.githubusercontent.com/119422587/208926251-d51949dd-2c7e-4fb7-a4a3-67e5ffdcc59c.png)

Inoltre il dettaglio del PUNTO DI CONTATTO, visualizza solo la descrisione.

**Comment by zetareticoli** [comment]
Ciao @cristina-pontarolo, non abbiamo previsto un template per il punto di contatto, per questo motivo WordPress ti mostra una pagina senza alcuna struttura.
