### ISSUE TITLE
TEMPLATE PERSONA PUBBLICA

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#157]
Buongiorno, scusatemi,
Ho riscontrato che la pagina di dettaglio della persona pubblica, non visualizza tutti i dati inseriti nel backend:
vedi allegati. Ho viato che un utente ha creato il template, ma nel nostro caso non funziona.
noi utilizziamo "Design Comuni Italia" Versione: 1.4.0.

Dettaglio persona pubblica backend
![Screenshot 2022-12-21 at 15-45-14 Modifica la Persona Pubblica “Paolo Verdi – Sindaco” ‹ Demo PA 2026 — WordPress](https://user-images.githubusercontent.com/119422587/208932299-b4307cb5-2a2e-4c5b-a0b8-caa93b6d2f80.png)

Dettaglio persona puhblica frontend
![Screenshot 2022-12-21 at 15-44-58 Paolo Verdi – Sindaco – Demo PA 2026](https://user-images.githubusercontent.com/119422587/208932434-6eb0f4e5-a706-4887-bbf9-a2b35bf6a6d7.png)

**Comment by astagi** [comment]
@cristina-pontarolo duplicato di #71
