### ISSUE TITLE
Segnala disservizio non funzionante (template non presente)

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#158]
Buongiorno,
il link "segnala disservizio" non risulta funzionante e non è presente nessun template a riguardo.
Questo servizio sarà gestito dal sito tipo gli altri tre: richiesta assistenza, valutazione pagine e richiesta prenotazione, oppure sarà un servizio esterno?

**Comment by zetareticoli** [comment]
Ciao @marco-nanni,
per la funzionalità di Segnalazione Disservizio ad oggi esistono solamente i templates statici che trovi [qui](https://italia.github.io/design-comuni-pagine-statiche/servizi/) (scorri fino alla fine della pagina, sono in fondo).

I templates possono essere utilizzati per una successiva implementazione da parte di enti e fornitori.

Essendo una funzionalità che necessita un'integrazione con sistemi di backend complessi, non è prevista la presenza nel tema Wordpress.
