### ISSUE TITLE
Pagina Novità. Le schede Avviso, Comunicato stampa e News, non hanno un template dedicato

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#16]
Nella pagina "**Novità**" alla sezione "**Esplora per categoria**" vengono mostrate le schede di _Avviso_, _Comunicato stampa_ e _News_.
Ogni scheda dovrebbe caricare una pagina con le notizie filtrate in base al tipo di notizia (Avviso, Comunicato stampa e News).
Attualmente, cliccando su qualsiasi delle 3 schede, viene ricaricata sempre la home page.
![categorie-news](https://user-images.githubusercontent.com/3976174/183652799-a8c48fbd-2fc0-4170-8e06-a2ad718e343f.png)

**Comment by zetareticoli** [comment]
Ciao @mariantanase, il template della lista per i contenuti filtrati per tipologia non è incluso in questa versione del tema WordPress. 
Posso suggerirti di utilizzare la lista di news a griglia come visibile nella sezione "Esplora tutte le novità" (sfondo grigio) con o senza input di ricerca.

**Comment by giuseppetucci** [comment]
Eventualmente come si può eliminare le voci delle categorie?![image](https://user-images.githubusercontent.com/111513916/187672091-4f1afe3c-b543-4bcb-9bb5-7eaab5ef5f87.jpeg)

**Comment by mariantanase** [comment]
> Eventualmente come si possono eliminare le voci delle categorie?!

Se vuoi eliminare la sezione "Esplora per categoria" puoi modificare il template "novità" eliminando la sezione "argomenti".

**Comment by mariantanase** [comment]
Ricordo che ancora non esiste un template per filtrare le notizie in base alla tipologia.
Ci sono notizie in merito sullo sviluppo ?
