### ISSUE TITLE
Link su Footer scompaiono

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#161]
Ho notato che alcune volte quando alla mattina controllo il mio sito, i link che ho modificato nel footer scompaiono.
Non capisco quale sia il motivo, perchè ad esempio ieri sera funzionava e non sono state fatte modifiche sul footer.

Qualcuno sa dirmi da cosa può dipendere o come risolverlo?

Grazie in anticipo

**Comment by astagi** [comment]
Ciao @danieledexter non capisco cosa succede

**Comment by danieledexter** [comment]
Ciao, per fare un esempio , ho inserito il link di una pagina sulla voce di amministrazione trasparente presente sul footer.
Mi sono poi accorto in un secondo momento che il link non c'era più e che il link puntava alla pagina corrente.

Credo che questo si sia verificato a seguito del cambio tema, da figlio a padre e poi impostato nuovamente a figlio.

Così è più chiaro?

**Comment by astagi** [comment]
Ok grazie @danieledexter mi mancava questo passaggio del cambio tema. Grazie!

**Comment by zetareticoli** [comment]
@danieledexter non abbiamo riscontro di questo bug nel tema, può darsi sia un problema di configurazione.
