### ISSUE TITLE
Pag. Novità - Elenco delle novità - pur aggiornando il tema all'ultima versione, quando selezioni Carica altri risultati, le news restano in ordine alfabetico.

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#163]
Buongiorno, 
abbiamo aggiornato il tema all'ultima versione (1.4.3),
ma andando in Novità, notiamo che l'ordine cronologico inverso per le news viene rispettato solo per le ultime 3:
![Screenshot 2023-01-09 at 10-07-19 Novità – Demo PA 2026](https://user-images.githubusercontent.com/119422587/211273622-59d283dc-ff22-4cc8-b82a-bc61afda6b55.png)

Una voltache l'utente clicca si "Carica altri risultati", l'elenco ritorna in ordne alfabetico:
![Screenshot 2023-01-09 at 10-07-33 Novità – Demo PA 2026](https://user-images.githubusercontent.com/119422587/211273729-62527e19-fa56-442c-ab3c-8df225b03f3b.png)

Purtroppo per l'elenco delle novità credo sia necessario poterle vedere innordine cronologico inverso.

PS: la scritta "n° notizie trovate in ordine alfabetico " che appare sotto a "Esplora tutte le novità" andremme modificata, in quanto forviante.

Grazie attendo un riscontro al più presto.

**Comment by astagi** [comment]
Buonasera @cristina-pontarolo sembra che da design sia stato volutamente scelto di caricare le notizie in ordine alfabetico. Per ora chiudo la segnalazione e riporto al fornitore la problematica per una eventuale futura implementazione.

Grazie!
