### ISSUE TITLE
Prenotare un appuntamento - disponibilità orari e invio email all'ufficio

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#164]
Buongiorno,

Ho notato che attualmente (v.1.4.3) si possono effettuare un infinità di prenotazioni nello stesso giorno e lo stesso orario presso una struttura. E questo non mi sembra un comportamento normale. Immagino il funzionario di quel ufficio quando si presenteranno 100 utenti nello stesso giorno e allo stesso orario per effettuare un servizio specifico.
Si può prendere in considerazione in futuro di implementare una verifica tra i appuntamenti inseriti? e se un utente ha fatto una prenotazione, quella fascia oraria non dovrebbe essere più disponibile e di non mostrarla nella fase di prenotazione ?
Spero che mi sono spiegato.
La seconda cosa, se possibile implementare l'invio di una email all'ufficio selezionato con i dati della prenotazione.

Grazie

**Comment by marco-nanni** [comment]
Tra le altre ciose nei dati dell'appuntamento non viene registrata l'email del richiedente.

**Comment by astagi** [comment]
@mariantanase i dettagli di una gestione degli slot orari è lasciata ai singoli enti perchè in anticipo non possiamo sapere quanta disponibilità c'è. 

@marco-nanni puoi aprire una issue ad hoc nel caso?

**Comment by mariantanase** [comment]
Ok per la gestione degli slot capisco e sono d'accordo, ma per la funzionalità come si può impostare dei limiti ? 
Anche se io inserisco nel file json orari personalizzati per ogni 10 minuti durante un giorno ad esempio, questo non impedisce che 10 utenti scelgono lo stesso slot orario.
A questo aspetto mi riferivo.
Sarebbe interessante l'idea di implementare una gestione del'inserimento degli orari lato backend.
