### ISSUE TITLE
Pulsante "Vai al calendario eventi"

### ISSUE THREAD

**Issue by FrancescaFrigerio** [italia/design-comuni-wordpress-theme#166]
Buongiorno,
volevo segnalare delle problematiche legate al pulsante **Vai al calendario eventi**, presente nel dettaglio degli eventi.
Dal lato utente, la frase sembra far presupporre che si verrà indirizzati ad un'ipotetica pagina del sito comunale con un calendario eventi, invece rimanda al proprio calendario di Google. Inoltre, quando si viene reindirizzati al proprio calendario di Google, l'utente in autonomia dovrebbe inserire l'evento andando a ricercare la data e l'ora in cui si terrà.

Grazie e buon lavoro
Francesca

**Comment by zetareticoli** [comment]
Ciao @FrancescaFrigerio, in una delle ultime release il pulsante del calendario era stato rimosso perché manca la funzionalità da te descritta.

Ti consiglio di aggiornare il tema alla [v1.4.3](https://github.com/italia/design-comuni-wordpress-theme/releases/tag/v1.4.3)
