### ISSUE TITLE
File font Titillium Web errore 404

### ISSUE THREAD

**Issue by guidobuldrighini** [italia/design-comuni-wordpress-theme#167]
Salve, volevo segnalare una problematica inerente all'errore 404 su tutti i file del font Titillium Web richiamati dal template.
Come da screenshot allegato i file dei font Titillium vengono richiamati da una directory inesistente.
I file sono presenti nella directori fonts dentro la cartella assets.
Ho effettuato il test sia in locale su docker sia online.
Grazie e buon lavoro
Guido Buldrighini

![Schermata del 2023-01-24 00-01-54](https://user-images.githubusercontent.com/1243192/214171829-e697a5cf-0d9e-4368-ba6e-21751a3215e2.png)

**Comment by mariantanase** [comment]
E stato segnalato l'errore in #132 .

**Comment by astagi** [comment]
@mariantanase nella #132 mi sembra ci sia la soluzione corretta, con la variabile globale si setta il path dei font.

**Comment by mariantanase** [comment]
Purtroppo quella guida non funziona per me, ed ho testato su varie installazioni, provato e riprovato.
Ad ogni modo ho notato che a partire dalla 2.2.0 di bootstrap italia il problema si risolve. Basta aggiornare bootstrap italia nel tema. Spero che la nuova versione del tema avrà già aggiornato bootstrap, che adesso e arrivato alla 2.3.2

**Comment by astagi** [comment]
@mariantanase @guidobuldrighini stiamo procedendo ad aggiornare BSI alla 2.3.2 sulla parte degli statici e di conseguenza qua.

**Comment by astagi** [comment]
@mariantanase @guidobuldrighini aggiornato, ora rilasciamo la 1.5.0 https://github.com/italia/design-comuni-wordpress-theme/commit/ddaaf81a64fdb9dbe810ca0796c32d44b9bb49a3

**Comment by guidobuldrighini** [comment]
@astagi grazie mille, ora funziona correttamente
