### ISSUE TITLE
Aggiornamento tema automatico

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#168]
Buongiono, 
vorrei sapere se avrete intenzione di rendere scaricabile/aggiornabile il tema direttamente da WordPress, senza usare lo zip per capirci, come avviene per gli altri temi standard. Lo chiedo in un ottica di aggiornamento massivo tramite tool tipo MainWP.

Grazie.

**Comment by astagi** [comment]
Buongiorno @marco-nanni , risolverebbe inserire il tema nel marketplace. In alternativa se vuoi puoi provare qualcosa come Git Updater.

**Comment by marco-nanni** [comment]
Buongiorno @astagi, 
inserire i tema nel marketplace risolve ed è assolutamente necessario, secondo me.

**Comment by astagi** [comment]
Concordo, chiudo come duplicato di https://github.com/italia/design-comuni-wordpress-theme/issues/11 e ci rifacciamo da lì. Grazie
