### ISSUE TITLE
Pagina Novità. Ordinamento notizie nella sezione "Esplora tutte le novità"

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#17]
Nella pagina **Novità**, la sezione **Esplora tutte le novità** mostra le notizie in ordine alfabetico.
Credo che dovrebbero essere **ordinate per data**, aggiungerei in ordine decrescente.
[Architettura informazione. Cap. 2.1.6. Pagine lista di primo livello](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/v2022.1/modello-sito-comunale/architettura-informazione.html#pagine-lista-di-primo-livello) .

**Comment by mariantanase** [comment]
Buon anno a tutti !
Non vorrei sbagliare ma dopo l'aggiornamento del tema alla 1.4.3, nella sezione "Esplora tutte le novità" noto due problemi:
1. Subito sotto la casella di ricerca compare ancora il testo "x notizie trovate **in ordine alfabetico**" (magari è sfuggito);
2. Le 3 notizie che vengono caricate (prima del pulsante "Carica altri risultati") sono ordinate correttamente per data, ok. Ma se clicco su "Carica altri risultati" vengono mostrate tutte le notizie in ordine alfabetico non per data;

**Comment by Cam-al** [comment]
riscontro lo stesso problema ho provato a modificarlo come ho spiegato qua #296 e funziona ma c'è ancora qualche problema quando si compila il campo data di pubblicazione o di scadenza nella notizia. Se non viene compilato in nessuna notizia le modifiche potrebbero andare bene, ma se compilato mischia le notizie con data di pubblicazione precedente con quelle che più recenti che non hanno il campo compilato. 
l'ordinamento delle notizie in ordine alfabetico non ha molto senso in questo contesto è necessario quello di pubblicazione

**Comment by malikmalhan** [comment]
+1
