### ISSUE TITLE
Gestione apostrofi nelle stringhe

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#171]
Buongiorno, bisognerebbe gestire gli apostrofi
![Schermata 2023-01-31 alle 15 30 26](https://user-images.githubusercontent.com/118733111/215790414-f462816e-f274-44e3-83ab-6a7c55a4f965.png)

Grazie.

**Comment by marco-nanni** [comment]
Buongiono @astagi,
potete chiudere l'issue. Il probelma risulta risoltio con la vostra fix.

Grazie.

![pa_2026_caratteri_speciali](https://user-images.githubusercontent.com/118733111/217760152-ff6c4973-e845-4bd3-99ae-b75fe037fc5e.PNG)

**Comment by marco-nanni** [comment]
@astagi andrebbe aggiornato anche assistenza.js in src.

**Comment by enrimk** [comment]
> @astagi andrebbe aggiornato anche assistenza.js in src.

Proprio così: infatti nel frattempo nella 770124b assistenza.js è stato sovrascritto con la versione non ancora corretta, minificata automaticamente da -src, e il bug [è ritornato](https://github.com/italia/design-comuni-wordpress-theme/issues/346).
