### ISSUE TITLE
Tempo di lettura

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#173]
Il tempo di lettura come viene calcolato ?
Perché, avevo inserito una notizia breve di un paragrafo e mi compariva il tempo di lettura 1 minuto. Perfetto.
Ma oggi ho aperto l'articolo stesso e l'ho modificato aggiungendo molti altri paragrafi, ma il tempo di lettura non è cambiato, mi da sempre 1 minuto, il che non è assolutamente corretto. Ci vuole almeno 5 minuti.

**Comment by astagi** [comment]
Grazie @mariantanase dovrebbe risolversi con quel fix

**Comment by mariantanase** [comment]
Perfetto!
Grazie
