### ISSUE TITLE
Campo "Multimedia" nel'articolo

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#174]
Ciao,
Ci sono novità in base a questa problematica segnalata ?

> Confermo invece che il field "Gallerie multimediali" non funziona. Le immagini che vengono caricate non compaiono a front-end. Apriremo comunque una issue relativa al funzionamento delle Gallerie. 

Grazie

_Originally posted by @zetareticoli in https://github.com/italia/design-comuni-wordpress-theme/issues/8#issuecomment-1245216040_

**Comment by astagi** [comment]
Ciao @mariantanase è una problematica chiusa tanto tempo fa, c'è qualcosa che ancora non funziona?

**Comment by mariantanase** [comment]
Ciao @astagi , quella issue conteneva 3 domande di cui la 2 e la 3 erano risolte ma come aveva confermato anche @zetareticoli , in merito al punto 1 si stavano facendo delle verifiche in quanto le gallerie multimediali non funzionava, e non funzionano ancora.
Così mi risulta.

**Comment by astagi** [comment]
Grazie @mariantanase questa è una evolutiva che pensiamo di aggiungere nelle prossime versioni!

**Comment by abmcr** [comment]
All'interno della pagina Evento (single-evento.php) la galleria viene visualizzata.
Per inserirla anche nelle notizie aggiungere dopo la riga 30

$gallery = dci_get_meta("multimedia", $prefix, $post->ID);

e, alla riga 198

<?php if (is_array($gallery) && count($gallery)) {
    get_template_part("template-parts/single/gallery");
} ?>


Il blocco però crea un <h3 class='h4'.. diverso da <h4 id='allegati' .. che ad esempio si  ha per gli allegati.

È corretto oppure deve essere anche lui un h4?
Nei file di esempio HTML non c'è il markup corrispondente... :-(
