### ISSUE TITLE
Servizi di richiesta appuntamento - disponibilità orari

### ISSUE THREAD

**Issue by guidobuldrighini** [italia/design-comuni-wordpress-theme#177]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

In fase di richiesta appuntamento, nello step "Data Orario" viene proposta una dropdown con il mese e una volta scelto il mese vengono proposte 3 date con relativi orari, ma questi orari non sono stati impostati da nessuna parte nella scheda "Servizio" o "Unità organizzativa":

1. sulla base di cosa vengono proposte queste date?
2. esiste una qualche sezione dove poter inserire date e orari di disponibilità?
3. come vengono gestite le prenotazioni negli stessi orari lato "operatore"?

![Immagine 2023-02-09 091624](https://user-images.githubusercontent.com/1243192/217755292-f5abb82e-7aaa-4efe-b4a1-1b2b9f151cd8.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.4.3

**Comment by mariantanase** [comment]
Da quanto ne so, ad oggi, gli orari vengono inseriti manualmente nel file **calendar.json** .

**Comment by guidobuldrighini** [comment]
Ok perfetto grazie mille @mariantanase , per quanto riguarda invece la gestione degli appuntamenti nello stesso orario?

**Comment by mariantanase** [comment]
> Ok perfetto grazie mille @mariantanase , per quanto riguarda invece la gestione degli appuntamenti nello stesso orario?

Per questo argomento ti rimando a questa discussione aperta #164

**Comment by johack0** [comment]
Salve a tutti, mi accodo alla discussione. 
Si potrebbero inserire nel servizio dei field custom per l'inserimento di orari e date di disponibililtà per la prenotazione

**Comment by zetareticoli** [comment]
Ciao @guidobuldrighini , il tema WordPress integra solamente una funzionalità indicativa del servizio. Non è infatti possibile gestire tutte le possibili integrazioni con sistemi di prenotazioni che differiscono da ente a ente.

**Comment by marco-nanni** [comment]
In realtà andrebbe sviluppato un plugin a parte (idem per il rating e le richieste di assistenza) legato al tema. Se viene attivato si dovrebbero poter inserire gli orari da backend e si attiverebbe la richiesta di appuntamento in modo completo. Se non viene attivato, semplicemente la richiesta di appuntamento non sarebbe operativa e a questo punto sarebbe sostituita da uno sviluppo custom ad hoc per il comune magari con una altro plugin. Perché, per come sono fati questi servizi, il problema è che non possono essere completamente modificati tramite chilld. Rischiando di dover effettuare un fork del inrtero progetto con tutto quello che ne consegue.
