### ISSUE TITLE
Utilizzo di reCaptcha di Google

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#179]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarebbe buona cosa, anche per una questione di sicurezza, introdurre l'utilizzo del reCaptcha V3 di Google nella pagine di rating, richiesta assistenza e richiesta appuntamento.

### Motivazione e contesto

Sicurezza

**Comment by astagi** [comment]
@marco-nanni lo consideriamo in una futura evolutiva. Per il momento ti chiedo, esiste un plugin che in automatico già inserisce il recaptcha Google V3 all'interno del tuo sito Wordpress per ovviare la tua richiesta?

**Comment by marco-nanni** [comment]
> @marco-nanni lo consideriamo in una futura evolutiva. Per il momento ti chiedo, esiste un plugin che in automatico già inserisce il recaptcha Google V3 all'interno del tuo sito Wordpress per ovviare la tua richiesta?

Si esiste, e potrei anche implementarlo io (l'ho già fatto e funziona) il probelma è: 
a) Non so se AGID acconsente all'utilizzo di un reCaptcha di Google visto che va registrato il dominio del comune in Google per poterlo utilizzare e attivare.
b) Eviterei di utilizzare, per quanto possibile plugin, di terze patri su siti pubblici per svariti motivi e non ultimo per una questione di sicurezza.

Ma sopratutto per il punto (a).
