### ISSUE TITLE
Vulnerabilità nella libreria Underscore@1.8.3

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#180]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Effettuando un testo con il tool di validazione, nel Lighthouse Report viene rileva una vulnerabilità.
Potete verificare ?
Grazie

### Includi link o screenshot

![vulnerabilita-libreria](https://user-images.githubusercontent.com/3976174/218412328-16540eac-5460-4de5-b171-4a03e6aecb82.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.4.3

**Comment by astagi** [comment]
Grazie @mariantanase hai provato per caso in locale ad aggiornarla ad una nuova versione?

**Comment by astagi** [comment]
@mariantanase questa PR è sotto test https://github.com/italia/design-comuni-wordpress-theme/pull/181

dimmi anche tu se ti funziona! Agisce su calendar

**Comment by mariantanase** [comment]
Confermo!
L'aggiornamento alla 1.13.6  risolve questa vulnerabilità.

**Comment by astagi** [comment]
Grazie del riscontro @mariantanase
