### ISSUE TITLE
Accesso al backend con utente di tipo editore

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#182]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Se accedo al backend di WP tramite un utente di tipo **admin** vedo tutte le voci relative alla gestione del comune.
Se accedo al backend con un utente di tipo **editore** le voci relative alla gestione dei dati del comune non sono più visibili.

### Includi link o screenshot

![wp_comuni_backend_admin](https://user-images.githubusercontent.com/118733111/218677829-6b344551-df3b-43db-9c41-fb8f7fedf1e1.PNG)
![wp_comuni_backend_editor](https://user-images.githubusercontent.com/118733111/218678327-9cfa83ac-51ae-4d4d-a83a-0c5cff3f154f.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.4.3

**Comment by mariantanase** [comment]
Ho notato anch'io quando cercavo di configurare e personalizzare dei ruoli, e non sono riuscito a trovare un compromesso.
La "Configurazione" la vede solo un utente con diritti admin, il che non mi pare normale.

**Comment by marco-nanni** [comment]
@mariantanase si potrebbe risolvere con un plugin tipo: https://wordpress.org/plugins/capability-manager-enhanced/
ma vorrei evitare di aggiungere plugin di terze parti per quanto possbile.

**Comment by astagi** [comment]
@marco-nanni @mariantanase ma la voce `Configurazione` non ha più senso se rimane di competenza di un admin?

@marco-nanni se il plugin risolve e a quanto mi pare è stabile e aggiornato, direi che non ci sono grandi problemi ad utilizzarlo per una vostra specifica esigenza.

**Comment by mariantanase** [comment]
> @marco-nanni @mariantanase ma la voce `Configurazione` non ha più senso se rimane di competenza di un admin?
> 
> @marco-nanni se il plugin risolve e a quanto mi pare è stabile e aggiornato, direi che non ci sono grandi problemi ad utilizzarlo per una vostra specifica esigenza.

Assolutamente non vorrei dare diritti di admin ad un utente solamente per inserire un avviso in homepage o per selezionare le 3 notizie o argomenti in evidenza. Avevo provato con il plugin user-role-editor ma non risolve il problema.

**Comment by marco-nanni** [comment]
@astagi il problema è che si vorrebbe evitare si usare plugin di terze parti su siti di eenti pubblici.

> @marco-nanni @mariantanase ma la voce `Configurazione` non ha più senso se rimane di competenza di un admin?
> 
> @marco-nanni se il plugin risolve e a quanto mi pare è stabile e aggiornato, direi che non ci sono grandi problemi ad utilizzarlo per una vostra specifica esigenza.

Si, però un utente di tipo editor potrebbe accedere solo alla parte di sua competenza. In questo modo invece qualunque soggetto del comune può accedere anche a parti non di sua competenza e tecniche non lo devono riguardare. E' una questione anche di sicurezza.

**Comment by astagi** [comment]
Chiaro quindi diciamo l'idea sarebbe quella di staccare queste parti (tipo avvisi in homepage) da admin e lasciarle in mano agli editor giusto?

**Comment by marco-nanni** [comment]
@astagi l'utente con permessi di admin può accedere a qualunque parte. 
E' l'utente con permessi diversi da admin che dovrebbe accedere di base solo alle informazioni relative al comune, tipo notizxie, eventi, luoghi, etc e non certo sulla configurazione di WordPress, plugin, temi e utenti. Poi questa cosa si può affinare ancora di più ad esempio permettendo l'accesso alle notizie di propria creazione. Mentre per le notizie pubblicate da altri, accedere solo in lettura.
