### ISSUE TITLE
Flussi autorizzativi

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#183]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarà prevista la gestione dei flussi autorizzativi all'interno del tema?

### Motivazione e contesto

Possibile richiesta da parte di un ente pubblico e per sapere cosa rispondere.

**Comment by astagi** [comment]
Buongiorno @marco-nanni , cosa si intende per flussi autorizzativi?

**Comment by marco-nanni** [comment]
@astagi per flussi autorizzativi, si intende la possibilità di subordinare la pubblicazione di un evento, di una notizia o di altro, ad una autorizzazione, o più di una, da parte di uno o più supervisori. Questa cosa, ad esempio, è richiesta nella trasparenza. Questo potrebbe esseere una richiesta special modo da parte di comuni di una certa dimensione.

**Comment by astagi** [comment]
@marco-nanni percaso è legata alla #182 ? Si tratta di creare ad esempio più ruoli editor e di fare in modo che questi editor possano gestire le pubblicazioni di eventi, notizie ecc?

**Comment by marco-nanni** [comment]
@astagi anche. 

In realtà quelle che hai descritto tu sarebbero i permessi (capabilities) legate ad un determinato ruolo.
Il flusso autorizzativo agisce al di sopra. Ad esempio: Tizio (con ruolo x) decide se la notizia inserita da Caio (con ruolo y) può essere pubblicata, banalmente. Oggi Caio inserisce una notizia e la pubblica senza che nessuno possa vedere e accertarsi dell'esattezza del contenuto di tale notizia se non dopo avral vista online. 

Spero di essermi spiegato. :)
