### ISSUE TITLE
Salvataggio in stato "Bozza" per i contenuti

### ISSUE THREAD

**Issue by FrancescaFrigerio** [italia/design-comuni-wordpress-theme#19]
Buongiorno,
vi contatto perché ho notato una problematica: quando viene creato un nuovo contenuto non è possibile salvarne la bozza finché non sono state inserite tutte le informazioni obbligatorie per lo specifico contenuto. Uscendo dal contenuto ne viene comunque creata la bozza, ma quando si entra per modificarla tutti i dati che erano stati inseriti vengono persi.

Grazie

**Comment by zetareticoli** [comment]
Ciao @FrancescaFrigerio,
il fatto che WP non permetta di salvare una bozza senza aver compilato i campi obbligatori è una sua funzionalità su cui non siamo intervenuti.

Non sono riuscito a riprodurre il fatto che uscendo dal contenuto la bozza venga comunque creata. Cosa intendi per uscire? Un click su qualsiasi link (menu, etc)?

**Comment by astagi** [comment]
Fixed in #49
