### ISSUE TITLE
Ordinamento dei post

### ISSUE THREAD

**Issue by mirkopeloso** [italia/design-comuni-wordpress-theme#192]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Entrando, ad esempio, nella sezione Novità, e cliccando poi su "Carica altri risultati", si ottiene sempre la lista dei post ordinata alfabeticamente.
Sarebbe molto più utile caricarla per data discendente, o almeno dare all'utente la possibilità di decidere con dei tasti/dropdown,  per quale campo ordinarli e se ASC/DESC.
Altrimenti così rimane inusabile e senza senso.

### Includi link o screenshot

![Screenshot from 2023-03-05 16-47-38](https://user-images.githubusercontent.com/51156052/222970867-b9c74949-6546-4e6b-8505-2343d5862806.png)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.3.1

**Comment by HshMatera** [comment]
Ciao, anche io ho trovato questo bug.
Sto provando ad impostare i parametri della query passandoli $order definita in args nel file tutte-novita.php
`$args = array(
        's'         => $query,
		'order'   => 'DESC',
        'post_type' => 'notizia'
    );`
poi in more-results.php
`$order = isset($query['order']) ? $query['order'] : null;
$order = json_encode( $order );
......
$query_params = '?post_count='.$the_query->post_count.'&load_posts='.$load_posts.'&search='.$query_search.'&post_types='.$post_types.'&load_card_type='.$load_card_type.'&query_params='.$query_params.'&additional_filter='.$additional_filter. '&order='.$order ;
`
ma non succede nulla, l'ordine risulta non corretto (alfabetico).

**Comment by HshMatera** [comment]
Ciao,
ho risolto questo problema modificando il file /inc/load_more.php.
Alla riga 41:

`$args = array(
        's' => $_POST['search'],
        'posts_per_page' => $_POST['post_count'] + $_POST['load_posts'],
        'post_type'      => $post_types,
        //'orderby'        => 'post_title',
        'order'          => 'DESC'
    );`

Adesso il caricamento è in ordine decrescente.

**Comment by HshMatera** [comment]
Forse avrai sbagliato nel codice perchè a me funziona.

Te lo copio in questo modo:

$args = array( 's' => $_POST['search'], 
'posts_per_page' => $_POST['post_count'] + $_POST['load_posts'], 
'post_type'      => $post_types, 
//'orderby'        => 'post_title', 
'order'          => 'DESC' );

Spero che funzioni anche a te

**Comment by mariantanase** [comment]
Ok, funziona ma ho notato che le notizie vengono ordinate in base alla data di pubblicazione della notizia, non in base al campo "Data della notizia". 
Prova a inserire una notizia con una data diversa e verifica se così.

**Comment by enrimk** [comment]
> [...] modificando il file /inc/load_more.php. Alla riga 41:
> `$args = array( [...] //'orderby' => 'post_title', 'order' => 'DESC' );`

> [...] provato anche con questo: `'orderby' => 'post_date'` ma non si risolve neanche così.

Queste modifiche non bastano. Il fatto è che così com'è load_more() non accetta altro che post_title per l'ordinamento.  Ma se si toglie il parametro 'orderby', usa sempre il default di WP_Query (che è post_date), e a parte le Novità non va poi bene per tutto il resto (gli altri contenuti che usano il caricamento ajax, che sono ordinati alfabeticamente o in altro modo). Anzi, non va bene neanche per le Novità, che in realtà non sono ordinate solo per post_date, ma per una combinazione complicata di data_pubblicazione e post_date.

Per tenere le modifiche al minimo, si potrebbe anche lasciare post_title lì dov'è come default, ma sostituire [alla riga 62](https://github.com/italia/design-comuni-wordpress-theme/blob/94f48868687a81f511c947f0f9cff7bfc0e287d5/inc/load_more.php#L62) l'operatore di accodamento "+" con array_merge(), che dà la precedenza al secondo operando.  Diventa:
`if ( isset($additional_filter) ) $args = array_merge($args, $additional_filter);`
E passare _sia_ orderby _sia_ order (che dev'essere DESC in caso di date) attraverso `$additional_filter`, in [tutte-novita-php](https://github.com/italia/design-comuni-wordpress-theme/blob/main/template-parts/novita/tutte-novita.php).
A questo punto i paramenti passati sovrascrivono gl ialtri. [C'è magari da verificare qualche aspetto di sicurezza, ma non mi pare che ce ne siano di gravi]

Però, non basterebbe ancora, per la questione che dicevo di data_pubblicazione, che non si riesce a combinare con post_date in un unico parametro di WP_Query.
