### ISSUE TITLE
Prenotazione appuntamento - errore REST API

### ISSUE THREAD

**Issue by abmcr** [italia/design-comuni-wordpress-theme#195]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Al primo step della pagina prenotazione appuntamento, una volta scelto l'ufficio viene generato un errofre dalla riga 181 del file booking.js (sto usando la versione in src quindi non minificata)

fetch(`${window.wpRestApi}wp/v2/sedi/ufficio/?${urlParam}`)ù

che genera un errore 404 come da schermata allegata.
Nel caso dell'esempio la URL che genera il 404 è

https://xxxxx.to.it/index.php?rest_route=/wp/v2/sedi/ufficio/?id=120

### Includi link o screenshot

![Screenshot 2023-03-09 alle 11 56 49](https://user-images.githubusercontent.com/286438/224004172-01e20acc-f7da-4258-b3c3-514955674f3b.png)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by danimog** [comment]
Ciao @abmcr, qualche giorno fa ho chiesto su slack (#design-modello-comuni) se c'era un elenco completo delle API di integrazione. Una cosa che difatti notavo è che la API di richiesta punta (come anche nel tuo esempio) su /sedi/ufficio/?id... e restituisce l'errore 404.. mentre gli uffici (o meglio le unità organizzative) sono su /amministrazione/unita_organizzativa/servizi-sociali/ (ad esempio).
Chiedo quindi anche qui se c'è un elenco documentato di API. grazie!

**Comment by danimog** [comment]
ciao @abmcr proprio qualche giorno fa chiedevo su slack (nel canale design-modello-comuni) se c'era un elenco documentato delle API. Perchè anch'io provando a richiedere elenco uffici mi restituisce l'errore 404..

**Comment by abmcr** [comment]
Grazie Daniele:mi sono unito al canale.. vediamo se ne usciamo in qualche modo

**Comment by abmcr** [comment]
In ogni caso, segnalo che le righe 12 e 13 sono errate
ORIGINALE

wp_localize_script('dci-booking', "url", get_template_directory_uri() . '/assets/json/calendar.json');
wp_localize_script('dci-booking', "urlConfirm", admin_url( 'admin-ajax.php' ));

CORRETTO (il terzo parametro deve essere un array)

wp_localize_script('dci-booking', "url", [get_template_directory_uri() . '/assets/json/calendar.json']);
wp_localize_script('dci-booking', "urlConfirm", [admin_url( 'admin-ajax.php' )]);

**Comment by abmcr** [comment]
Ho scoperto che il bug da me segnalato si verifica SOLO se non si imposta un permalink e quindi con la configurazione degli URL di default, cioè ?page=xxx

**Comment by EliaTolin** [comment]
@abmcr che servizi utilizzi per la gestione del calendario (calendar.json)?
