### ISSUE TITLE
Checkbox non visualizzato

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#197]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
Ho notato che i checkbox di bootstrap non vengono visualizzati sul tema dei comuni.
Ho installato il plugin Contact Form 7 (5.7.4) e aggiunto il checkbox per l'accettazione della privacy policy.
In frontend il checkbox non viene visualizzato.

### Includi link o screenshot

Link: https://www.tanase.it/demo-comuni/contattaci/

### Su quale sisitema operativo stai riscontrando il problema?

Windows, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by abmcr** [comment]
Hai verificato la classe CSS che Contact Form mette?

**Comment by mariantanase** [comment]
> Hai verificato la classe CSS che Contact Form mette?

Ho verificato ma non c'entra nulla. 
Anche inserendo i codici bootstrap per il checkbox all'interno di una semplice pagina del sito, il checkbox non viene visualizzato.

**Comment by abmcr** [comment]
Però in questa pagina

https://www.tanase.it/demo-comuni/servizi/assistenza/

la checkbox è corretta ed è una input mentre in quella 

https://www.tanase.it/demo-comuni/contattaci/

Contact form nasconde la input e mette uno span che avrebbe credo del CSS

**Comment by mariantanase** [comment]
Risolto

**Comment by abmcr** [comment]
Ciao: ma come hai  risolto? vorrei anche io inserire Contact Form per la gestone di un paio di form... grazie

**Comment by mariantanase** [comment]
Io ho fatto le modifiche per quanto riguarda solamente quel checkbox per la privacy. In pratica ho aggiunto una classe custom nel form acceptance del plugin, l'ho definita nel mio css e poi come ultimo ho commentato questa istruzione:
/*input{-webkit-appearance:none!important}*/
