### ISSUE TITLE
errore nella libreria CMB2

### ISSUE THREAD

**Issue by oxodi** [italia/design-comuni-wordpress-theme#198]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [x] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,

con il template sto riscontrando un problema nelle varie sezioni di configurazione Es: 
Configurazione -> HomePage ; In basso compare il seguente errore: 

"Fatal error: Uncaught Error: Call to a member function options() on null in /home/admin/web/comuni.turco.cloud/public_html/wp-content/themes/design-comuni-wordpress-theme-1.6.1/inc/lib/cmb-field-select2-master/cmb-field-select2.php:84" 

Sto utilizzando WP 6.0 con PHP 7.4 ma ho verificato anche con altre versioni ed il problema rimane.

Grazie 

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by oxodi** [comment]
Si segnala che l'errore non è presente nella versione 1.6.0

**Comment by marco-nanni** [comment]
Segnalo pure io il medesimo errore.

**Comment by abmcr** [comment]
Lo stesso problema all'interno di ogni CPT

**Comment by abmcr** [comment]
con la seguente modifica l’errore è risolto MA non sono in ghrado di capire se la modifica abbia ripercussioni altrove, anche se non dovrebbe

<img src=‘https://pnrr.mlabvda.it/wp-content/uploads/2023/03/Screenshot-2023-03-22-alle-10.39.12.png’>

Riporto qui le linee
`public function get_pw_multiselect_options( $field_type_object, $field_escaped_value = array() ) {
		if($field_type_object){
		    $options = (array) $field_type_object->field->options();
		    // If we have selected items, we need to preserve their order
		    if ( ! empty( $field_escaped_value ) ) {
			    $options = $this->sort_array_by_array( $options, $field_escaped_value );
		    }
		} else {
		    $options = [];
		} `

**Comment by fabricius4** [comment]
in fase di correzione mi da errore qui e difatti il problema rimane. Forse sbaglio qualcosa nel codice
![Immagine2](https://user-images.githubusercontent.com/128590137/226871597-60ee6af9-d75d-4d4e-ae7f-933bff8e1a8c.jpg)

**Comment by danimog** [comment]
ciao, così viene ripristinato. 
Resta escluso, nel mio caso, la sezione Argomenti dove segnala sempre errore.

grazie @abmcr per il codice

**Comment by abmcr** [comment]
> [danimog](/danimog)

Argomenti .. dentro quale menu? io ho provato dentro Servizi->Argomenti ma non ho alcun erroe...

**Comment by danimog** [comment]
Configurazione -> Argomenti 
![Cattura](https://user-images.githubusercontent.com/16287539/226877647-24816e8f-8d3b-4b8a-a22a-1c972b4cc6e8.PNG)

**Comment by abmcr** [comment]
![image](https://user-images.githubusercontent.com/286438/226877892-4c902203-9892-479c-aecd-4dd42d2fc74e.png)
ma..... io vedo cosi

Attiva il debug nel wp-config.... cosi vediamo l'errore....

Non capisco perché io veda diverso

Se vuoi ti mando in privato un accesso al sito dove sto facendo le prove

**Comment by guidobuldrighini** [comment]
Applicando la modifica di @abmcr 

Sezione Home Page:

![Immagine 2023-03-22 114125](https://user-images.githubusercontent.com/1243192/226879174-c6ba89b5-b670-4d23-b47f-b243c80ff4a0.png)

Sezione Servizi:

![Immagine 2023-03-22 114155](https://user-images.githubusercontent.com/1243192/226879778-48be6d44-302e-462f-95de-3897a192aa36.png)

Sezione Documenti e dati:

![Immagine 2023-03-22 114216](https://user-images.githubusercontent.com/1243192/226880015-7d75e3f1-fe1f-476e-81de-69c92db6e58e.png)

Sezione Argomenti:

![Immagine 2023-03-22 114234](https://user-images.githubusercontent.com/1243192/226880108-c7f43bb3-12b8-49d4-b0fd-efad124a0fa0.png)

**Comment by abmcr** [comment]
@danimog se mi contatti in privato ti mando un accesso.. ho provato a scriverti usando la email trovata nel tuo sito ma torna indietro con un errore...

**Comment by danimog** [comment]
@abmcr aggiornato contatti..
nonostante abbia attivato il wp-debug non riesco a far uscire l'errore..
ho installazione su server linux ma wordpress e mysql girano su docker...
grazie

**Comment by danimog** [comment]
ciao, ho richiesto come mai nel fix della 1.6.1 sono stati invertiti i parametri nella funzione che causa gli errori: 
public function get_pw_multiselect_options(....
modificando l'ordine dei parametri della funzione e rimettendoli come nella versione 1.6.0 gli argomenti vengono caricati correttamente nella multiselect.
La funzione per me funzionante è quindi:
public function get_pw_multiselect_options( $field_escaped_value = array(), $field_type_object ) {

p.s. non serve poi modificare il resto come nel codice di @abmcr ma solo questi due parametri

**Comment by fabricius4** [comment]
> ciao, ho richiesto come mai nel fix della 1.6.1 sono stati invertiti i parametri nella funzione che causa gli errori: public function get_pw_multiselect_options(.... modificando l'ordine dei parametri della funzione e rimettendoli come nella versione 1.6.0 gli argomenti vengono caricati correttamente nella multiselect. La funzione per me funzionante è quindi: public function get_pw_multiselect_options( $field_escaped_value = array(), $field_type_object ) {
> 
> p.s. non serve poi modificare il resto come nel codice di @abmcr ma solo questi due parametri

confermo quanto sopra

**Comment by fabricius4** [comment]
ho notato che da errore nel caricamento della sezione mappa in fase di creazione di un "luogo" 
![Immagine](https://user-images.githubusercontent.com/128590137/227136412-7ca6bfce-0b9d-439a-bb76-87c596ad0e01.jpg)

**Comment by abmcr** [comment]
Esatto @fabricius4 

Segnalato qui 
https://github.com/italia/design-comuni-wordpress-theme/issues/205

**Comment by danimog** [comment]
ciao, è un po' la stessa cosa di quanto riportato sopra..
nel fix 1.6.1 sono stati invertiti i parametri alla riga 140 del file cmb-field-leaflet-map.php
1.6.1 ---> protected function render_input( CMB2_Field $field, $field_escaped_value, CMB2_Types $field_type_object, $field_name = '' ) {
1.6.0. ---> protected function render_input($field_name = '', CMB2_Field $field, $field_escaped_value, CMB2_Types $field_type_object ) {

Questa modifica (quindi riportando il codice come nella 1.6.0) nel mio caso funziona.

Resta da capire perchè sia stato il fix invertendo i parametri. Chiederei a @mariantanase. grazie!

**Comment by danimog** [comment]
Grazie!
