### ISSUE TITLE
Tab "Home Page" nella sezione "Configurazione": errore layout per la scelta dei contenuti da mostrare

### ISSUE THREAD

**Issue by guidobuldrighini** [italia/design-comuni-wordpress-theme#199]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella sezione configurazione del tema per i comuni, alla sezione Homepage si è disabilitata la possibilità di aggiungere/rimuovere news e contenuti in tutte le sezioni, il primo screenshot mostra la sezione col template alla versione 1.6.1, gli altri due sono fatti con la versione 1.6.0 e la 1.5.0

### Includi link o screenshot

![homepage_1 6 1](https://user-images.githubusercontent.com/1243192/226550610-84cd02ae-cfb1-49a6-8278-3def6a4dd15d.png)
![homepage_1 6 0](https://user-images.githubusercontent.com/1243192/226550644-76803358-cd07-4711-83f7-70f10b8af7ad.png)
![homepage_1 5 0](https://user-images.githubusercontent.com/1243192/226550665-642673f9-f69c-43cf-b54a-5296f364613d.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Linux

### Su quale browser stai riscontrando il problema?

Chrome, Firefox, Microsoft Edge

### Che versione del tema stai utilizzando?

1.6.1

**Comment by abmcr** [comment]
Il problema è analogo a questo già segnalato e , almeno per questa sezione, risolto da un codice da me aggiunto

https://github.com/italia/design-comuni-wordpress-theme/issues/198#issuecomment-1479221797

Nel caso mi puoi confermare se a te la mia modifica funziona? grazie

Dopo la modifica la mia videata è questa
![image](https://user-images.githubusercontent.com/286438/226870906-35747faa-0f7f-4c62-8315-1d96ce25a27f.png)

**Comment by guidobuldrighini** [comment]
Ciao @abmcr , ho applicato la correzione ma il risultato non cambia purtroppo, allego screenshot:
![Immagine 2023-03-22 112545](https://user-images.githubusercontent.com/1243192/226875277-f62adecd-dac1-45fb-bd2d-d58cb3f67bc8.png)
![Immagine 2023-03-22 112610](https://user-images.githubusercontent.com/1243192/226875311-f552c6eb-ed7b-4227-aac4-cb6ceb3932bc.png)

**Comment by guidobuldrighini** [comment]
sei sempre alla 1.6.1?
alcune sezioni vanno e altre no
