### ISSUE TITLE
class 'CMB2_Hookup' not found

### ISSUE THREAD

**Issue by mspinternational** [italia/design-comuni-wordpress-theme#2]
Salve,
le pagine sono piene di Warning di questo tipo:

Warning: include_once(): Failed opening '/home/customer/www/unionecomuniarcipelagodelsulcis.it/public_html/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/includes/CMB2_Hookup.php' for inclusion (include_path='.:/usr/local/php74/pear') in /home/customer/www/unionecomuniarcipelagodelsulcis.it/public_html/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/includes/helper-functions.php on line 44

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'CMB2_Hookup' not found in /home/customer/www/unionecomuniarcipelagodelsulcis.it/public_html/wp-includes/class-wp-hook.php on line 307

Uso WP 6.0.1 appena installato.

**Comment by totolabs** [comment]
> Salve, le pagine sono piene di Warning di questo tipo:
> 
> Warning: include_once(): Failed opening '/home/customer/www/unionecomuniarcipelagodelsulcis.it/public_html/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/includes/CMB2_Hookup.php' for inclusion (include_path='.:/usr/local/php74/pear') in /home/customer/www/unionecomuniarcipelagodelsulcis.it/public_html/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/includes/helper-functions.php on line 44
> 
> Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'CMB2_Hookup' not found in /home/customer/www/unionecomuniarcipelagodelsulcis.it/public_html/wp-includes/class-wp-hook.php on line 307
> 
> Uso WP 6.0.1 appena installato.


E' necessario fare una piccola correzione al nome di un file e si risolvono tutti i warning.
Il file in questione è "CMB2_hookup.php" e si trova nella cartella "/wp-content/themes/design-comuni-wordpress-theme-1.0.1/inc/lib/CMB2/includes".
Deve essere rinominato da "CMB2_hookup.php" a "CMB2_Hookup.php".
I warning indacati sono causati da quell'H minuscola.

**Comment by zetareticoli** [comment]
@mspinternational hai risolto con il metodo illustrato da @totolabs ?

**Comment by zetareticoli** [comment]
Il problema è stato corretto in 4b8ce244ed7afc31881c9fe4faca28419024493c
