### ISSUE TITLE
Funzionalità "Richiesta assistenza" - invio email

### ISSUE THREAD

**Issue by HshMatera** [italia/design-comuni-wordpress-theme#200]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
mi potreste indicare il modo di impostare i parametri di invio mail al termine della procedura di Richiesta assistenza?
`<button
        type="submit"
        class="btn btn-primary btn-sm steppers-btn-confirm send"
        data-bs-validate="validate"
        <span class="text-button-sm">Invia</span>
        <svg class="icon icon-white icon-sm">
        <use href="#it-chevron-right"></use>
        </svg>
    </button>`

Ho trovato la funzione nel file assistenza.js ma non riesco a capire perchè non invia la mail o meglio dove e come definire i parametri.

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by HshMatera** [comment]
> qui c'è una vecchia issue che non ho chiaro se abbia risolto il problema
> 
> #120
Non hanno risolto il problema purtroppo.

**Comment by abmcr** [comment]
concordo: ma quindi tu non usi il form integrato nel tema ma come fatto anche da altri, un plugin come contact form?
E per la sezione di richiesta appuntamento però siamo daccapo... anche li l'invio della email è da programmare perché non funziona ....

**Comment by HshMatera** [comment]
Io utilizzo si un plugin come contact form, si chiama Formidable Forms.
Mentre per l'appuntamento sto testando Amelia, lo trovo molto completo.
L'app di verifica non entra nel dettaglio dell'appuntamento quindi il test passa tranquillamente.

**Comment by HshMatera** [comment]
La gestione della prenotazione, a mio avviso, conviene gestirla con un plugin per avere altre funzionalità e maggiore autonomia. 
Nel caso il tema prima o poi sviluppa il tutto lo prendo in considerazione.

**Comment by marco-nanni** [comment]
Dovete armarvi di pazienza e sviluppare tramite l'utilizzo del child e plugin ad hoc.
Difficilmente troverete dei plugin di terze parti che si aggancino ai dati di questo tema tra l'altro rispettando le direttive AGID.
