### ISSUE TITLE
Problema creazione Notizie, Configurazione Sito 

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#202]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Non è possibile creare notizie/avvisi/comunicati stampata (è sparita la tab "descrizione" e tutto il resto).
All'interno della sezione "Configurazione" non è più possibile impostare la struttura dell'homepage attaraverso la selezione delle schede in evidenza.

### Includi link o screenshot

![problema creazione notizie](https://user-images.githubusercontent.com/128592652/226874905-6f97e8e7-0045-4a71-8bb5-ad99efc488fa.JPG)
![problema configurazione sito](https://user-images.githubusercontent.com/128592652/226874912-b431bec2-f70d-41d4-bdca-47adce0a7d94.JPG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.6.1

**Comment by danimog** [comment]
ciao, controlla la issue #198
