### ISSUE TITLE
Problema pubblicazione "Servizi"

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#203]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo aver compilato tutti i campi necessari a pubblicare un servizio, la pubblicazione non avviene.
Non mi viene mostrato nessun tipo di errore o campo mancante, semplicemente cliccando su "Pubblica" non avviene nulla.

Versione Wordpress 6.1.1
Versione Tema 1.6.1

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by abmcr** [comment]
![image](https://user-images.githubusercontent.com/286438/226888201-4258612b-6ccc-41a6-92c7-637a833c00f7.png)


anche a me stesso problema

**Comment by zetareticoli** [comment]
Ciao @luciox96, non riscontro questa problematica nella _sandbox_ che usiamo per lo sviluppo. 

Hai errori in console?

**Comment by abmcr** [comment]
Che fosse legato a https://github.com/italia/design-comuni-wordpress-theme/pull/209? e quindi risolto

**Comment by luciox96** [comment]
Risolto, grazie

**Comment by fabricius4** [comment]
> Che fosse legato a #209? e quindi risolto

![network](https://github.com/user-attachments/assets/52820b4a-918a-480b-8185-bcd036c93fc2)

ancora oggi stesso problema. Cosa potrebbe essere?

**Comment by enrimk** [comment]
@fabricius4 
_Questa_ console ("Network") non ci dice molto, giusto il fatto che alcune risorse della pagina vengono effettivamente scaricate.

Più utile sarebbe vedere la console vera e propria (il tab "Console"), che raccoglie gli errori del browser. Tra cui, magari, qualche errore javascript che _potrebbe_ pure interrompere l'invio di una nuova richiesta al server.

**Comment by fabricius4** [comment]
> @fabricius4 _Questa_ console ("Network") non ci dice molto, giusto il fatto che alcune risorse della pagina vengono effettivamente scaricate.
> 
> Più utile sarebbe vedere la console vera e propria (il tab "Console"), che raccoglie gli errori del browser. Tra cui, magari, qualche errore javascript che _potrebbe_ pure interrompere l'invio di una nuova richiesta al server.

![console](https://github.com/user-attachments/assets/072ff60c-9be4-49e6-91aa-2d48be0007a4)

**Comment by fabricius4** [comment]
> @fabricius4
> 
> Non sono sicuro che anche questo errore sia pertinente al problema. Prima che ci si imbarchi in un safari a caccia di bug, hai fatto qualche test in una situazione più controllata? Ad es. con un browser "vergine" senza troppe estensioni, e magari anche in una copia del sito in locale e con pochi plugin.

Risolto. Si trattava semplicemente di un campo obbligatorio che però wordpress andava a comprimere e non si riusciva a visualizzare.
