### ISSUE TITLE
Problema creazione "Persone Pubbliche"

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#204]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti, 

Sono già andato a vedere in tutte le domande passate ma nessuno ha ancora riscontrato questo problema.
Dopo aver creato un "Punto di contatto" devo procedere con la creazione di una "Persona Pubblica"; il problema è che non mi fa selezionare nessun "Punto di contatto" creato precedentemente.

Come posso risolvere questo problema?

### Includi link o screenshot

`
![Creazione persone pubbliche](https://user-images.githubusercontent.com/128592652/226882775-73ad9b58-e82d-4925-b7ad-d127f3bb6b2c.JPG)
`

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by Mesterfem** [comment]
Stesso problema

**Comment by danimog** [comment]
Potrebbe essere legato a quanto riportato nella issue #198 (nell'inversione dei parametri della funzione messi nel fix della versione 1.6.1). 
Nel mio caso dopo questa modifica si vedono i punti di contatto

**Comment by fabricius4** [comment]
confermo. con la ver 1.6.1 e la sola modifica: public function get_pw_multiselect_options( $field_escaped_value = array(), $field_type_object )
funziona anche la selezione del "punto di contatto"

**Comment by luciox96** [comment]
Ciao, inserendo la modifica public function get_pw_multiselect_options( $field_escaped_value = array(), $field_type_object ) funziona!
L'unico problema è che le informazioni inserite al momento della creazione di una persona pubblica non vengono visualizzate lato front-end.
In particolare:
- immagine persona
- deleghe
- biografia
- galleria immagini
- cv
- situazione patrimoniale
- ecc..
(praticamente tutto tranne nome, cognome, descrizione breve e competenze)

**Comment by abmcr** [comment]
@luciox96 

Guarda qui https://github.com/italia/design-comuni-wordpress-theme/issues/71

**Comment by luciox96** [comment]
Grazie mille!

**Comment by luciox96** [comment]
Grazie mille ora funziona, alcuni campi non sono più presenti ma vedrò come ripristinarli
