### ISSUE TITLE
Bug durante creazione Luogo

### ISSUE THREAD

**Issue by abmcr** [italia/design-comuni-wordpress-theme#205]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Cercando di creare un nuovo Luogo si incorre in un errore php come da allegata schermata

### Includi link o screenshot

![image](https://user-images.githubusercontent.com/286438/226888767-a23dbeb6-bff5-4bd3-ae1d-9e3819044519.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by mariantanase** [comment]
Dovrebbe risolversi con #209
