### ISSUE TITLE
Servizio e fasi del servizio

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#21]
Salvando un servizio il box tempi e scadenze richiede **obbligatoriamente** una o più fasi da inserire. Queste fasi inoltre richiedono come parametro obbligatorio una **data reale**. Ma non tutti i servizi richiedono per forza una data reale. Questa obbligatorietà rende difficile inserire qualsiasi servizio. Verrà presa in considerazione l'eventualità di togliere questo obbligo o dovrà essere risolta nella versione child del tema?

**Comment by mariantanase** [comment]
Ciao @garagiu ,
Ho notato anch'io questo comportamento, ma mi risulta che è ancora in valutazione. 
Sono d'accordo con te che va levata questa obligatorietà, altrimenti nessun servizio si può inserire.

**Comment by minnogit** [comment]
Stesso problema se volessi inserire un servizio di pagamento multe.
In pratica non si riesce a fare una pagina come questa:
https://italia.github.io/design-comuni-pagine-statiche/servizi/pagamenti-dovuti-multa-trovare-informazioni-servizio.html

**Comment by nomissor** [comment]
Sono anch'io del parere che vada tolta l'obbligatorietà sia delle fasi nella scheda servizio che della Data nella singola fase.

Per risolvere il primo attualmente nel mio tema child ho aggiunto:
```
$box = CMB2_Boxes::get( '_dci_servizio_box_tempi' );
$box->update_field_property('_dci_servizio_fasi','attributes', ['required' => false,'placeholder' => "Seleziona le fasi del Servizio"]);
```
