### ISSUE TITLE
Importazione contenuti

### ISSUE THREAD

**Issue by fnori77** [italia/design-comuni-wordpress-theme#211]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve, ho un sito che utilizza il template Italia Wp. Ho installato il nuovo tema design-comuni-wordpress ma i contenuti vengono classificati come articoli. Avrei bisogno che fossero inseriti come notizie.
Grazie mille.

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.4.4

**Comment by fnori77** [comment]
Grazie mille per il consiglio. In alternativa ho trovato il plugin Post Type Switcher. Anche qui bisogna comunque andare ad integrare le nuove info.

**Comment by astagi** [comment]
Visto è stata risolta questa necessità possiamo chiudere la segnalazione. Grazie
