### ISSUE TITLE
Segnalazione disservizio - Incongruenza con i campi back-end del post type "Servizi" e altre informazioni

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#212]
Buongiorno,
vorrei maggiori informazioni su come implementare la segnalazione di disservizio nel template Wordpress. Nello specifico:

Scheda del servizio di segnalazione:
Aggiungendo un nuovo servizio ci sono campi obbligatori nel back-end che non sono presenti sul template statico:
    - Selezione obbligatoria dell'argomento e conseguente output della breadcrumb
    - Il campo "Tempi e scadenze" è obbligatorio ma nel template statico non è presente

Step di segnalazione:
La breadcrumb è ancora:
Home/Servizi/Segnalazione disservizio
- Questo significa che la pagina non è cambiata e va implementato tutto nella stessa pagina?
- La segnalazione non prevede l'obbligatorietà del login, come faccio a prendere i dati dell'utente?
- Nei dati di segnalazione la ricerca del luogo deve essere implementata a parte o ci sono dei metodi già presenti nel template?

Area personale:
- La segnalazione del disservizio è sotto l'elenco delle pratiche, deve essere salvata come una pratica?
- Sotto la voce Attività, aprendo il collapse della segnalazione del disservizio nel template statico (https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-area-personale.html#) c'è un link "Scheda servizio". Cliccando cosa si dovrebbe aprire?
- Cliccando su "Perfeziona la richiesta" si apre nuovamente tutto il flusso?

Elenco segnalazioni:
- Le categorie a lato provengono dai vocabolari controllati? In caso affermativo sono tutte? In caso negativo sono a discrezione della PA?
- Esiste una documentazione tecnica per mostrare i segnaposto sulla mappa?

**Comment by astagi** [comment]
Buongiorno @stefanoianna non so come mai ma questa segnalazione non rispetta il template. Sono costretto a chiudere. Inoltre mi sembra un'unica segnalazione di diversi problemi, sarebbe meglio anche per il team avere i problemi separati con la propria issue.
