### ISSUE TITLE
Eliminazione stili in comuni.css nell'ultimo aggiornamento

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#214]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve,
nello file comuni.css, con l'ultimo aggiornamento, sono stati eliminati degli stili utili per la visualizzazione le card.

### Includi link o screenshot

![Screenshot 2023-03-29 at 11-43-50 Vivere il Comune – Comune AGID](https://user-images.githubusercontent.com/67457275/228495484-69a858f2-1be8-487a-8db7-fc7ac56159b9.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, Linux

### Su quale browser stai riscontrando il problema?

Chrome, Firefox

### Che versione del tema stai utilizzando?

1.6.1

**Comment by zetareticoli** [comment]
ciao @stefanoianna,
il[ template statico](https://italia.github.io/design-comuni-pagine-statiche/sito/eventi.html) delle card è visivamente corretto.

Potresti fare un _diff_ del codice per confrontarlo con la tua implementazione e mi fai sapere? 

Magari c'è qualche differenza nelle classi utilizzate.

**Comment by danimog** [comment]
@mariantanase come sopra avevo riportato ho visto che la differenza è relativa all'attributo class nei files cards-list.php (dentro template-parts), relativo al caricamento dell'immagine della card:  

<div class="col-4 order-2 order-md-1">

Con col-4 è evidente che l'immagine si prende un terzo della larghezza.
Togliendo difatti col-4 dal class l'immagine "ritorna" come nella versione 1.6.0.
Il problema è che facendo un diff tra le due versioni (1.6.2 nel mio caso e 1.6.0) non trovo dove sia stato modificata questa parte...

**Comment by stefanoianna** [comment]
L'immagine a me si vede. il card body invece non ha più il padding giusto, infatti nel css manca questa media query:
  @media (min-width: 576px)
.cmp-list-card-img .card.card-img .card-body, .cmp-list-card-img .cmp-list-card-img-hr .card.card-img .card-img-none, .cmp-list-card-img-hr .cmp-list-card-img .card.card-img .card-img-none {
  padding: 1.78rem 1.33rem;
}

**Comment by mariantanase** [comment]
> @mariantanase come sopra avevo riportato ho visto che la differenza è relativa all'attributo class nei files cards-list.php (dentro template-parts), relativo al caricamento dell'immagine della card:
> 
> Con col-4 è evidente che l'immagine si prende un terzo della larghezza. Togliendo difatti col-4 dal class l'immagine "ritorna" come nella versione 1.6.0. Il problema è che facendo un diff tra le due versioni (1.6.2 nel mio caso e 1.6.0) non trovo dove sia stato modificata questa parte...

Ciao @danimog ,
Era semplice se si risolveva solo con quel col-4, ma non è così.
Se confronti il file "comuni.css" delle due versioni (1.6.0 e 1.6.2), noti tantissime differenze.
Io l'ho sostituito completamente con quello vecchio per risolvere, per ora.

**Comment by mariantanase** [comment]
OT: Per poter confrontare i file ho dovuto trasformare il file comuni.css minificato in un file non-minificato.
Sarebbe molto utile se può essere fornito insieme al tema anche il file non-minificato comuni.css.

**Comment by danimog** [comment]
ciao @mariantanase si, in effetti rimettendo comuni.css della versione 1.6.0 è tutto funzionante a dovere.. per ora faccio questa modifica anch'io..
