### ISSUE TITLE
Campi dei CPT popolati ma non visibili

### ISSUE THREAD

**Issue by Mesterfem** [italia/design-comuni-wordpress-theme#215]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
ho riscontrato questo problema: nell'inserire i contenuti nei vari Custom Post Type, ho notato che questi non si riflettono sul frontend. Per esempio se vado a popolare il CPT "Unità Organizzative" nei suoi vari campi (mandatori e non), questi non si vedono una volta pubblicati. Ho notato che manca il file nel tema e di conseguenza questo si aggancia a quello dei post di default.
Questo è tutto ciò che viene visualizzato:

![Cattura](https://user-images.githubusercontent.com/128602074/228515415-3f0e4338-9472-4cf0-beeb-b007eafed71a.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by abmcr** [comment]
Credo dipenda dal fatto che, lato fronend, non tutti i CPT hanno il loro template che va creato come nel caso dei servizi. vedi https://github.com/italia/design-comuni-wordpress-theme/pull/185

**Comment by astagi** [comment]
Esatto @abmcr farà parte sicuramente delle prossime versioni per ora chiudo come duplicato.
