### ISSUE TITLE
Problema sub menu

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#216]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti,

Sto provando ad aggiungere delle voci come sottomenu per le pagine principali (voci principali nel main menu) ma non viene letta la classe.
Qualcuno ha per caso riscontrato lo stesso problema?

### Includi link o screenshot

![Cattura](https://user-images.githubusercontent.com/128592652/228766945-44af1f7c-f0eb-4013-9ebf-25002e1bb412.JPG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @luciox96, il menu di primo livello non supporta un sotto-menu in modo nativo. Se stai cercando di implementarlo autonomamente, dovresti provare ad utilizzare il componente [megamenu](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/megamenu/) di Bootstrap Italia.
