### ISSUE TITLE
Test conformità AGID tema Comune - Problema riduzione codice javascript e contenuti CSS

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#217]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho eseguito il test di conformità AGID per quanto riguarda il tema del Comune e mi riporta le seguenti segnalazioni:
I file javascript e CSS sono quelli formiti con il tema.
Potreste darmi dei ragguagli, tenendo presente che non posso toccare questi file.

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_1](https://user-images.githubusercontent.com/118733111/229463935-47f7ed9a-fcc8-4df5-abd9-a97647f7b9dd.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by danimog** [comment]
interessa anche a me la issue..

**Comment by zetareticoli** [comment]
Questa non è una issue, in quanto l'implementazione e ottimizzazione delle risorse non è un criterio di conformità
