### ISSUE TITLE
C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO - Tutte le schede informative dei servizi per il cittadino devono mostrare le voci segnalate come obbligatorie all'interno dell'architettura dell'informazione, nell'ordine segnalato dal modello.Fornire un riepilogo generale del problema

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#219]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO - Tutte le schede informative dei servizi per il cittadino devono mostrare le voci segnalate come obbligatorie all'interno dell'architettura dell'informazione, nell'ordine segnalato dal modello.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?,

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_4](https://user-images.githubusercontent.com/118733111/229467015-11a6b9a0-f509-496d-a40f-e0242a5f9919.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by marco-nanni** [comment]
@zetareticoli 
I servizi creati sono presi dal custom post del tema "servizi".
Quindi fanno parte del tema.

**Comment by marco-nanni** [comment]
Abbiamo un nuovo problema sempre inerente alle schede di servizio. Oltre ai data-element amncanti che ho provveduto a sistemare, con al versione 2.7 della app di valutazione è emerso che il comune DEVE avere almeno 10 schede di servizio- Si da il caso che il comune in questione ne abbia solo 3. Ma dove è scritto che un comune debba per forza avere alemno 10 schede di servizio?
![app_valutazione_schede_servizio](https://github.com/italia/design-comuni-wordpress-theme/assets/118733111/0bffed58-706e-4d97-b4f2-297d02b3b666)

**Comment by LucaDuttoTD** [comment]
> Abbiamo un nuovo problema sempre inerente alle schede di servizio. Oltre ai data-element amncanti che ho provveduto a sistemare, con al versione 2.7 della app di valutazione è emerso che il comune DEVE avere almeno 10 schede di servizio- Si da il caso che il comune in questione ne abbia solo 3. Ma dove è scritto che un comune debba per forza avere alemno 10 schede di servizio? ![app_valutazione_schede_servizio](https://user-images.githubusercontent.com/118733111/270931605-0bffed58-706e-4d97-b4f2-297d02b3b666.PNG)

https://padigitale2026.gov.it/ , in "aggiornamento agosto 2023" linka questi doc:
https://assets.innovazione.gov.it/1693494978-230831_linee-guida-ls-aggiornamento-allegati-tecnici-n-2-e-n-6.zip

**Comment by marco-nanni** [comment]
A parte leggermi un pippone del genere... che vabbè. 
Ma la domanda è semplice: se un comune non ha 10 servizi non passa il test?

**Comment by marco-nanni** [comment]
E nel documento di valutazione non ho trovato menzione di questo limite.

**Comment by LucaDuttoTD** [comment]
> E nel documento di valutazione non ho trovato menzione di questo limite.

![Screenshot 2023-09-27 115508](https://github.com/italia/design-comuni-wordpress-theme/assets/121243866/0d181474-13c2-4a60-8b1f-ec78d0e416ff)

Pagina 15 del documento sulla 1.4.1

**Comment by marco-nanni** [comment]
Perfetto, rimane sempre il problema però.

**Comment by zetareticoli** [comment]
Ciao @marco-nanni, ti chiederei la cortesia di usare il canale Slack dedicato al modello per questioni di questo tipo.

Le issues di Github devono essere aperte per informazioni tecniche sul tema WordPress.

Grazie

**Comment by marco-nanni** [comment]
Ok, mi potresti fornire il link, grazie.
