### ISSUE TITLE
C.SI.2.2 - RICHIESTA DI ASSISTENZA / CONTATTI - All'interno del sito comunale, nel contenuto della scheda servizio, devono essere comunicati i contatti dell'ufficio preposto all'erogazione del servizio

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#221]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

C.SI.2.2 - RICHIESTA DI ASSISTENZA / CONTATTI - All'interno del sito comunale, nel contenuto della scheda servizio, devono essere comunicati i contatti dell'ufficio preposto all'erogazione del servizio.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
I Contatti nelle pagine risultano presenti
Potreste verificare ed provvedere alla sua risoluzione?,

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_5](https://user-images.githubusercontent.com/118733111/229467758-8f2de017-1566-4fcd-87d7-f43ee8a90682.PNG)

![seglazione_conformita_AGID_5_1](https://user-images.githubusercontent.com/118733111/229468188-cd227803-2231-4867-8b89-2015bb79ca89.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by mariantanase** [comment]
Questa isssue la risolvi aggiungendo l'attributo `data-element="service-area"` nelle righe 33 e 97 nel file : /template-parts/unita-organizzativa/card-full.php

**Comment by marco-nanni** [comment]
Ok, perfetto.

Grazie.
