### ISSUE TITLE
C.SI.2.3 - RICHIESTA DI ASSISTENZA / DOMANDE FREQUENTI - Il sito comunale deve contenere una sezione per le domande più frequenti (FAQ)

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#222]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

C.SI.2.3 - RICHIESTA DI ASSISTENZA / DOMANDE FREQUENTI - Il sito comunale deve contenere una sezione per le domande più frequenti (FAQ).

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Si da il caso però che la pagina domande frequenti sia presente.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_6](https://user-images.githubusercontent.com/118733111/229468736-20b5df6e-1045-40d8-a4d8-076b6fca1e4c.PNG)

![seglazione_conformita_AGID_6_1](https://user-images.githubusercontent.com/118733111/229469089-9b9f7671-2c56-4cd2-b662-58358286ceae.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by Tizzz-555** [comment]
Buongiorno, sto avendo esattamente lo stesso problema, vedo che la issue è stata chiusa ma non capisco perchè, qualcuno sa gentilmente aiutarmi?

**Comment by marco-nanni** [comment]
@Tizzz-555 devi verificare esattamente quanto scritto nella nota della segnalazione e vedere il dettaglio nella documentazione dell'app di valutazione. Spesso la causa è il data-element mancante ad esempio se si cambia la dicitura del menù del footer nel quale si dovrebbe trovare il link alle FAQ. Utilizzare sempre l'ultima versione dell'app. Se anche dopo queste verifiche la segnalazione permane apri una altra ISSUE. Potrebbe essere anche un bug dell'app di valutazione.

**Comment by Tizzz-555** [comment]
@marco-nanni ho già verificato, spero correttamente. Il dettaglio è qui riportato
![Screenshot 2023-10-05 at 13 37 00](https://github.com/italia/design-comuni-wordpress-theme/assets/103275021/7983bf86-2025-41ff-944b-4644de3cf3bf)

il data-element coincide con la documentazione, questo il mio codice ispezionando la pagina:
`<a href="https://monteloopo.local/home/domande-frequenti/" data-element="faq">Leggi le FAQ</a>`

### Versione app:
2.7.2
### Versione tema:
1.7.3
