### ISSUE TITLE
R.SI.1.1 - METATAG - Nel sito comunale, le voci della scheda servizio devono presentare i metatag descritti dal modello, in base agli standard internazionali

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#226]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

R.SI.1.1 - METATAG - Nel sito comunale, le voci della scheda servizio devono presentare i metatag descritti dal modello, in base agli standard internazionali.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_10](https://user-images.githubusercontent.com/118733111/229475379-e77684f6-aa6a-4430-a067-328e47bc6da6.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by HshMatera** [comment]
In realtà questo BUG è già stato segnalato ma mai risolto.
io ho messo una pezza cambiando qualcosa nel single-servizio.php
Ho aggiunto dei controlli se quei campi non sono popolati in fase di inserimento del servizio. 
Tipo in questo modo:

```
<? if ($ipa){?>
	"name": "<?= $ipa; ?>"
<?} else {?>
	"name": "nessuno"
<? } ?>
```
così con gli altri campi.
Ma dovrebbero sistemarlo.

**Comment by mariantanase** [comment]
@HshMatera ,
Quel codice all'interno del script a me da errore. 
Puoi mostrarmi per favore tutto il script ? Grazie

**Comment by HshMatera** [comment]
@mariantanase eccolo qui...
```
<script type="application/ld+json" data-element="metatag">{
                    "name": "<?= $post->post_title; ?>",
                    "serviceType": "<?= $categoria_servizio; ?>",
                    "serviceOperator": {
						<? if ($ipa){?>
							"name": "<?= $ipa; ?>"
						<?} else {?>
							"name": "nessuno"
						<? } ?>
                    },
                    "areaServed": {
						<? if ($copertura_geografica){?>
							"name": "<?= convertToPlain($copertura_geografica); ?>"
						<?} else {?>
							"name": "nessuno"
						<? } ?>
                    },
                    "audience": {
                        "name": "<?= convertToPlain($destinatari); ?>"
                    },
                    "availableChannel": {
                        "serviceUrl": "<?= $canale_digitale_link; ?>",
                        "serviceLocation": {
                            "name": "<?= $ufficio->post_title; ?>",
                            "address": {
                            "streetAddress": "<?= $indirizzo; ?>",
                            "postalCode": "<?= $cap; ?>",
							<? if ($quartiere){?>
								"addressLocality": "<?= $quartiere; ?>"
							<?} else {?>
								"addressLocality": "nessuno"
							<? } ?>
                            }
                        }
                    }
            }</script>
```

**Comment by mariantanase** [comment]
Purtroppo mi da json non valido.

![Screenshot 2023-05-03 at 15-08-48 Lighthouse Report](https://user-images.githubusercontent.com/3976174/235925415-77d2f0c9-f05e-48c7-85b6-7b2d259d2287.png)

**Comment by lucafranco74** [comment]
Buongiorno, io ho inserito tutti i campi possibili ma rimane l'errore per il metatag availableChannel.serviceLocation.address.addressLocality. Lato WP Admin non ci sono campi che fanno riferimento ad una località, qualcuno sa darmi qualche informazione utile? Grazie
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/126711265/4ee85d41-c896-4fcc-a8e3-96c886c803d6)

**Comment by marco-nanni** [comment]
availableChannel.serviceLocation.address.addressLocality ->  Quartiere (campo facente parte dei “Luoghi” assegnato/i al servizio)

**Comment by farapeppe** [comment]
> Purtroppo mi da json non valido.
> 
> ![Screenshot 2023-05-03 at 15-08-48 Lighthouse Report](https://user-images.githubusercontent.com/3976174/235925415-77d2f0c9-f05e-48c7-85b6-7b2d259d2287.png)

L'ho sistemato così:

```
<script type="application/ld+json" data-element="metatag">
{
    "@context": "http://schema.org",
    "@type": "GovernmentService",
    "name": <?php echo json_encode($post->post_title); ?>,
    "serviceType": <?php echo json_encode($categoria_servizio); ?>,
    "serviceOperator": {
        "@type": "GovernmentOrganization",
        <?php if ($ipa){?>
"name": "<?= $ipa; ?>"
<?php } else {?>
"name": "nessuno"
<?php } ?>
    },
    <?php if ( !empty($copertura_geografica) ) : ?>
    "areaServed": {
        "@type": "AdministrativeArea",
        <?php if ($copertura_geografica){?>
"name": "<?= convertToPlain($copertura_geografica); ?>"
<?php } else {?>
"name": "nessuno"
<?php } ?>
    },
    <?php endif; ?>
    "audience": {
        "@type": "Audience",
        "audienceType": "<?php echo convertToPlain($destinatari); ?>"
    },
    "availableChannel": {
        "@type": "ServiceChannel",
        "name": "Dove rivolgersi"
        <?php if ( !empty($canale_digitale_link) ) : ?>
        ,"serviceUrl": <?php echo json_encode($canale_digitale_link); ?>
        <?php endif; ?>
        <?php if ( !empty($ufficio) ) : ?>
        ,"serviceLocation": {
            "name": <?php echo json_encode($ufficio->post_title); ?>,
            "address": {
                "streetAddress": <?php echo json_encode($indirizzo); ?>,
                "postalCode": <?php echo json_encode((string)$cap); ?>,
                <?php if ($quartiere){?>
"addressLocality": "<?= $quartiere; ?>"
<?php } else {?>
"addressLocality": "nessuno"
<?php } ?>
            }
        }
        <?php endif; ?>
    }
}
</script>
```

**Comment by enrimk** [comment]
> > Purtroppo mi da json non valido.
> 
> L'ho sistemato così:
> ```
> 		<?php } else {?>
> 			"name": "nessuno"
> 		<?php } ?>
> ```

Nelle release successive a maggio '23, data di quel suggerimento, la validità formale del JSON è stata poi corretta.

Dal punto di vista della validità "semantica" e dell'utilità dell'informazione data all'utente... si potrebbe eccepire qualcosina nella "soluzione" di riempire i campi con valori "toppa".
Per ora magari si valida, ma solo finché il validatore non si incattivisce; se in una prossima release dovesse diventare più severo controllando anche il contenuto dei campi, e non solo se sono presenti, lo stratagemma non funzionerebbe più.

Poi, coi valori "finti" si contravviene anche allo "spirito" che la piattaforma cerca di incoraggiare, che è di fornire al cittadino il più possibile informazioni utili, e info in formato uniforme che possano dialogare in un sistema automatico. Tanto varrebbe allora che i campi obbligatori non lo fossero.
