### ISSUE TITLE
 Test Conformità AGID - Assicurati che il testo rimanga visibile durante il caricamento dei caratteri web

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#227]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

 Assicurati che il testo rimanga visibile durante il caricamento dei caratteri web.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_11](https://user-images.githubusercontent.com/118733111/229478117-5d77a69b-bbcb-44a6-8b62-edef4d9de808.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by mariantanase** [comment]
> Sembra manchi l'attributo `font-display: swap;` nelle dichiarazioni `@font-face` nel file /assets/css/fonts.css. Come riportato qui: https://developer.chrome.com/docs/lighthouse/performance/font-display/?utm_source=lighthouse&utm_medium=node
> 
> Tra le altre cose è possibile avere i sorgenti dei css come avvenuto per i file Javascript? Grazie.

Confermo!
Aggiungendo la dichiarazione `font-display:swap;` nel `fonts.css`, il messaggio non esce più.

**Comment by marco-nanni** [comment]
Perfetto. 
Però devono rilasciare la modifica altrimenti ad ogni aggiornamento verrebbe sovrascritta oltre ai sorgenti CSS.
