### ISSUE TITLE
Template per le sotto-sezioni dell'Amministrazione

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#228]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Tranne "Documenti e Dati", le altre sottosezioni (Aree Amministrative, Enti e Fondazioni, Organi di Governo, Personale amministrativo, Politici, Uffici) non hanno un template dedicato.
Qualcuno ha sviluppato un template per far mostrare in automatico questi contenuti ?
Grazie

### Includi link o screenshot

![Screenshot 2023-04-03 at 12-10-44 Amministrazione – Design Comuni](https://user-images.githubusercontent.com/3976174/229480295-fae5eb20-dfb8-4357-a740-3f7146230522.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by abmcr** [comment]
Ciao: ma in relazione a questi esempi 

https://italia.github.io/design-comuni-pagine-statiche/#amministrazione

quale template è da usare...

Nel mio test

https://pnrr.mlabvda.it/amministrazione/aree-amministrative/

il testo aggiunto è l'unico campo possibile...
Intendi quindi la parte che nell'esempio è relativa alla parte delle aree in evidenza?

**Comment by mariantanase** [comment]
No, va creato un template per quelle sezioni, in grado che poi vengono popolate in automatico con le UO inserite lato backend.

**Comment by gtimpano74** [comment]
> Ciao: ma in relazione a questi esempi
> 
> https://italia.github.io/design-comuni-pagine-statiche/#amministrazione
> 
> quale template è da usare...
> 
> Nel mio test
> 
> https://pnrr.mlabvda.it/amministrazione/aree-amministrative/
> 
> il testo aggiunto è l'unico campo possibile... Intendi quindi la parte che nell'esempio è relativa alla parte delle aree in evidenza?

Ciao ho visto nel tuo sito di test che hai molti template che non sono presenti nella versione in repository come ad esempio la sezione politici mi potresti dire dove hai preso questi template o come si modificano quelli ufficiali

**Comment by abmcr** [comment]
Li ho sviluppati ....

**Comment by abmcr** [comment]
gtimpano74... sentiamoci in privato

**Comment by abmcr** [comment]
scarica la App di Slack... e poi ci agganciamo li

**Comment by gtimpano74** [comment]
fatto ti ho scritto

**Comment by luciox96** [comment]
Buongiorno @abmcr ho letto che sei riuscito a sviluppare un template smile a quello dell'amministrazione per poterlo applicare anche ad altre aree.
Potremmo sentirci gentilmente? Perché sono settimane che ci sto dietro e non riesco a svilupparlo.

**Comment by fnori77** [comment]
ciao abmcr, come possiamo metterci in contatto su slack? Grazie.
