### ISSUE TITLE
PHP Deprecated:  La funzione get_page_by_title è <strong>deprecata</strong> dalla versione 6.2.0! Utilizza al suo posto WP_Query.

### ISSUE THREAD

**Issue by eb-ai4** [italia/design-comuni-wordpress-theme#229]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Con l'aggiornamento a WP 6.2 la funzione get_page_by_title  è deprecata. 

`PHP Deprecated:  La funzione get_page_by_title è <strong>deprecata</strong> dalla versione 6.2.0! Utilizza al suo posto WP_Query.`

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by abmcr** [comment]
La funzione get_page_by_title è appunto deprecata, per cui va sostituita con una analoga ma che usi WP_Query.

`
function my_get_page_by_title($page_title,  $output = OBJECT, $post_type = "page"){
    
    if ( is_array( $post_type ) ) {
		$post_type           = esc_sql( $post_type );
		$post_type_in_string = "'" . implode( "','", $post_type ) . "'";
    } else {
        $post_type_in_string = $post_type;
    }
    
    $query = new WP_Query(
        array(
            'post_type'              => array( $post_type_in_string ),
            'title'                  => $page_title,
            'post_status'            => 'all',
            'posts_per_page'         => 1,
            'no_found_rows'          => true,
            'ignore_sticky_posts'    => true,
            'update_post_term_cache' => false,
            'update_post_meta_cache' => false
        )
    );
 
    if ( ! empty( $query->post ) ) {
        $page_got_by_title = $query->post;
    } else {
        $page_got_by_title = null;
    }
    return $page_got_by_title;
}
`

Una volta creata , le varie chiamate alla funzione originale vanno cambiate in my_get_page_by_title.
La funzione originale è però usata in molti posti, per cui va proprio inserita nel tema : ci sono 7 file che usano get_page_by_title...

**Comment by zetareticoli** [comment]
ciao @abmcr , il modo migliore per contribuire è aprire una PR così che possiamo fare review e aggiornare il tema.

**Comment by enrimk** [comment]
> La funzione get_page_by_title è appunto deprecata, per cui va sostituita con una analoga ma che usi WP_Query.

Non so se è il caso di sostituirla "con una analoga", probabilmente lo spirito della deprecazione è spingere all'uso _diretto_ di WP_Query (o get_posts).
Tanto più che nel codice della funzione qui sopra, tutto quello che precede e segue WP_Query è del tutto superfluo.
