### ISSUE TITLE
C.SI.3.3 - INFORMATIVA PRIVACY - Il sito comunale deve presentare l'informativa sul trattamento dei dati personali, secondo quanto previsto dalla normativa vigente

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#230]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

C.SI.3.3 - INFORMATIVA PRIVACY - Il sito comunale deve presentare l'informativa sul trattamento dei dati personali, secondo quanto previsto dalla normativa vigente.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_12](https://user-images.githubusercontent.com/118733111/229503903-5d4c65cb-03c6-4aaf-83a5-e8a9ca998a0d.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by HshMatera** [comment]
Errore è dovuto dalla mancata presenza della pagina.
Crea una pagina Informativa privacy e poi crei il link nel menu del footer. 
Ciao
