### ISSUE TITLE
C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ - Il sito comunale deve esporre la dichiarazione di accessibilità in conformità al modello e alle linee guida rese disponibili da AgID in ottemperanza alla normativa vigente in materia di accessibilità e con livelli di accessibilità contemplati nelle specifiche tecniche WCAG 2.1

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#231]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

C.SI.3.2 - DICHIARAZIONE DI ACCESSIBILITÀ - Il sito comunale deve esporre la dichiarazione di accessibilità in conformità al modello e alle linee guida rese disponibili da AgID in ottemperanza alla normativa vigente in materia di accessibilità e con livelli di accessibilità contemplati nelle specifiche tecniche WCAG 2.1.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_13](https://user-images.githubusercontent.com/118733111/229504557-04851c58-3c2b-40ca-a260-5fba940f91d0.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by zetareticoli** [comment]
Ciao @marco-nanni , la compilazione della dichiarazione di accessibilità è a carico dell'ente e del fornitore, non è inclusa nel modello.
