### ISSUE TITLE
Test Conformità AGID -  Gli ID ARIA non sono univoci

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#232]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

Gli ID ARIA non sono univoci.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_14](https://user-images.githubusercontent.com/118733111/229505249-3882bf8d-7e76-4954-a9a9-aa71314fc515.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by HshMatera** [comment]
Questo problema l'ho risolto cambiando l'id in \template-parts\common\svg.php del symbol.
`<symbol id="search1" viewBox="0 0 16 17">`
Ciao
