### ISSUE TITLE
 Test Conformità AGID - Gli elementi di intestazione non sono in ordine decrescente sequenziale

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#233]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

 Gli elementi di intestazione non sono in ordine decrescente sequenziale.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_15](https://user-images.githubusercontent.com/118733111/229505672-3644cf90-e1dd-4fd0-bfc5-e7acda84e9b2.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by HshMatera** [comment]
Io ho risolto questo problema sostituendo <h4> con <h3> in \template-parts\home\calendario.php

**Comment by zetareticoli** [comment]
Sicuramente la soluzione indicata da @HshMatera è quella corretta. Provvediamo a correggere il bug nella versione base del tema, grazie
