### ISSUE TITLE
Test Conformità AGID -  Il file manifest o il service worker dell'app web non soddisfano i requisiti di installabilità

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#234]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

Il file manifest o il service worker dell'app web non soddisfano i requisiti di installabilità.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_16](https://user-images.githubusercontent.com/118733111/229506244-f4492358-cf8f-4257-afb2-0695d8f57f68.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by zetareticoli** [comment]
Questo controllo non è soggetto a criterio di conformità, @marco-nanni ti invito a rileggere [quali sono i criteri](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/conformita/conformita-modello-sito.html)

**Comment by marco-nanni** [comment]
Perfetto, Però perché lo segnala? E' un po' fuorviante.
