### ISSUE TITLE
 C.SI.1.4 - UTILIZZO DI TEMI PER CMS - Nel caso in cui il sito utilizzi un tema messo a disposizione nella documentazione del modello di sito comunale, lo utilizza nella versione 1.0 o successive

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#235]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

 C.SI.1.4 - UTILIZZO DI TEMI PER CMS - Nel caso in cui il sito utilizzi un tema messo a disposizione nella documentazione del modello di sito comunale, lo utilizza nella versione 1.0 o successive.
Si da il caso che il tema attualmente utilizzato è la 1.6.0 (child).

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_17](https://user-images.githubusercontent.com/118733111/229507529-8c9e2a5a-e827-4877-a92c-a59c679577f0.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by zetareticoli** [comment]
Il problema non è riproducibile

**Comment by HshMatera** [comment]
Buongiorno, molto probabilmente è un problema di cache.
Io l'ho risolto intervenendo sulla cache dei file css.

**Comment by marco-nanni** [comment]
@HshMatera 
 Io utilizzo un child e a quanto pare la soluzione dovrebbe essere inserire la parola WordPress o Drupal, a seconda, nella descrizione.
 
 https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html
