### ISSUE TITLE
 C.SI.1.7 - TITOLI DELLE PAGINE DI SECONDO LIVELLO - Nel sito comunale, i titoli delle pagine di secondo livello devono rispettare il vocabolario descritto dalla documentazione del modello di sito comunale

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#236]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
il test di conformità AGID mi riporta la seguente segnalazione:

 C.SI.1.7 - TITOLI DELLE PAGINE DI SECONDO LIVELLO - Nel sito comunale, i titoli delle pagine di secondo livello devono rispettare il vocabolario descritto dalla documentazione del modello di sito comunale.

Il test è stato effettuato sul tema dei comuni standard per WordPress versione 1.6.0.
Potreste verificare ed provvedere alla sua risoluzione?

Grazie.

### Includi link o screenshot

![seglazione_conformita_AGID_18](https://user-images.githubusercontent.com/118733111/229507984-3b1ea76f-c0c5-47d3-ab11-7fd04506650d.PNG)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by zetareticoli** [comment]
Ciao @marco-nanni , dallo screen che hai allegato vedo che il controllo effettuato con l'app di valutazione ti restituisce un 85% di titoli validi. Non c'è alcun bug da risolvere :)

**Comment by HshMatera** [comment]
Buongiorno, per non essere generato l'errore devi modificare la dicitura "Comunicati stampa" in "Comunicati" ed andare a modificare il link del pulsante "Tutti gli Eventi" nella pagina Vivere in Comune facendolo linkare ad una pagina tipo calendario eventi. Ciao

**Comment by marco-nanni** [comment]
Rieffettuando i test con la versione 1.7.1 del tema, il messaggio è cambiato:
![c si 1 7_titoli_delle_pagine](https://github.com/italia/design-comuni-wordpress-theme/assets/118733111/da9beb41-e785-4bce-b663-69127b191a89)
