### ISSUE TITLE
Impostare all'interno dell'Homepage, 6 News in evidenza invece di 3

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#239]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti,

Per caso qualcuno ha provato ad impostare 6 news in evidenza invece di 3, all'interno dell'homepage nella sezione "Configurazione"?
Attualmente sono presenti 3 schede; quindi ho provato ad andare a modificare il file pagina_home.php (inc>admin>options>..) inserendo una quarta scheda e copiando il codice precedente, ma non sono riuscito ad ottenere il risultato sperato.
Qualcuno ha avuto lo stesso problema?

### Includi link o screenshot

![screen](https://user-images.githubusercontent.com/128592652/230052761-a1236989-464e-42c9-9c34-667be102a64f.JPG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by mariantanase** [comment]
Non ti basta quello, devi definire anche le variabili `$scheda4`, `$scheda5` e `$scheda6`, così:
```
$scheda4 = dci_get_option('schede_evidenziate_4','homepage', true )[0] ?? null;
...
```
