### ISSUE TITLE
Formattazione dei testi WYSIWYG

### ISSUE THREAD

**Issue by nomissor** [italia/design-comuni-wordpress-theme#24]
Ho notato che i vari testi inseriti tramite editor WYSIWYG nel frontend non vengono poi visualizzati con la formattazione corretta per quanto riguarda gli accapo dei paragrafi.
Nella documentazione del plugin CMB2 è scritto che è una scelta nella progettazione del plugin. che si può ovviare andando ad aggiungere in fase di rendering la funzione wpautop.

Il fatto che non l'abbiate aggiunta, è una scelta dettata dalle linee guida?

**Comment by zetareticoli** [comment]
@nomissor no, nessuna linea guida si esprime in tal senso. Penso che sia un bug di configurazione.

Puoi proporre una PR di modifica così integriamo nel tema, grazie 🙏

**Comment by astagi** [comment]
@nomissor ho visto la chiusura della PR, la #44 e #46 dovrebbero già risolvere questa parte, la tua PR aggiungerebbe altre parti di formattazione?

**Comment by nomissor** [comment]
No nulla di più.
Grazie.

**Comment by astagi** [comment]
Grazie a te @nomissor
