### ISSUE TITLE
Creazione pagina  "Archivio Eventi"

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#240]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti,

All'interno del tema non sono riuscito a trovare "l'archivio Eventi" o "Eventi".
(sono presenti quelli delle notizie, dei servizi, ecc... ma non per gli eventi)
Sapete per caso come fare?

Grazie mille

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @luciox96, nel tema non è presente quel template. 

Se lo crei autonomamente, puoi basarti su uno dei possibili [layout di tipo lista ](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/%5BComuni%5D-Modello-sito-e-servizi?type=design&node-id=9979%3A204736&t=EJ7bHh0zFcApQfrd-1)
