### ISSUE TITLE
Aggiungere nuova voce nel main menù

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/design-comuni-wordpress-theme#241]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Vista la possibilità, come da normativa, di poter aggiungere fino a 3 voci nel main menù in più a quelle previste, quando si aggiunge una nuova voce, dall'home page viene automaticamente selezionata (cioè viene impostata come "active"), cliccando la voce creata e visualizzando il suo contenuto viene automaticamente rimosso l'attributi "active" e di conseguenza non più selezionata, il comportamento della voce di menù è errato, praticamente al contrario.
Spero di essere stato chiaro...

Ver. wordpress: 6.1.1
Ver. Tema: 1.6.0, ma ho testato anche la 1.6.2 e il comportamento è uguale.

Grazie

### Includi link o screenshot

![comune_test_documenti](https://user-images.githubusercontent.com/83232158/230116544-79762a24-627a-4d08-bc76-52320a4105a7.jpg)
![comune_test_home](https://user-images.githubusercontent.com/83232158/230116554-2caa393f-d9b7-41c4-8265-99825fe8b2f2.jpg)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by StefanoDevPro** [comment]
Stessa problematica se, anche per errore, si rimuove e si ri-aggiunge una voce già prevista al momento dell'installazione, ogni voce che si inserisce risulta "active" in home page.

**Comment by mariantanase** [comment]
Quando si aggiunge una nuova voce di menu di solito non viene popolato il campo "**Attributo del titolo**".

![Screenshot 2023-04-06 at 08-40-19 Menu ‹ Design Comuni — WordPress](https://user-images.githubusercontent.com/3976174/230292754-db323d56-b686-4e2a-868c-661ed2867e9c.png)

Compila quel campo con qualcosa tipo "**documenti-e-dati**" e vedrai che si risolve il problema.

**Comment by zetareticoli** [comment]
@abmcr segnalo che la voce "documenti e dati" non è di primo livello, così facendo avresti un errore nel rispetto dei criteri di conformità
