### ISSUE TITLE
Inserimento "Categorie Servizi" o "Servizi" in Homepage

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#242]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti,

In Homepage, attualmente, è possibile inserire 3 news, gli eventi in corso e gli argomenti principali.
Volevo chiedervi se ci fosse la possibilità di inserire anche le "Categorie dei Servizi" o "Servizi", magari come le notizie, a blocchi di 3.

Grazie mille

### Includi link o screenshot

![servizi](https://user-images.githubusercontent.com/128592652/230127109-28f10d1f-342a-4924-8ca2-1dbb0f3fa213.JPG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @luciox96, c'è la piena libertà di personalizzare l'impaginazione dei contenuti, rispettando comunque l'architettura dell'informazione per quanto riguarda i _content-type_, le tassonomie e il menu di navigazione di primo livello.

**Comment by luciox96** [comment]
Ciao @zetareticoli grazie mille!
Chiudo il task
