### ISSUE TITLE
Attributo "title" sui link del sito comunale

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/design-comuni-wordpress-theme#243]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti, da quanto ho potuto verificare, non è presente l'attributo "title" sui link del sito, credo sia un obbligo riguardante l'accessibilità per l'utilizzo del browser vocale. Non era presente neanche nella 1.6.0.
Spero di sbagliarmi, ma credo che sia obbligatorio.

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @StefanoDevPro, l'attributo `title` pone delle problematiche di accessibilità che trovi [spiegate qui](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns).

Forse intendevi l'attributo `alt`?
