### ISSUE TITLE
Data di scadenza notizia

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#244]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Mi potete spiegare qual'è la funzionalità o scopo del campo "**Data di scadenz**a" per le notizie ?
In teoria, mi aspetto che se il campo è compilato, dopo quella data la notizia in questione non dovrebbe essere più visibile sul sito. 
In pratica, non influisce in alcun modo sulla visualizzazione di quella notizia.

### Includi link o screenshot

![Screenshot 2023-04-06 at 14-48-20 Modifica la Notizia “Elezioni Trasparenti 2023” ‹ Comune di Valenzano — WordPress](https://user-images.githubusercontent.com/3976174/230383873-b12613cb-5bee-4136-ad2d-874182e43611.png)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by abmcr** [comment]
Concordo con te sul fatto che , per come la intendo io, dopo la scadenza la notizia dovrebbe più essere visibile.
Altrimenti non capisco il senso, ache perché tale data non compare in nessun altro modo nel front end.

Se fosse come intendiamo, per rimediare al bug, è sufficiente un cron (wp-cron) che metta lo stato su draft dopo tale data/ora. 

Aspettiamo di avere un feed...

**Comment by zetareticoli** [comment]
La data di scadenza fa rifermento alla categoria Avvisi che in genere la prevedono. Hai provato applicando questa categoria alla notizia?

**Comment by mariantanase** [comment]
> La data di scadenza fa rifermento alla categoria Avvisi che in genere la prevedono. Hai provato applicando questa categoria alla notizia?

Si, ho provato con tutti i tipi di notizie, impostando una data di scadenza precedente alla data odierna.
La notizia compare lo stesso.

**Comment by Cam-al** [comment]
é stato risolto ?

**Comment by abmcr** [comment]
Avevo postato lo pseudo code..io ho fatto un shedule cron in functions ...
