### ISSUE TITLE
Pagina site-map assente

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#245]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiono,
la pagina relativa al site map non è presente e questo porta ad un errore.
Ho provveduto a generare la pagina (vuota) giusto per non vedere il 404.

Avete in programma di svilupparla?
Se no, esiste qualche plugin che si può sfruttare o va creato da zero?
In quest ultimo caso, ci sono delle linee guida particolari da seguire e sopratutto è obbligatoria?

Grazie.

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.0

**Comment by zetareticoli** [comment]
Ciao @marco-nanni ,

abbiamo aggiunto il [template "Mappa del sito"](https://italia.github.io/design-comuni-pagine-statiche/sito/mappa-sito.html) la scorsa settimana

**Comment by marco-nanni** [comment]
Ciao @zetareticoli 
servirebbe la versione per WordPress però.
Ma rimmarà statica oppure dinamica?

Grazie.
