### ISSUE TITLE
Problema visualizzazione "Tutti gli eventi" e "Tutti i luoghi"

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#247]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti,

Ho creato diversi "Eventi" e "Luoghi" per poterli visualizzare tutti quanto insieme.
Ho popolato la pagina "Vivere il comune" tramite l'apposita configurazione inserendo 6 Eventi e 6 Luoghi.
MA, se provo a cliccare sulle CTA "Tutti gli eventi" o "Tutti i luoghi", mi restituisce una pagina 404; questo perché non è previsto un template per la visualizzazione dei suddetti ("archive-eventi" e "archive-luoghi").
Sapete per caso se è possibile visualizzare l'archivio in un altro modo?

### Includi link o screenshot

![tutti gli eventi](https://user-images.githubusercontent.com/128592652/231196547-f03f84e6-d164-4bdc-b8c2-6b63e5c76119.JPG)
![tutti i luoghi](https://user-images.githubusercontent.com/128592652/231196554-7ff5af7c-104d-4a1e-b6ad-0c96392380a7.JPG)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by luciox96** [comment]
Qualcuno ha per caso trovato un modo per visualizzare "tutti gli eventi" o "tutti i luoghi"?
O per sicurezza mi conviene togliere il bottone per ora?

**Comment by zetareticoli** [comment]
Ciao @luciox96, il template da te cercato non è incluso. Deve essere implementato autonomamente.

Nelle prossime settimane inizieremo una nuova fase di aggiornamento e integrazione delle funzionalità mancanti quindi puoi aspettarti aggiornamenti in tal senso.

**Comment by luciox96** [comment]
Ottimo! Grazie mille per l'informazione @zetareticoli
