### ISSUE TITLE
Widget disabilitati

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#25]
La voce di menu relativa ai widget è disabilitata sul menu /wp-admin/widgets.php
E' una scelta legata all'accessibilità del template ? Oppure verranno abilitati in una delle prossime release?
Il messaggio ricevuto è 
_"Il tema attualmente in uso non è pronto per i widget, quindi non ha alcuna barra laterale che è possibile modificare. "_

**Comment by Takedown81** [comment]
anche a me interessa questa cosa, in particolare per quanto concerne le barre laterali nelle pagine, che allo stato attuale non sono presenti, quindi rende impossibile ad esempio inserire lateralmente pulsanti (come quello SPID-CIE, e/o altri link relativi all'oggetto della pagine creata.

**Comment by zetareticoli** [comment]
Il tema non prevede utilizzo di menu di navigazione alternativi a quelli già presenti (header e indice di pagina).
