### ISSUE TITLE
App Valutazione comuni

### ISSUE THREAD

**Issue by ivancorsetti** [italia/design-comuni-wordpress-theme#250]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Facendo la verifica con la app-valutazione-comuni messo a disposizione, anche a template appena montato quindi voto risulta sempre la non compatibilità.
Qualcuno ha avuto modo di verificare se funziona correttamente l'app ?

### Includi link o screenshot

<img width="924" alt="image" src="https://user-images.githubusercontent.com/3714484/233115989-531a8ba4-04f8-4399-9759-3ff4119f988e.png">

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

Design Comuni ItaliaVersione: 1.6.2

**Comment by abmcr** [comment]
Da 1.5 in avanti ci potrebbe anche stare visto che il tema "vanilla" non ha quei dati.. ma i primi invece mi preoccupano.. appena riesco provo anche io a far girare il validatore
Hai usato l'ultima versione ?

**Comment by ivancorsetti** [comment]
Si . https://github.com/italia/pa-website-validator/releases

**Comment by ivancorsetti** [comment]
Ciao, ho appena utilizzato la nuova versione del validatore.
Ancora problemi.

**Comment by zetareticoli** [comment]
CIao @ivancorsetti , hai popolato le pagine del sito con i contenuti necessari?

**Comment by ivancorsetti** [comment]
Qualcuna si. Comunque senza fare nulla dopo qualche giorno ripetendo il test, il primo blocco  di errore è sparito.
Adesso rimangono accesi alcuni errori che ancora non ho visto in dettaglio. 
Aggiorno appena termino.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/3714484/235640006-35adfd4f-4bdb-452f-9c05-523ea76a2e4e.png">

**Comment by ivancorsetti** [comment]
Ciao, qualcosa non va. Sempre senza toccare nulla mi ha ridato di nuovo tutti gli errori anche dei font.
Validatore da controllare bene.
Ciao

**Comment by abmcr** [comment]
idem.... dopo 4 giorni sullo stesso sito errori rilevati diversi

**Comment by enrimk** [comment]
Il validatore, a quanto pare, non valida tanto "il tema", quanto "il sito"; cioè si aspetta che ci siano già dentro dei contenuti.
Sembra anche che faccia [controlli "a campione"](https://github.com/italia/pa-website-validator/blob/422acdbac13a48e145b71bc8e8fc53a4fdf55731/src/utils/municipality/utils.ts#L20), forse è per questo che i risultati non sono sempre gli stessi.
E poi, alcuni controlli hanno delle "dipendenze" non scontate, che uno magari non si aspetta. Ad es. vedo che per controllare Bootstrap cerca nella home e [in tre pagine a caso di diversi livelli](https://github.com/italia/pa-website-validator/blob/422acdbac13a48e145b71bc8e8fc53a4fdf55731/src/audits/municipality/bootstrapItaliaDoubleCheckAudit.ts#L106). Se qui non sono stati ancora inseriti Servizi, o se trova una pagina "sfortunata" senza meta tag o in qualche altro modo incompleta, fallisce tutto il test.
