### ISSUE TITLE
Problema autocompletamento - Segnalazione disservizio

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#256]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve,
sto cercando di implementare la pagina:

https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-02-dati.html

Cerco di passare i dati all'autocomplete via ajax sfruttando alcune API per recuperare indirizzi ma non ottengo alcun risultato.
Ho cercato sul componente di bootstrap italia (https://italia.github.io/bootstrap-italia/docs/form/autocompletamento/) e sulla documentazione annessa, ma è veramente minimale e non menziona l'aggiornamento asincrono.

Nel tema dove viene inizializzato il componente? Come si fa ad aggiornare l'autocompletamento?

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2.

**Comment by abmcr** [comment]
Ciao stefanoianna... identico problema.. hai scoperto qualcosa ? grazie

**Comment by stefanoianna** [comment]
Ciao, ho risolto utilizzando il componente nativo di jquery ui per l'autocompletamento.
Tra l'altro sulle issue del componente attualmente utilizzato c'è scritto che non è stato pensato per ricevere dati in maniera asincrona.

Sinceramente mi chiedo con quale criterio vengano sviluppati i template visto che non sono adatti.

**Comment by abmcr** [comment]
grazie.. devo sviluppare anche io tutti i custom post type ecc..

**Comment by stefanoianna** [comment]
Fai attenzione perchè c'è una funzione che filtra gli elementi del menu, quindi se non aggiungi a quella funzione anche i nuovi post type non li vedi. La funzione non è neanche sovrascrivibile, quindi ad ogni aggiornamento devi anche andare a correggere a mano ciò che hai modificato nel tema padre.

**Comment by abmcr** [comment]
si ho letto la tua issue.. stai sicuro che se qualcosa non mi torna ti chiederò :-)

**Comment by abmcr** [comment]
Ciao @stefanoianna : non trovo più la issue in cui specificavi il file da modificare per poter visualizzare i custom post type nel menu...
