### ISSUE TITLE
Riferimenti sbagliati alle icone - Tema wordpress, file comuni.js

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#257]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve,
nel tema wordpress, nel file comuni.js (design-comuni-wordpress-theme/assets/js/comuni.js ) ci sono riferimenti sbagliati alle icone.
Nello specifico l'icona della "X" viene referenziata con questo path: <use xlink:href="../assets/bootstrap-italia/dist/svg/sprites.svg#it-close"></use> quando invece dovrebbe essere <use href="#it-close"></use>

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by abmcr** [comment]
mi sa che il sistema ha tolto le path....

**Comment by stefanoianna** [comment]
use xlink:href="../assets/bootstrap-italia/dist/svg/sprites.svg#it-close"
Deve essere:
use href="#it-close"
