### ISSUE TITLE
Scroll menù laterale non funziona 

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#260]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve,
nel template da voi proposto per le segnalazioni:

https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-02-dati.html

c'è un menù laterale per scrollare alle varie sezioni. Implementandolo nel vostro template wordpress al click la pagina non scrolla alla sezione. Il problema sono 2 menù nella pagina?

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @stefanoianna, per implementarlo correttamente dovresti seguire il template statico che trovi sia nella segnalazione disservizio che in altri template (es.servizio-dettaglio.html)

**Comment by stefanoianna** [comment]
Ciao, ho utilizzato esattamente quei template ma non funziona.
