### ISSUE TITLE
Gestione degli appuntamenti 

### ISSUE THREAD

**Issue by EliaTolin** [italia/design-comuni-wordpress-theme#266]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Integrare un tool per la gestione degli appuntamenti direttamente dalla gestione del sito. 

### Motivazione e contesto

Sarebbe utile gestire direttamente tutte le disponibilità direttamente dal sito!

**Comment by abmcr** [comment]
Ciao: la funzione credo non verrà mai sviluppata, in quanto molti enti usano servizi terzi e , effettivamente, la gestione degli appuntamenti è molto custom...
io comunque ci sto trafficando perchPé nel mio caso la gestione sarà interna a Wordpress cosi come quella della segnalazione dei disservizi....
