### ISSUE TITLE
Configurazione della pagina Novità - Notizie in Evidenza

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#268]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo aver inserito una notizia in evidenza non è possibile rimuoverla
Con il tasto - è possibile riportarla nel box di sinistra, ma poi al salvataggio della configurazione la notizia rimane comunque in evidenza

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.6.2

**Comment by mariantanase** [comment]
Confermo !

**Comment by enrimk** [comment]
Anche i "Contenuti in evidenza" nel tab "Documenti e dati" hanno lo stesso problema.
Non si può "sbiancare" il campo: cercando di salvare un valore vuoto dopo averci messo qc., non si ha nessun effetto.

Coincidenza (?), le due tab sono organizzate in modo identico, così come l'opzione che viene (dovrebbe venire) salvata a db: selezione `contenuti_evidenziati`, e selezione `argomenti`.

Controllando un po' oltre, sembra che il salvataggio di `contenuti_evidenziati`, quando vuoto, venga proprio saltato da CMB2.  La ragione non mi è ancora chiara...

Fortunatamente CMB2 ha un sacco di hook e filtri che si possono sfruttare per metterci una pezza - ma c'è sicuramente un bug più profondo che va investigato.

Come _hotfix_, meglio se nel child theme, in functions.php ad es., si può aggiungere una toppa di questo genere:

```
/* hotfix bug CMB2 (?) al salvataggio di certe opzioni vuote. */
add_filter('cmb2_override_contenuti_evidenziati_meta_remove', function($override, $args, $field_args, $field){
	if ( ! in_array($args['id'], ['novita','documenti']) ) return $override;
	return cmb2_options( $args['id'] )->remove( $args['field_id'], true );
}, 10, 4);
```

...che [si aggancia a questo hook](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/lib/CMB2/includes/CMB2_Field.php#L432C30-L432C74), e in sostanza forza e anticipa il salvataggio. 
Finché non si chiarisce meglio la causa del bug.
