### ISSUE TITLE
La ricerca non viene effettuata nelle pagine

### ISSUE THREAD

**Issue by abmcr** [italia/design-comuni-wordpress-theme#271]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

La ricerca globale nel sito non prende in esame il contenuto delle pagine (post type: page)

FIX: nel file inc/comuni_config.php la funzione alla linea 129 diventa

```
function dci_get_sercheable_tipologie() {
    return array(
        'unita_organizzativa',
        'evento',
        'luogo',
        'documento_pubblico',
        'notizia',
        'servizio',
        'persona_pubblica',
        'dataset',
        'page',
       'post' //se si vogliono includere anche gli articoli
    );
}

```
successivamente aggiungere in inc/comuni_tipologie.json il seguente blocco

```
        "page": {
            "name" : "page",
            "singular_name" : "Pagina",
            "plural_name" : "Pagine"
        },
```

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @abmcr , nella descrizione del problema hai indicato anche il fix. Se apri la PR agganciata a questa issue, procediamo con la review e il merge. Grazie

**Comment by abmcr** [comment]
Fatta PR

**Comment by enrimk** [comment]
Attenzione, che la risoluzione di questo issue (secondo #279, poi integrata in #349), ha introdotto [un warning php](https://github.com/italia/design-comuni-wordpress-theme/pull/349#issuecomment-1710876981).
