### ISSUE TITLE
Implementazione "Segnalazione Disservizio". E' obbligatorio seguire i template o può essere gestito diversamente?

### ISSUE THREAD

**Issue by GabrieleMartina** [italia/design-comuni-wordpress-theme#272]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
sto cercando di implementare il flusso di "Segnalazione Disservizio", mi chiedo se ci siano specifiche direttive su come debba essere fatto;
Tale flusso deve seguire obbligatoriamente i template/step mostrati all'interno del [github per il design](https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-dettaglio.html)
oppure può anche essere gestito diversamente con ad esempio un modulo che permetta l'invio di email?

### Su quale sistema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by michmeno** [comment]
Puoi scegliere se utilizzare un link diretto all'e-mail del Comune, oppure creare un servizio dedicato (https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/funzionalita.html#segnalazione-disservizio). Se decidi per il servizio dedicato devi attenerti alle indicazioni di Designers Italia
