### ISSUE TITLE
Aggiunta gallery con lightbox

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#273]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Le gallery standard presenti ora nel sito permettono di aprire l'immagine come link, non si possono scorrere o chiudere.

Posso utilizzare una libreria per aggiungere la lightbox ? O ci sono dei problemi in validazione del sito?

### Motivazione e contesto

Le gallery attualmente sono limitanti e scomode

**Comment by abmcr** [comment]
io ho aggiunto e non pare avere problemi col validatore
