### ISSUE TITLE
Area di testo WYSIWYG

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#275]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho riscontrato che i post di tipo luogo hanno dei problemi nella visualizzazione della descrizione estesa.
L'area testo è una WYSIWYG ma non mostra il contenuto nello stesso modo in cui lo scrivo.

Il testo non viene racchiuso tra paragrafi, se passo alla visualizzazione da **Visuale** a **Testo**, non vedo gli elementi <p></p>

Se inserisco il mio contenuto come html nella visualizzazione **Testo**, allora poi la vedo corretta, ma nel momento in cui rimetto la visualizzazione a **Visuale**, torno ad avere il problema precedente ed infatti gli elementi <p></p> non ci sono più.

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/115085709/66d9f4b8-4525-4ba3-8c9d-0e3129d8415c)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.6.2

**Comment by enrimk** [comment]
È il comportamento normale dell'editor "classico" di WordPress (tinyMCE), ed è anche il modo in cui i contenuti dei post vengono salvati nel database: tutti i tag `<br>` e `<p>` sono sostituiti da semplici a-capo. [^1]
[^1]: Immagino che, agli inizi di WP, fu fatta questa scelta per "semplificare" l'html... Può darsi per una certa sfiducia verso la competenza tecnica dell'utente medio di WP (o per attivamente cercare una certa base di utenti). Scelta "democratica", diciamo - ma azzeccata, vista la diffusione dell'app.

L'html completo [viene ripristinato solo dopo](https://developer.wordpress.org/reference/functions/wpautop/), a frontend.

Generalmente nei template, i valori dei campi wysiwyg vengono letti con [`dci_get_wysiwyg_field()`](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/utils.php#L144), che li passa attraverso `wpautop()`. Se non è così, gli a-capo non si vedranno.
