### ISSUE TITLE
Errore JS nel configuratore

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#276]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Da quando ho aggiornato all'ultima versione, provando a fare delle modifiche nel configuratore ottengo l'errore (Riporto la console):

Uncaught TypeError: $el.attr(...) is undefined
    updateNameAttr https://[nome sito]/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/js/cmb2.min.js?ver=2.10.1:1
    removeGroupRow https://[nome sito]/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/js/cmb2.min.js?ver=2.10.1:1
    jQuery 2
    removeGroupRow https://[nome sito]/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/js/cmb2.min.js?ver=2.10.1:1
    jQuery 10
    init https://[nome sito]/wp-content/themes/design-comuni-wordpress-theme-main/inc/lib/CMB2/js/cmb2.min.js?ver=2.10.1:1
    jQuery 13
cmb2.min.js:1:12874

Questo problema si presenta ad esempio quando provo a rimuovere i social media nel configuratore.

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by stefanoianna** [comment]
Confermo la presenza dell'errore anche nella versione 1.7.1

**Comment by enrimk** [comment]
Io riscontro l'errore solo sul tab _Configurazione>SocialMedia_, tutti gli altri controlli non lo danno.
[con 1.7.3, ma non dovrebbe essere cambiato niente di pertinente nel frattempo]

Poi, si verifica solo in un caso particolare: eliminando l'_ultimo_ elemento Social. Gli altri si cancellano correttamente.

In quel caso invece, non solo l'ultimo non viene cancellato, ma compare dal nulla il template di un secondo elemento vuoto, come se si fosse cliccato "Aggiungi un social", e non "Rimuovi".

**Comment by enrimk** [comment]
Risalendo dall'errore, il punto cruciale sembra che sia il campo icona.

Dunque: CMB2, alla cancellazione di un gruppo _repeatable_, rinumera i campi. [Per farlo, usa l'`id`](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/lib/CMB2/js/cmb2.js#L623) degli `<input>`. Si aspetta che gli input che trova siano quelli dei valori delle opzioni. Ora, il campo icona (["faiconselect"](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/options/opzioni_social.php#L81C20-L81C32)) ha dei campi ausiliari che non usa per metterci il suo valore, ma per la ricerca nella lista icone. E questi campi non hanno `id`. Non hanno neanche `name`, perché sono usati solo da frontend. Questo manda lo script di CMB2 in confusione.

Per fortuna, CMB2 [ha un'opzione con cui indicargli quali campi cercare nei _repeatable_](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/lib/CMB2/js/cmb2.js#L25).
Per sfortuna, lo script è minificato. Ma CMB2 sta nello scope globale, la sua opzione è una proprietà public, e possiamo passare l'opzione a posteriori, dopo l'inizializzazione.

In breve: si dovrebbe risolvere, anche senza alterare gli script, con una toppa di questo tipo:
```
/* Hotfix bug CMB2 + repeatable + faiconselect in pannello opzioni tema (Social) */
add_action( 'cmb2_footer_enqueue', function(){
	wp_add_inline_script( 'cmb2-scripts', 'jQuery(function(){ (CMB2 || {}).repeatEls = \'input:not([type="button"]):not(.icons-search-input),select:not(.icon-category-select),textarea,.cmb2-media-status\'; });' );
});
```
