### ISSUE TITLE
Assenza template per i tipi documento (documenti e dati)

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#277]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
stiamo riscontando la mancanza dei template relativi a documenti e dati per tipo documento.
Ad esempio "[Accordo tra enti](https://wp-dev1.ecohmedia.com/tipi_documento/accordo-tra-enti/)" posra alla home page.
Questo vale per tutte le tipologie di documento.
Come è possibile ovviare la problema?

Grazie.

### Includi link o screenshot

![documenti_e_dati_bug_1](https://github.com/italia/design-comuni-wordpress-theme/assets/118733111/7834f128-ce7a-4fa9-b563-a1c3a3179801)

![documenti_e_dati_bug_2](https://github.com/italia/design-comuni-wordpress-theme/assets/118733111/23abd45d-633d-419a-95b3-383a8c03853c)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by michmeno** [comment]
C'è una pull request a riguardo, guarda #252
