### ISSUE TITLE
Non popola la pagina Politici

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#280]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Come per altri template come quello delle persone, il tema nonostante la compilazione di tutti i campi alla fine non crea il template come dovrebbe. Anzi non inserisce quasi nulla. 

### Includi link o screenshot

![Immagine](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/e4460fa5-a014-40e9-909b-e85f0436d5da)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.1

**Comment by fabricius4** [comment]
inoltre, anche la vista delle persone pubbliche non viene compilata.

**Comment by zetareticoli** [comment]
Ciao @fabricius4, alcuni templates, come quello per le persone, non sono attualmente disponibili.

Il consiglio è quello di seguire il [layout hi-fi disponibile su Figma](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/%5BComuni%5D-Modello-sito-e-servizi?type=design&node-id=24059%3A198882&t=eT8fBML95xzaZUjN-1) e, attraverso i [templates statici](https://github.com/italia/design-comuni-pagine-statiche), riutilizzare codice HTML, CSS e PHP del tema per crearne uno nuovo.

Ogni aggiunta può essere messa a riuso open-source contribuendo al tema ufficiale tramite PR su questo repository 🙌
