### ISSUE TITLE
Impossibilitato ad accedere nelle sezioni "tickets" , "valutazioni" e "appuntamenti"

### ISSUE THREAD

**Issue by GabrieleMartina** [italia/design-comuni-wordpress-theme#281]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Per la gestione dei singoli permessi, ho testato due plugin, entrambi mi visualizzano l'impossibilità di accedere nelle sezioni riguardanti le valutazioni, i tickets e gli appuntamenti. Credo sia un problema di tema, potrei avere qualche delucidazione?
Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

ultima

**Comment by Cam-al** [comment]
anche io riscontro lo stesso problema

**Comment by enrimk** [comment]
Credo sia intenzionale, "da progetto", che appuntamenti, ticket e valutazioni non diano accesso _alla creazione di un elemento_ (alla lista sì però, almeno all'amministratore).
Immagino che l'idea sia che questi sono elementi creati dall'utenza del sito, non dalla redazione. È solo il cittadino che può aprire un ticket, ecc. [^1]
[^1]: Scelta forse opinabile... Per es. in WP i commenti li crea di solito un visitatore, ma non è che l'admin non possa farlo se lo ritiene utile. È vero però che forse questi casi sono più complessi, e "impersonare" un utente è più problematico per varie ragioni (SPID, e quant'altro... non ho ancora controllato). 

Fatto sta che nella dichiarazione di tutti e tre i _post type_ ([appuntamenti](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/tipologie/tipologia_appuntamento.php#L32C1-L32C1), [ticket](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/dci_richiesta_assistenza.php#L31) e [valutazioni](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/dci_rating.php#L31)), la creazione del post è esplicitamente proibita.

**Comment by Cam-al** [comment]
quello si, anche io lo vedo cosi con il mio utente amministratore, ma l'utente del comune dovrebbe poter vedere i ticket aperti o le valutazioni , a me dice che non ho i permessi

**Comment by enrimk** [comment]
Le capabilities da assegnare all'utente sono quelle definite normalmente sui _post type_ [secondo lo schema classico di WP](https://developer.wordpress.org/reference/functions/get_post_type_capabilities/), con nomi speciali per ogni tipologia di contenuto.
Ad es., [il parametro capability_type del tipo Appuntamento](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/tipologie/tipologia_appuntamento.php#L30) definisce dei permessi con nomi come "edit_appuntamenti", sul modello di "edit_posts", eccetera.

Per ticket e valutazioni avrai rispettivamente [`edit_richieste_assistenza`](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/dci_richiesta_assistenza.php#L29C61-L29C81) e [`edit_ratings`](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/dci_rating.php#L29), e così via.
