### ISSUE TITLE
Permessi assegnati al post_type

### ISSUE THREAD

**Issue by GabrieleMartina** [italia/design-comuni-wordpress-theme#283]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti, utilizzando il tema dei comuni, alla tipologia "Appuntamenti" viene, secondo me erroneamente, assegnato il permesso di gestione "edit_posts" che si riferisce agli articoli nativi di wordpress, e non "edit_appuntamenti" come previsto per questo post_type. In quale porzione di codice posso modificare questo controllo?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

ultima

**Comment by abmcr** [comment]
Devi creare le capabilities ed un ruolo adatti al tuo caso

**Comment by Cam-al** [comment]
io ho lo stesso problema con "configurazione"

**Comment by enrimk** [comment]
Però _edit_posts_ non risulta. Come hai controllato?
```
$ wp post-type get appuntamento --fields=cap --format=yaml
---
cap:
  edit_post: edit_appuntamento
  read_post: read_appuntamento
  delete_post: delete_appuntamento
  edit_posts: edit_appuntamenti
  edit_others_posts: edit_others_appuntamenti
  delete_posts: delete_appuntamenti
  publish_posts: publish_appuntamenti
  read_private_posts: read_private_appuntamenti
  read: read
  delete_private_posts: delete_private_appuntamenti
  delete_published_posts: delete_published_appuntamenti
  delete_others_posts: delete_others_appuntamenti
  edit_private_posts: edit_private_appuntamenti
  edit_published_posts: edit_published_appuntamenti
  create_posts: do_not_allow
```
