### ISSUE TITLE
Problema layout pagina "documenti e dati" con versione 1.7.0

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#285]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

dopo aver aggiornato il tema, l'unica pagina sulla quale non carica il layout è 'Documenti e dati' come da screen. Carica la pagina tutta centrata, come se non riuscisse a caricare le librerie. 

### Includi link o screenshot

![doc e dati](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/ef44651c-5c56-4f7d-8203-29c5bd320f99)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.0

**Comment by fabricius4** [comment]
si ho visto anch'io. Al momento ho risolto ricopiando il codice della versione precedente.

Invece se volessi mantenere questo codice, alla luce del bug su $tipo, cosa dovrei modificare?

**Comment by mariantanase** [comment]
confermo

**Comment by abmcr** [comment]
https://github.com/italia/design-comuni-wordpress-theme/issues/286
