### ISSUE TITLE
Domande frequenti - mancata visualizzazione risposta nella pagina delle domande frequenti

### ISSUE THREAD

**Issue by abmcr** [italia/design-comuni-wordpress-theme#287]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella pagina con template page-templates/domande-frequenti.php la risposta alla Domanda non viene visualizzata
Il problema è nel file template-parts/domanda-frequente/item.php che deve  essere corretto come segue

`<?php
global $i;
$prefix = "_dci_domanda_frequente_";
$description = dci_get_meta('risposta', $prefix , $post->ID); 
 `
`?>`

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.0

**Comment by enrimk** [comment]
Bug reale e [verificabile](https://github.com/italia/design-comuni-wordpress-theme/blob/7a92e3faef3a67daef43bc3334f727e56ee68bc9/template-parts/domanda-frequente/item.php#L4), soluzione semplice e già data all'apertura dell'issue: perché non risolverlo?

```diff
+++ a/template-parts/domanda-frequente/item.php
--- b/template-parts/domanda-frequente/item.php
@@ -1,5 +1,5 @@
<?php
global $i;

- $description = dci_get_meta('risposta'); 
+ $description = dci_get_meta('risposta', '_dci_domanda_frequente_', $post->ID);
?>
```
