### ISSUE TITLE
Errore durante il salvataggio di un post

### ISSUE THREAD

**Issue by sync3ds** [italia/design-comuni-wordpress-theme#289]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Alla pubblicazione/aggiornamento di qualsiasi post type, appare il seguente messaggio di errore:
`Warning: Undefined array key "post" in /var/www/html/wp-content/themes/design-comuni-wordpress-theme/inc/admin/page.php on line 53`
Il problema è identificato dal codice seguente:
```
if(isset($_GET['post']))
       $curr_page_id = $_GET['post'];
else if(isset($_POST['post_ID']))
       $curr_page_id = $_POST['post_ID'];

if ( ! isset( $curr_page_id ) ) {
       return;
}

$curr_page_id = $_GET['post'];
```
L'ultima riga andrebbe rimossa perché la variabile $curr_page_id è già stata valorizzata nelle righe precedenti.
Inoltre, nell'ultima riga si da per scontato che nella url della pagina ci sia il query param "post" ma in caso di pubblicazione/aggiornamento, il parametro è in $_POST, quindi l'ultima riga genera ovviamente errore.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.0

**Comment by enrimk** [comment]
_Wontfix_ direi che non è appropriato, perché:
1) il problema esiste ed è verificabile;
2) sussiste tuttora e non è mai stato corretto;
3) la soluzione è semplice;
4) la soluzione è stata già proposta dall'OP, insieme alla segnalazione.

```diff
--- a/inc/admin/page.php
+++ b/inc/admin/page.php
@@ -44,13 +44,12 @@ function dci_add_page_metaboxes() {
         if(isset($_GET['post']))
             $curr_page_id = $_GET['post'];
         else if(isset($_POST['post_ID']))
             $curr_page_id = $_POST['post_ID'];
 
         if ( ! isset( $curr_page_id ) ) {
             return;
         }
 
-        $curr_page_id = $_GET['post'];
         $slug = get_post_field( 'post_name', $curr_page_id );

         // Get the name of the Page Template file.
```

**Comment by enrimk** [comment]
Chiuso, ma in realtà, non affrontato e non completato.
Questa chiusura automatica indiscriminata a tempo degli issue è un ottimo modo per perdere traccia dei problemi (e delle soluzioni).
E di disincentivare nei fatti la collaborazione del pubblico.
Davvero un peccato.
