### ISSUE TITLE
Scheda Unità Organizzativa

### ISSUE THREAD

**Issue by nomissor** [italia/design-comuni-wordpress-theme#29]
Volevo sviluppare la scheda per le unità organizzative, a partire dal wireframe presente su Figma https://www.figma.com/file/Kfa8NiMX4BDgJmRZiXxjnY/Siti-Comuni---hi-fi?node-id=0%3A9923

Ho bisogno di alcune delucidazioni.
**1.**
![image](https://user-images.githubusercontent.com/3584477/190597741-ff4a661c-df33-488e-850f-18eb1b0b91a2.png)
a cosa è collegato?

**2.**
![image](https://user-images.githubusercontent.com/3584477/190597646-71fad67d-2feb-47b2-bda0-4ae4f96eb27b.png)
a cosa è collegato?

**3.**
![image](https://user-images.githubusercontent.com/3584477/190598517-9dd907f4-aac2-4b49-b8ba-d4bf4fcdeff1.png)
Suppongo siano il "responsabile" e le "Unità organizzativa genitore"

**4.**
![image](https://user-images.githubusercontent.com/3584477/190597895-887d1e96-033e-47c1-835a-958116fa6fc9.png)
Cosa sono i _luoghi_ o i _punti di contatto_ collegati?
Inoltre la funzionalità richiedi appuntamento non è legata a unità organizzative?

**5.**
Tutti gli altri campi compilati sul BackEnd che non compaiono su questo wireframe, come devono essere gestiti?

**Comment by zetareticoli** [comment]
@nomissor 

le risposte alle tue domande sono nel [documento di Architettura](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit?usp=sharing&ouid=114978373497590601993&rtpof=true&sd=true) 

inoltre il template deve seguire il[ nuovo layout](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/%5BComuni%5D-Modello-sito-e-servizi?node-id=30%3A199476)
