### ISSUE TITLE
Errore da app valutazione

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#290]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Da app di valutazione esce questo errore dove dice che in tutte le categorie le domande di follow up non sono associate a valori corretti. Ho controllato i data-element e risultano corretti; ho provato a utilizzarlo simulando valutazioni e funziona. Cosa potrebbe essere? 
Grazie mille

### Includi link o screenshot

![domande follow up](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/d843dc47-9821-4f6e-bf02-e3f22c0e0f53)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by farapeppe** [comment]
Aggiungo anche che la documentazione dice
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/75178422/a677b441-dd65-49af-af52-bd04e770b2dd)
invece il template mette quel data-element non sul tag <legend> ma sul tag <span> circa 4 righe più sotto.
Spostando il data-element da span a legend l'app di valutazione dà errore su tutte le pagine del sito.
Suggerisco quindi di chiarire quale è il comportamento desiderato e uniformare template, app di valutazione e documentazione.
Sto cercando anche io di risolvere il problema che riscontra @fabricius4 ma noto che ad esempio, il comune di Sedriano non dà questo errore.
https://comune.sedriano.mi.it/

**Comment by farapeppe** [comment]
Interessante notare come il comune di Sedriano
https://comune.sedriano.mi.it/
non presenta questi errori se si lancia l'app di valutazione.
Ma, pur avendo modificato il mio codice della parte relativa ai feedback, per renderlo identico al loro, io continuo a riscontrare lo stesso errore di @fabricius4

**Comment by fabricius4** [comment]
Grazie per avermi contattato. 
    In questo momento siamo chiusi per ferie e rientreremo giorno 23
      agosto. 
    
    A presto.
    
    -- 
Fabrizio Marano Mariosa
INACUS - Istituto Nazionale di Cultura e Solidarietà
Via Galliano, 4/D - 87100 Cosenza
Tel. 0984790333

**Comment by farapeppe** [comment]
Novità? @fabricius4

**Comment by malikmalhan** [comment]
sei riuscito a risolvere? ho lo stesso problema
