### ISSUE TITLE
Errato campo metatag "addressLocality"

### ISSUE THREAD

**Issue by valeriot30** [italia/design-comuni-wordpress-theme#291]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella scheda servizio, l'adressLocality viene assegnato in base al campo "Quartiere" del Luogo specificato, erroneamente.
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/30567406/2e8fda38-6e50-48b4-86a7-37af83cd1ae7)

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/30567406/1fdd2903-18f7-4279-afff-4506eb7840e3)

Qualora l'uso fosse errato, mi scuso nella creazione dell'issue.

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/30567406/e62b2a0c-2537-4f7a-8566-de082df52a9e)

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

ultima versione

**Comment by enrimk** [comment]
Inoltre, `addressLocality` è una delle proprietà che il validatore controlla per l'asseverazione, in pratica è pressoché obbligatorio che ci sia.
[Da specifiche](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/architettura-informazione.html#dati-strutturati-e-interoperabilita), dovrebbe contenere "il nome del comune", non il quartiere.
[Su schema.org, addressLocality](https://schema.org/addressLocality) è definita nel formato di un [indirizzo postale](https://schema.org/PostalAddress).

La cosa che abbiamo che ci può andare più vicina è il codice IPA (che ha un nome ambiguo, "codice", ma in realtà è solo il nome dell'ente). Non è esattamente quello che va in un indirizzo postale però: sarà "Comune di XYZ", mentre serve "XYZ".

Perciò, qui si apre un problema ulteriore: **[nei Luoghi](https://github.com/italia/design-comuni-wordpress-theme/blob/80f7c859163b19a3e8861596a1bca57d1422bf48/inc/admin/tipologie/tipologia_luogo.php#L239), un campo "Comune" manca**.
Anche [il documento di architettura](https://designers.italia.it/files/resources/modelli/comuni/adotta-il-modello-di-sito-comunale/definisci-architettura-e-contenuti/Architettura-informazione-sito-Comuni.ods) non include esplicitamente il Comune, per la Tipologia Luogo cita solo un "indirizzo", testo libero.

È un'omissione strana, ma visto che coinvolge la validazione dei servizi è molto importante; è meglio che apriamo un issue dedicato?

**Comment by zetareticoli** [comment]
Ciao @enrimk , hai ragione in merito al fatto che dovrebbe essere correlato al "Comune" e non "Quartiere". Correggeremo la label nel _back-office_ di Wordpress in una prossima release.

Quello che tu dici in merito alla definizione su _schema.org_ però non è corretta. Riporto qui la frase:
"_The locality in which the street address is, and which is in the region. For example, Mountain View._

Può essere quindi qualsiasi forma testuale di una località.

**Comment by enrimk** [comment]
È vero che il formato "concreto" di addressLocality è un testo libero qualunque, ma intendevo che è usata e definita specificamente come componente di un [PostalAddress](https://schema.org/PostalAddress).
[ServiceChannel ](https://schema.org/ServiceChannel) > [serviceLocation](https://schema.org/serviceLocation)::[Place ](https://schema.org/Place)> [address](https://schema.org/address)::[PostalAddress](https://schema.org/PostalAddress).
Suppongo che abbia senso che il suo contenuto debba "funzionare" in quel contesto, cioè che sia una parte di un indirizzo postale (italiano). 

Strettamente parlando, in effetti il campo che manca sul Luogo probabilmente dovrebbe chiamarsi in modo generico "Località".
