### ISSUE TITLE
Bug nel Front-end quando ad un argomento si associa l'Area di appartenenza e l'Assessorato di riferimento

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#293]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando si associa l'Area di appartenenza e/o l'Assessorato di riferimento ad un argomento appare l'errore come in figura.

![Screenshot 2023-06-29 at 09-43-30 Agricoltura – Comune AGID](https://github.com/italia/design-comuni-wordpress-theme/assets/67457275/d0370422-6698-40d2-8ce2-75630215ce6a)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
Dalla [posizione del warning](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/template-parts/unita-organizzativa/card.php#L13), sembra che sia causato da un Punto Contatto della UO senza "voci". Che sono però obbligatorie, e un PC "vuoto" non è facile da inserire - non da backend almeno.  

Potrebbe anche starci un default per _$voci_ (`$voci=dci_get_meta(...) ?: []`), ma se è così è un po' un caso limite, e alla fine è solo un warning.
