### ISSUE TITLE
I documenti correlati dentro documenti pubblici mostrano sempre lo stesso documento

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#294]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

All'interno della pagina singola dei documenti pubblici non vengono mostrati i documenti pubblici correlati ma sempre lo stesso documento. Quando inserisco i documenti collegati in un documento pubblico invece che mostrare quelli selezionati mostra sempre il documento principale ripetuto tante volte quanti sono i documenti collegati

### Includi link o screenshot

![documento pubblico  duplicato](https://github.com/italia/design-comuni-wordpress-theme/assets/132072881/36f0e2f5-7eda-4475-b58e-4c09ed4e2529)
![documento pubblico  duplicato 1](https://github.com/italia/design-comuni-wordpress-theme/assets/132072881/e66ead8f-8367-4397-bd0b-2ccaf6c1831d)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by Cam-al** [comment]
io l'ho risolto modificando il file single-documento_pubblico.php cosi:

`<?php if($documenti_collegati && is_array($documenti_collegati) && count($documenti_collegati)>0 ) { ?>
                    <article id="documenti_collegati" class="it-page-section anchor-offset mt-5">
                        <h3>Documenti correlati</h3>
                        <div class="card-wrapper card-teaser-wrapper card-teaser-wrapper-equal">
                            <?php foreach ($documenti_collegati as $all_url) {
                                //$all_id = attachment_url_to_postid($all_url);
                                $documento = get_post($all_url);
                                $with_border = true;
                                get_template_part("template-parts/documento/card");
                            } ?>
                        </div>
                    </article>
                    <?php } ?>`

**Comment by enrimk** [comment]
Sì, `$documenti_collegati` è già in origine un array di post ID, e non di url che debbano essere convertiti in post.
Nel loop si ha sempre un `get_post(null)`, cioè sempre il documento corrente.

Aggiungo, per completezza, che documento/card non usa `$with_border`, che quindi si può togliere. [^1]
[^1]: E che funziona anche perché `$documento` è già implicitamente una global, perché siamo in un template di primo liv., single-*, che è eseguito nello scope globale. Dunque per passare la variabile a documento/card (che appunto se la aspetta come global), basta istanziarla.

Una patch un po' più chiara può essere questa: https://github.com/italia/design-comuni-wordpress-theme/compare/main...enrimk:design-comuni-wordpress-theme:patch/issue294
