### ISSUE TITLE
Redirect alla home per gli archivi di alcune tassonomie

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#297]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella sezione "Esplora per categoria" della pagina Novità o Documenti e Dati sono elencati i termini delle rispettive tassonomie.

Cliccando su questi link non si apre la pagina di archivio della tassonomia ma si viene ridirezionati alla home, mentre altri archivi di tassonomia vengono visualizzati correttemente (es. argomenti). Ho provato ad aggiungere il controllo anche nel file taxonomy.php ma senza successo. C'è qualche funzionalità nel tema che fa questo redirect?

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by michmeno** [comment]
Ci sono diversi file da modificare.  C'è già una Issue per le Novità #16, mentre per Documenti e dati puoi guardare la Pull request #252
