### ISSUE TITLE
Punti di contatto senza dati lato frontend

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#3]
Buongiorno,
Ho inserito dei punti di contatto e quando cerco di visualizzare il punto di contatto lato frontend, viene mostrato solo il titolo, senza dati.

![punto-di-contatto](https://user-images.githubusercontent.com/3976174/182308085-e2f0c9a0-3223-45fa-820f-58d83e991107.png)

WordPress 6.0.1
Tema "Design Comuni Italia" v.1.0.1
PHP 7.4.26

**Comment by zetareticoli** [comment]
Ciao @mariantanase ,

il _content-type_ Punto di Contatto non avrà mai una vista dedicata, in quanto serve per essere collegato ad altri _content-type_. Sappiamo che da _backoffice_ viene comunque prevista la possibilità di visitare una URL pertanto capiremo se inibire questa _feature_ solo per questo _content-type_.

**Comment by enrimk** [comment]
> il _content-type_ Punto di Contatto non avrà mai una vista dedicata [...]

Lo pensavo anch'io, ma allora come mai la PR #254 che aggiunge [un link al dettaglio](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/single/punto-contatto.php#L26)?

E anche [nella card](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/punto-contatto/card.php#L22) c'è un link abbozzato (tag `<a>` non funzionante).

**Comment by enrimk** [comment]
[Anche qui](https://github.com/italia/design-comuni-wordpress-theme/issues/156#issuecomment-1427638300) mi sembra che venga confermato che la vista dettaglio del Punto Contatto non dovrebbe esistere.

Per evitare confusioni, meglio correggere [la definizione del content type](https://github.com/italia/design-comuni-wordpress-theme/blob/main/inc/admin/tipologie/tipologia_punto_contatto.php)?

E oltre al Contatto, anche l'Incarico immagino che non abbia una vista propria.
