### ISSUE TITLE
Cambio colore del Tema

### ISSUE THREAD

**Issue by carmeloimpusino** [italia/design-comuni-wordpress-theme#30]
In che modo è possibile variare il colore del Tema?

**Comment by nomissor** [comment]
Per iniziare a personalizzare i colori, fai riferimento a https://github.com/italia/bootstrap-italia-playground

Poi però ci sono alcune regole CSS nel file comuni.css che vanno modificate o sovrascritte.

Anche per questo motivo ho modificato il tema padre  per renderlo estendibile con un tema child.

Se esistesse anche la versione SASS per il file comuni.css sarebbe la cosa migliore.

**Comment by zetareticoli** [comment]
Ciao @carmeloimpusino,
le indicazioni di @nomissor sono corrette.

Il file sorgente del CSS è disponibile sul repository [design-comuni-pagine-statiche](https://github.com/italia/design-comuni-pagine-statiche/tree/main/src/stylesheets), questo repo eredita solo il file compilato.

**Comment by sviluppoRobyone** [comment]
Buongiorno,
chiediamo di implementare nella documentazione (sezione personalizzazione), tali indicazioni per fornire tutte le indicazioni in modo chiaro a chi volesse personalizzare il tema.
Fino al ritrovamento di questa issue non era assolutamente chiaro come trovare le sorgenti del file comuni.css
