### ISSUE TITLE
La funzione get_page_by_title è deprecata

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#301]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

In diversi file dentro template-parts si utilizza la funzione get_page_by_title che è deprecata dalla versione 6.2.0 come riportato anche nell'errore 
Deprecated: La funzione get_page_by_title è deprecata dalla versione 6.2.0! Utilizza al suo posto WP_Query. in /var/www/vhosts/modelloagid.it/httpdocs/wp-includes/functions.php on line 5413
Nella pagina vivere il comune è presente sia per la sezione eventi in evidenza che per i luoghi in evidenza, io ho risolto semplicemente cancellando le seguenti righe:

$url_eventi = get_permalink( get_page_by_title('Eventi') );
dentro "template-parts/vivere-comune/eventi.php"

$url_luoghi = get_permalink( get_page_by_title('Luoghi') );
dentro "template-parts/vivere-comune/luoghi.php"

sembra stia funzionando tutto, non ho capito dove veniva utilizzato.

lo stesso errore è presente anche in altre pagine potrebbe essere lo stesso

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by abmcr** [comment]
https://github.com/italia/design-comuni-wordpress-theme/issues/229

**Comment by Cam-al** [comment]
@abmcr grazie, non ho capito per cosa lo utilizza nella pagina di vivere il comune? 
Non ho trovato da nessuna parte "$url_eventi",  io l'ho commentato come indicato su e non ho avuto problemi continua a funzionare tutto. Ho sbagliato?

**Comment by abmcr** [comment]
leggi la mia issue

**Comment by Cam-al** [comment]
letta ! ma non capisco a cosa serve  la funzione get_page_by_title nei file "/vivere-comune/eventi.php" e "/vivere-comune/luoghi.php"

**Comment by abmcr** [comment]
a prendere l'ID della pagina passata come argoimento e a farne il linkl

**Comment by Cam-al** [comment]
ok, ma non mi sembra venga utilizzato in vivere il comune, anche perché utilizza `get_template_part("template-parts/evento/card-full");` e all'interno del template usa `get_term_link($tipo_evento->term_id)` per recuperare il link del post

**Comment by enrimk** [comment]
Infatti `$url_eventi` e `$url_luoghi`, _nella versione attuale_ dei due template, non sono usati. 
Immagino che fossero stati pensati per i [link a "tutti i luoghi"](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/template-parts/vivere-comune/luoghi.php#L23) e "[tutti gli eventi](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/template-parts/vivere-comune/eventi.php#L23)", che però adesso sono incompleti (`href="#"`).

L'idea evidentemente era anche di usare delle pagine, e dei template di pagina, per quei due archivi.  
Questa a mio avviso non è l'idea migliore, visto che non sembra che abbiano bisogno di una pagina a cui legarli (per cosa? Opzioni speciali? non mi pare).
È più che sufficiente fare due viste "automatiche" con due template archivio (_archive-evento.php_ e _archive-luogo.php_). Il cui url è `get_post_type_archive_link('evento')`, e il valore è preso [da qui](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/tipologie/tipologia_evento.php#L31), c'è già. Bisogna però abilitare `has_archive => true` nella dichiarazione delle due tipologie, che stranamente ora è `false`. 

Si può fare anche in altro modo; io nella mia implementazione ho fatto così.

Quindi in sostanza: _molto probabilmente_ qui `get_page_by_title()` è inutile e può essere tolta, ma di fatto dipende da come verranno implementate le parti che ancora mancano dentro a _Vivere il Comune_.

**Comment by Cam-al** [comment]
S, anche io ho fatto allo stesso modo
