### ISSUE TITLE
Undefined array key "testo_message" nella home

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#302]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella sezione dedicata ai messaggi o avvisi di allerta quando non è impostato nulla o viene rimosso un avviso compare il seguente errore :

Warning: Undefined array key "testo_message" in /var/www/vhosts/modelloagid.it/httpdocs/wp-content/themes/design-comuni-wordpress-theme-1.7.1/template-parts/home/messages.php on line 5

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
```diff
--- a/template-parts/home/messages.php
+++ b/template-parts/home/messages.php
@@ -5,2 +5,2 @@
-    if(trim($message['testo_message']) == "") continue;
+    if ( empty($message['testo_message']) || trim($message['testo_message']) == "" ) continue;
     $message_date = strtotime($message['data_message'] ?? '');
@@ -13,2 +13,2 @@
             <p class="msg">
-                <?php if($message['icona_message']): ?>
+                <?php if ( !empty($message['icona_message']) ): ?>
@@ -21,2 +21,2 @@
                 <?php echo nl2br($message['testo_message']) ?>
-                <?php if($message['link_message']): ?>
+                <?php if ( !empty($message['link_message']) ) : ?>
```
