### ISSUE TITLE
realizzare template mancanti

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#304]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Sto provando a realizzare i template mancanti, ma non riesco a capire qual è il metodo corretto per  procedere.
Normalmente avrei creato un file "single-(nome post type).php" per fare il template delle singole pagine e un file "archive-(post type).php" per fare l'archivio, ma ho notato che quasi tutti i post type nel file di definizione (inc/admin/tipologie/...) hanno impostato: `'has_archive'      => false,` 
C'è un motivo in particolare per il quale è stato scelto di impostarlo cosi?
ho provato a modificarlo con true e a creare un file archive-nome post type.php ma non funziona.
Per esempio ho provato a fare l'archivio degli eventi chiamandolo archive-evento.php non ha funzionato ho provato a cambiare con archive-eventi.php ma nulla, non funziona comunque.

come fanno a funzionare archive-argomento.php o archive-servizio.php se nelle impostazioni hanno `'has_archive'      => false,` ?

Questo mi sembra il metodo più veloce per fare i template mancanti.
oppure devo creare un file template che poi applico a una pagina che creo su Wordpress? come è stato fatto per altre pagine.

poi vorrei capire che aspetto dare ai template che ancora non sono rilasciati per il modello, è sufficiente rispettare lo stile del sito o ci sono altre restrizioni particolari? 
A che punto è lo sviluppo e integrazione dei template mancanti nel tema? era stato detto che entro il primo quadrimestre del 2023 verranno rilasciati

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by Cam-al** [comment]
è possibile che il tema child non riesca a sovrascrivere i file dentro la cartella inc ?
dovrei modificare il tema principale per farlo funzionare, o ci sono alternative.
queste genere di modifiche sarebbe meglio averle direttamente nel tema  per non doverle applicare a ogni aggiornamento

**Comment by danieledexter** [comment]
Anche io nel tema child avevo provato a fare delle modifiche ad alcuni di questi file,  mi sono trovato nella tua stessa situazione.
Ho quindi modificato il tema padre, ma questo non va bene in caso di aggiornamenti.
Se qualcuno ha la soluzione più corretta per farlo sarebbe ottimale.

Io avevo pensato di confrontare eventuali modifiche aggiuntive del tema padre e di fare il merge di solo quello che mi interessava.

**Comment by michmeno** [comment]
public e has archive diventano true, poi devi modificare anche il file taxonomy.php

**Comment by michmeno** [comment]
@Cam-al il tema child non sovrascrive i file dentro la cartella inc. (puoi farlo nella root principale e nelle cartelle template-parts e page-templates).
Sei riuscito a fare il template eventi?

**Comment by Cam-al** [comment]
Ah ok grazie, si lo sto facendo. Ho modificato direttamente il tema originale per abilitare l'archivio, ora mi sono bloccato per capire che struttura dargli, non essendoci un template statico da seguire su cosa mi baso?
sicuramente la solita struttura ci deve essere ma per il contenuto non so come organizzarlo

- header
- hero
- (contenuto)
- valuta servizio
- assistenza contatti
- footer

nel contenuto devo mostrare di nuovo gli eventi in evidenza oppure no, poi sotto metto l'elenco degli eventi mostrando prima quelli più recenti, ma non so se fare una griglia con la barra di ricerca come per le notizie e servizi con il tasto carica altri risultati oppure se fare una griglia con le pagine sotto per scorrere (così [lista-risorse.html](https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse.html) ).

Sai se la barra di ricerca è obbligatoria ?

**Comment by michmeno** [comment]
qui trovi tute le indicazioni: https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/index.html

**Comment by zetareticoli** [comment]
Chiudo questo thread in quanto non si tratta di una issue con il prodotto. Potete continuare discussione sul [canale Slack](https://developersitalia.slack.com/archives/CME9AD8NN).

**Comment by Cam-al** [comment]
scusa ma non ho capito perché non riguarda il prodotto? é comunque un problema il fatto che gli archivi sono disattivati su quasi tutti i tipi di posti e tassonomie, a ogni aggiornamento è necessario inserire nuovamente le modifiche.
Devo aprire un nuovo problema, senza tutto il resto delle conversazione?

**Comment by zetareticoli** [comment]
@Cam-al nella descrizione del "problema" sono state poste domande giuste, ma aperte più ad un confronto. Il canale Slack è il luogo più adatto per questo tipo di comunicazione.

Diverso è aprire una issue in cui si indica un bug o una richiesta specifica che deve essere presa in carico.

**Comment by Cam-al** [comment]
Ah ok, grazie, si volevo pubblicarlo su Slack ma non riesco a creare un account. Mi dovrebbe arrivare un codice ma non arriva

**Comment by Vingithub2020** [comment]
Salve, ho anche il il problema che lei ha descritto, volevo capire se ha trovato i template tipo Aree Amministrative in formato php ecc..  Grazie mille per la risposta
