### ISSUE TITLE
R.SI.1.1 - METATAG - Nel sito comunale, le voci della scheda servizio devono presentare i metatag descritti dal modello, in base agli standard internazionali.

### ISSUE THREAD

**Issue by fnori77** [italia/design-comuni-wordpress-theme#309]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Non riusciamo a capire quale sia il problema. Grazie.

### Includi link o screenshot

<img width="803" alt="Screenshot 2023-07-13 alle 15 17 09" src="https://github.com/italia/design-comuni-wordpress-theme/assets/126147260/65bef65b-40b4-4f8b-820f-c9ed48329d24">

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.5

**Comment by mariantanase** [comment]
Lo stesso comportamento anche qui #226

**Comment by zetareticoli** [comment]
Ciao @fnori77 , nella [documentazione](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/conformita/conformita-modello-sito.html#raccomandazioni) trovi qualche dettaglio in più su come impostare i `metatag`

**Comment by michmeno** [comment]
L'errore viene generato perchè l'app verifica campi facoltativi anzichè quelli obbligatori.

Nella pagina del singolo servizio i campi sono questi:
- Uffici (canale fisico)
- Codice dell'Ente Erogatore (IPA)
- Copertura geografica
- Introduzione canale digitale
- Canale digitale

Poi va compilato il campo "Quartiere" nel Luogo di riferimento dell'ufficio che offre il servizio.

**Comment by lucafranco74** [comment]
Buongiorno, io ho inserito tutti i campi possibili ma rimane l'errore per il metatag availableChannel.serviceLocation.address.addressLocality. Lato WP Admin non ci sono campi che fanno riferimento ad una località, qualcuno sa darmi qualche informazione utile? Grazie

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/126711265/a8a10c06-4878-4c21-9827-10ad8cbf3510)

**Comment by fnori77** [comment]
Ciao, dovrebbe essere inerente al campo Uffici (canale fisico) della scheda servizio. Richiede la compilazione.

**Comment by lucafranco74** [comment]
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/126711265/ba9c2175-907f-4115-9865-cbf1caf6b080)

è valorizzato il campo, l'ufficio anagrafe l'ho inserito sotto Unità Organizzative

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/126711265/71dfc0ba-ee89-4a69-ad32-6d1f09dd3395)

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/126711265/f18ba637-4691-4a56-b54b-7053ffcc2e76)

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/126711265/43708b0b-cb04-492b-a03a-83d775cd310a)

Penso di aver inserito tutti i campi, ma continua a dare questa difformità

**Comment by enrimk** [comment]
L'indirizzo del Luogo _Municipio_ ha il _quartiere_?
Altrimenti, niente validazione. 🙁

**Comment by lucafranco74** [comment]
Grazie, mille ho risolto inserendo il quartiere!!
