### ISSUE TITLE
Richiesta comuni.css NON minificato

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#313]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ritorno con una richiesta fatta tempo fa in un altro topic ma senza riscontro.
E possibile fornire il file `comuni.css` non-minificato ?

Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by zetareticoli** [comment]
Ciao @mariantanase , la scelta di non includere in questo repository il file `src` è stata dettata dalla necessità di non frammentare la manutenzione dello stesso codice in più posti.

Il file `comuni.css` (che contiene delle personalizzazioni rispetto a `bootstrap-italia-comuni.min.css`) è disponibile nel repository [design-comuni-pagine-statiche](https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/stylesheets/styles.scss).

Prevediamo di ripulire questo _stylesheet_ in quanto tutto il tema dovrebbe essere gestito centralmente dal file proveniente dalla libreria Bootstrap Italia.

**Comment by mariantanase** [comment]
Ottima notizia @zetareticoli !

**Comment by enrimk** [comment]
Credo che manchi la versione non minificata di [assets/js/load_more.js](https://github.com/italia/design-comuni-wordpress-theme/blob/main/assets/js/load_more.js).
Vedo che è stato compresso in #101 , ma dentro ad assets-src/js l'originale non c'è.
Fa parte della distribuzione del tema, non di un componente esterno, vero?
Gli altri js vengono tutti da librerie?

**Comment by mariantanase** [comment]
> Ciao @mariantanase , la scelta di non includere in questo repository il file `src` è stata dettata dalla necessità di non frammentare la manutenzione dello stesso codice in più posti.
> 
> Il file `comuni.css` (che contiene delle personalizzazioni rispetto a `bootstrap-italia-comuni.min.css`) è disponibile nel repository [design-comuni-pagine-statiche](https://github.com/italia/design-comuni-pagine-statiche/blob/main/src/stylesheets/styles.scss).
> 
> Prevediamo di ripulire questo _stylesheet_ in quanto tutto il tema dovrebbe essere gestito centralmente dal file proveniente dalla libreria Bootstrap Italia.

Ciao @zetareticoli 
Ci sono aggiornamenti in merito a questa informazione ? E' passato quasi un anno...
Grazie

**Comment by zetareticoli** [comment]
Ciao @mariantanase, il file sorgente (non minificato) è da noi gestito sul repo dei templates statici, per motivi di semplificazione.

Nulla vieta però di scaricarsi quel sorgente e aggiungerlo alla propria installazione, riscrivendo il processo di build della risorsa.
