### ISSUE TITLE
Errore visualizzazione elenchi puntati

### ISSUE THREAD

**Issue by stefanoianna** [italia/design-comuni-wordpress-theme#314]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel file **comuni.css**, al tag **a** viene assegnata la proprietà "display: inline-block;". Tuttavia, questa proprietà fa si che gli elenchi puntati contenenti link vengano visualizzati male.

### Includi link o screenshot

![Screenshot 2023-07-17 at 10-09-54 Contributi per il sostentamento di persona singola o nucleo familiare – Comune AGID](https://github.com/italia/design-comuni-wordpress-theme/assets/67457275/3a54bb43-9a22-4cb1-9b94-f037cf15b88f)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Se i problemi di comuni.css sono pertinenza di [design-comuni-pagine-statiche](https://github.com/italia/design-comuni-pagine-statiche/) (secondo [quanto si diceva qui](https://github.com/italia/design-comuni-wordpress-theme/issues/313#issuecomment-1635896950)), segnaliamo su quel progetto? 

La regola in oggetto [sembra essere stata aggiunta qui](https://github.com/italia/design-comuni-pagine-statiche/commit/dfd2414769493cd3fe6a2232d14d43c135899dad). A giudicare dal titolo della commit, per correggere qualche problema sul bordo dell'outline negli stati :focus? Non ci sono molti dettagli nei messaggi, difficile avere un'idea precisa. 
Ad ogni modo, probabilmente il selettore `a` qui è un po' troppo generico.

**Comment by zetareticoli** [comment]
@enrimk esatto, le segnalazioni in merito al file `comuni.css` va aperto sul repo `design-comuni-pagine-statiche` perché il tema WP eredita la versione minificata.

@stefanoianna potresti aprire questa issue su quel progetto? Grazie
