### ISSUE TITLE
Errore Deprecated: Required parameter nella versione 1.7.2

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#315]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo l'aggiornamento alla versione 1.7.2  sono apparsi nella parte alta di tutte le pagine i seguenti errori:

Deprecated: Required parameter $field follows optional parameter $field_name in /var/www/vhosts/modelloagid.it/httpdocs/wp-content/themes/design-comuni-wordpress-theme-1.7.2/inc/lib/CMB2-field-Leaflet-Geocoder/cmb-field-leaflet-map.php on line 140

Deprecated: Required parameter $field_escaped_value follows optional parameter $field_name in /var/www/vhosts/modelloagid.it/httpdocs/wp-content/themes/design-comuni-wordpress-theme-1.7.2/inc/lib/CMB2-field-Leaflet-Geocoder/cmb-field-leaflet-map.php on line 140

Deprecated: Required parameter $field_type_object follows optional parameter $field_name in /var/www/vhosts/modelloagid.it/httpdocs/wp-content/themes/design-comuni-wordpress-theme-1.7.2/inc/lib/CMB2-field-Leaflet-Geocoder/cmb-field-leaflet-map.php on line 140

Deprecated: Required parameter $field_type_object follows optional parameter $field_escaped_value in /var/www/vhosts/modelloagid.it/httpdocs/wp-content/themes/design-comuni-wordpress-theme-1.7.2/inc/lib/cmb-field-select2-master/cmb-field-select2.php on line 83

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Partendo da quale versione del tema hai eseguito l'aggiornamento?
Questi warning in realtà erano già presenti da prima dell'ultima versione, sono relativi a un modulo della libreria CMB2 che è lì da sempre (e non modificato almeno da marzo, v1.6.2, #198 ).

Tra parentesi, sono warning di livello abbastanza secondario e probabilmente non molto utili per un test "pratico" del tema.
Qual è la tua impostazione di [error_reporting](https://www.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) in php.ini? Può darsi che convenga aggiungere un ~E_DEPRECATED. [a meno che non ci sia anche qualcos'altro nell'app che interviene dopo, ad alzare a sua volta il livello di paranoia degli avvisi]

Se in wp-config.php hai WP_DEBUG a true, considera di attivare [WP_DEBUG_LOG](https://wordpress.org/documentation/article/debugging-in-wordpress/#wp_debug_log) e disattivare WP_DEBUG_DISPLAY. 
I notice php non sono fatti per essere visualizzati su schermo frammisti al codice dell'app, andrebbero registrati e consultati nei log.
Questo è ancora più importante in certi contesti, come le chiamate AJAX e il JSON in genere, dove una piccola alterazione può rendere tutto sintatticamante invalido e far fallire l'intera operazione.
Vedo altri issue aperti di recente (#316, #317) che potrebbero far pensare a una situazione del genere.

**Comment by enrimk** [comment]
Questi altri warning sono causati da un plugin, e anche qui probabilmente è da un po' che ci sono, a meno che tu non l'abbia aggiornato proprio adesso.   
Purtroppo l'"ecosistema" dei plugin, temi ecc. di WordPress è quello che è, non ci si deve aspettare sempre grande precisione: warning, notice, e ogni tanto qualche errore anche più grave sono all'ordine del giorno. Anche per questa ragione non è consigliabile tenere error_reporting "tutto acceso", o display_errors sempre attivo, neanche in fase di test. Qualche notice, da qualche fonte, ci sarà quasi sempre. E se sono resi visibili in mezzo all'html, o al json, js, ecc., è facile che siano i notice stessi a rompere ulteriormente le cose, invece di rendere un servizio.

**Comment by Cam-al** [comment]
Si questi warning ci sono praticamente da sempre ma non sono un problema perché tutto sembra funzionare e una volta completato il sito toglierò il debug e non si vedranno più. Diverso è il problema degli errori del tema che vengono mostrati a schermo che probabilmente non sono nemmeno collegati ai malfunzionamenti che ho riscontrato. Vorrei capire se fa cosi a tutti o solo a me? non e solo un problema di visualizzazione errori (cosa che posso risolvere disabilitando il debug se non è necessario risolverli) ma proprio di funzionamento, non posso più vedere e caricare i media e non funziona più il tasto "carica altri risultati"

**Comment by enrimk** [comment]
Io il problema non lo riscontro, quindi sospetto che sia collegato al tuo setup.
Sospetto anche che la visualizzazione a schermo degli errori dopotutto qualcosa c'entri. Se il warning venisse visualizzato in mezzo al risultato di una chiamata ajax, tipo quelle che avvengono per il caricamento dei media o dei risultati delle ricerche, i dati non sarebbero più interpretabili e l'aggiornamento della pagina ovviamente si bloccherebbe.

Sottolineo che non è molto utile tenere il debug visibile in test, perché non è la condizione normale di esercizio (spero bene che in produzione php non l'avrà), e dunque come test è un po' falsato. Debug attivo, bene, ma registrato in un log.

**Comment by enrimk** [comment]
Il debug io l'ho sempre attivo, ma non visibile nell'html. Basta leggere wp-content/error.log: più semplice e sicuro.
Per curiosità ho attivato WP_DEBUG_DISPLAY come probabilmente avrai tu: come facilmente intuibile, si rompe tutto: l'upload non funziona, ecc.
Ma non è che è _garantito_ che si debba rompere: è semplicemente un setup fragile, esposto a mille variabili poco cotrollabili. Non la condizione ideale per dei test.

Rischi di essere sommerso dai falsi positivi: almeno l'imita l'output agli E_ERROR.

**Comment by Cam-al** [comment]
Ti ringrazio per l'aiuto, mi chiedo come abbia fatto a non darmi problemi per tutto questo tempo. provvederò a rimuovere il debug, grazie

**Comment by zetareticoli** [comment]
Ciao @Cam-al ,abbiamo fatto un controllo sugli errori da te citati e non li abbiamo riscontrati.
