### ISSUE TITLE
Dopo l'aggiornamento 1.7.2 problema nel caricamento e visualizzazione media

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#317]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo l'aggiornamento alla versione 1.7.2 ho problemi con i media.
non riesco più a caricare qualsiasi tipo di file e non riesco nemmeno a visualizzare quelli già caricati, se vado nella sezione media continua a caricare ma senza mostrare nulla 

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by zetareticoli** [comment]
Ciao @Cam-al, non riscontriamo il problema da te segnalato. Potresti aggiungere qualche informazione in più (es. screen)?
