### ISSUE TITLE
Dopo l'aggiornamento alla 1.7.2 voci del menu Argomenti duplicate

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#318]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo l'aggiornamento alla 1.7.2 le voci del menu "Argomenti" sono duplicate, ho dovuto cancellarle manualmente per farle tornare come prima.
Ho avuto troppi problemi con questa versione sono dovuto tornare alla precedente, non so se è stato solo un problema mio ma cosi il sito era inutilizzabile.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by zetareticoli** [comment]
Anche in questo caso, non riscontriamo il problema delle voci di menu duplicate.
