### ISSUE TITLE
Errore XAMPP e versione PHP >= 8

### ISSUE THREAD

**Issue by dadah3** [italia/design-comuni-wordpress-theme#319]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho installato localmente con XAMPP Wordpress con le scuole di design del tema. Viene visualizzato un errore quando provo ad aprire la finestra panoramica della scuola. Lo stesso è successo a me tempo fa riguardava la versione di php utilizzata dalla 8 in poi. Mi sembrava che l'errore fosse stato corretto. Come dovrei fare? cambiare php e rimanere alla versione inferiore a 8? o c'è qualcos'altro da fare?

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

l'ultima

**Comment by zetareticoli** [comment]
Ciao @dadah3 , questo è il repository dedicato al modello per i comuni.
