### ISSUE TITLE
 C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA 

### ISSUE THREAD

**Issue by tommaso326** [italia/design-comuni-wordpress-theme#321]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Sto lavorando su 2 siti in contemporanea. Sono identici, uno la copia dell'altro, in quanto il secondo è stato clonato dal primo. L'unica cosa in cui differiscono sono i dati inseriti.
Nell'originale, quello di partenza, sto riscontrando l'errore alla voce 1.2, in allegato uno screen fatto durante la validazione.
Nel clone l'errore non sussiste.
Nel report dell'originale, l'app di validazione trova la libreria in homepage ma non trova almeno una classe CSS di quelle indicate nella documentazione. Tuttavia, alla voce "Versione in uso", viene riportata la versione della libreria tra virgolette, cosa che non succede nelle altre pagine analizzate (screenshot in allegato).

versione app di valutazione: 2.5.1
versione wp: 6.2.1
versione tema: 1.6.2

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/139881085/1095f77e-58ca-4b6c-b5f3-665e66156b24)
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/139881085/657a45b6-6f0f-4e7d-8b5b-9543a8d12329)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by tommaso326** [comment]
@enrimk Ho apportato le modifiche che hai menzionato, ma non mi è chiara una cosa. Come compilo il progetto per renderlo un file eseguibile .exe su VSC ?

**Comment by enrimk** [comment]
A dire il vero, a compilare il validatore in un exe non ci ho provato. Non dovrebbe essere necessario però: è un applicativo node.js, può essere eseguito anche "spacchettato", dopo una build seguendo le procedure descritte nel Readme.
Con le ultime versioni, sinceramente, io ho avuto qualche problema con le dipendenze tra pacchetti npm che non ho avuto tempo di risolvere, quindi ho sperimentato solo fino a un paio di versioni fa.

Comunque non saprei se modificare il validatore ti serve realmente... hai poi provato con la nuova versione del tema?
