### ISSUE TITLE
Il template di questa pagina non è ancora disponibile

### ISSUE THREAD

**Issue by AndTod28** [italia/design-comuni-wordpress-theme#326]
### Prerequisiti

- [x] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [ ] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ragazzi buon pomeriggio, ho installato il tema 1.7.2 dei comuni, con l'ultima versione di Wordpress (6.2), con php 7.4, ma non mi funziona nulla, entrando nelle pagine mi dice sempre "Il template di questa pagina non è ancora disponibile", qualcuno saprebbe aiutarmi gentilmente?

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/139989302/6a28c303-1499-4175-bfc7-5e25c6ad232c)

### Su quale sisitema operativo stai riscontrando il problema?

Qualsiasi

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by Cam-al** [comment]
Ciao, se hai trovato questo messaggio in alcune pagine è perché il template per visualizzare i contenuti non è stato ancora realizzato, per farlo funzionare è necessario realizzare da se i template, puoi riprendere i template già esistenti e modificarli per completare quelli mancanti. Purtroppo non si sa ancora quando e se verranno rilasciati.

**Comment by AndTod28** [comment]
Ciao, grazie per la risposta, non mi ero accorto che non erano selezionati i template per le pagine di default (amministrazione, servizi, vivere il comune ecc..), siccome nella 1.7.1 erano selezionati di default non ci avevo pensato subito.

Grazie ancora, gentilissimo.

**Comment by enrimk** [comment]
Vedi: #393
