### ISSUE TITLE
Elenco tipologie di Eventi e Tipologie di luogo

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#329]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

alla pagina 
https://wp-dev1.ecohmedia.com/tipi_evento/evento-religioso/
dovrei vedere l'elenco degli eventi della tipologia Evento religioso, invece vedo i contenuti presenti in HOME PAGE.

IDEM PER
https://wp-dev1.ecohmedia.com/tipi_luogo/architettura-residenziale/
dovrei vedere l'alenco delle tipologie di Luogo e i invece vedo i contenuti presenti in HOME PAGE.

Inoltre se in VIEVRE IL COMUNE cliccco su TUTTI GLI EVENTI o TUTTI I LUOGHI, non succede nulla.
MI aspetterei di vedere l'lenco degli EVENTI o dei LUOGHI.

### Includi link o screenshot

[](url)
![mouse-sopra-a-tutti-gli-eventi](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/49c29a24-87cb-4e2f-930d-340cc0d332d7)
![la-url-non-visualizza-elenco-architeture](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/44b321ef-6efc-4afb-aa51-9c906e2ccdb0)
![la-url-non-visualiza-elenco-eventi](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/0e2610fb-8707-4d1c-9cc0-01bc0ccd1e34)

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2.

**Comment by enrimk** [comment]
Sì, mancano i template di tassonomia.
[taxonomy.php](https://github.com/italia/design-comuni-wordpress-theme/blob/3f3cfca912a2faa1b1c9f33b654560212a16098f/taxonomy.php) ora fa altro (e così è inutile, v. #328), e non c'è né un taxonomy-tipi_evento.php né taxonomy-tipi_luogo.php.
Inoltre, gli archivi sono proprio esplicitamente disattivati, nella definizione dei tipi: sia [per i luoghi](https://github.com/italia/design-comuni-wordpress-theme/blob/3f3cfca912a2faa1b1c9f33b654560212a16098f/inc/admin/tassonomie/tassonomia_tipi_luogo.php#L28) che [per gli eventi](https://github.com/italia/design-comuni-wordpress-theme/blob/3f3cfca912a2faa1b1c9f33b654560212a16098f/inc/admin/tassonomie/tassonomia_tipi_evento.php#L28) (oltre che, mi pare, per quasi tutti gli altri tipi). 

Mi chiedo se sia cosi per design, o se è solo perché il progetto è ovviamente un _work in progress_. Immagino la seconda, perché dopotutto sono linkati, qualcosa in quel punto ci vorrà.

Non mi sembra che tra le pagine statiche ci sia un template apposta, ma probabilmente va bene una qualche variante di [Lista Risorse](https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse-categorie.html). Magari senza sez. _In Evidenza_ (almeno per Luoghi ed Eventi, perché c'è già in Vivi Comune). E senza lista Categorie, visto che si è già dentro a una (a meno che non si voglia una navigazione "trasversale"). Il caso specifico non lo trovo citato nella docum. tecnica, ma spero in un po' di elasticità. Tra parentesi, "In Evidenza" in generale è facoltativo, vero?

**Comment by enrimk** [comment]
Vedo che c'è già una discussione aperta a riguardo in #16 e #297 .

**Comment by zetareticoli** [comment]
Chiudo perché duplicato di altre issues.
