### ISSUE TITLE
Elemento </li> di troppo in tutte le voci di menu

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#33]
Noto che sulla view-source html del tema in tutte le voci di menu presenti viene generato un elemento di chiusura elenco di troppo </li>. Da cosa dipende?

**Comment by zetareticoli** [comment]
Ciao @garagiu, potresti essere più specifico e magari aggiungere screen o _source code_ interessata?

**Comment by garagiu** [comment]
ecco lo screen di una parte del menu nel footer
![Immagine 2022-09-19 155736](https://user-images.githubusercontent.com/26837134/191035873-6442f04e-869b-4767-bde3-58adf6623963.png)

**Comment by mariantanase** [comment]
Confermo

**Comment by zetareticoli** [comment]
@garagiu @mariantanase 
Non sono riuscito a replicare il bug, guardando infatti il footer del tema sembra tutto a posto (allego screen)
![footer](https://user-images.githubusercontent.com/69706/191208674-48f155aa-1974-4d22-9cd8-e1a9b055f178.png)

Nel tuo caso hai apportato qualche modifica al template?

**Comment by garagiu** [comment]
No non ho apportato modifiche al template. 
Ho due installazioni in cui uso questo template e il comportamento è simile.
In effetti se verifico con gli strumenti di sviluppo del browser, non vedo questa anomalia, ma quando faccio il view-source della stessa pagina rilevo quel tag di chiusura in più come nella schermata che ho allegato sopra

**Comment by mariantanase** [comment]
> No non ho apportato modifiche al template. Ho due installazioni in cui uso questo template e il comportamento è simile. In effetti se verifico con gli strumenti di sviluppo del browser, non vedo questa anomalia, ma quando faccio il view-source della stessa pagina rilevo quel tag di chiusura in più come nella schermata che ho allegato sopra

Essatto! Solo in view-source compare il tag di chiusura. Molto strano!

**Comment by zetareticoli** [comment]
Anche il validatore HTML del W3C trova questo doppio `</li>` in chiusura. Verifichiamo e in caso fixiamo. 👍
