### ISSUE TITLE
Ordinamento delle persone pubbliche appartenenti ad un'Unità organizzativa

### ISSUE THREAD

**Issue by FrancescaFrigerio** [italia/design-comuni-wordpress-theme#333]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarebbe utile poter ordinare le persone pubbliche che appartengono ad un'unità organizzativa non solo tramite ordine cronologico, ma selezionando l'ordine che si vuole dare alle persone.
Lato backend il template sembra consentire di ordinare le persone pubbliche selezionate, in quanto è possibile trascinare i nominativi delle persone appartenenti alla struttura
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/112412456/f5c6a4ce-1332-464d-97c4-23714ed95799)
Tuttavia, una volta salvate le modifiche, lato front-end le persone pubbliche sono visualizzate solo in ordine alfabetico:
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/112412456/4e563497-98b9-4f05-9ec3-30e34d3364fb)

### Motivazione e contesto

Secondo quanto emerso con il confronto con alcuni enti comunali, risulterebbe molto utile per loro poter scegliere l'ordinamento secondo cui mettere le persone pubbliche facenti parte di un'Unità organizzativa, in particolar modo nei casi di giunta e consiglio, in cui vorrebbero poter ordinare i membri in ordine di importanza e non in ordine cronologico.

**Comment by enrimk** [comment]
Per curiosità, che template stai usando per unita_organizzativa?
Perché "ufficialmente" il dettaglio della UO non mi sembra che sia incluso nella vers. attuale del tema.
Inoltre, [il mockup](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/Comuni---Modello-sito-e-servizi?type=design&node-id=30-200132&mode=dev) ha la lista Persone come serie di card, non di tag.

**Comment by mariantanase** [comment]
Hai provato a cambiare manualmente l'ordine dei tag (nell'amministrazione) ?

**Comment by FrancescaFrigerio** [comment]
@enrimk Il template lo abbiamo creato con "single-unita_organizzativa.php". E  nel template, per visualizzare l'elenco delle persone utilizziamo il file persone.php fornito nel get_template_part("template-parts/single/persone");

@mariantanase sì abbiamo provato a cambiare l'ordine dei tag manualmente da backend, però al momento del salvataggio non vengono salvati nell'ordine impostato, ma vengono ripristinati in un altro ordine di default.
Credo che se funzionasse l'ordine di salvataggio poi la lista delle persone verrebbe mostrata nell'ordine scelto da noi da backend.
