### ISSUE TITLE
Contatti all'interno della pagina servizi

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#336]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Modificare il file single-servizio.php per mostrare nella card anche i contatti telefonici e email del campi "Unità Organizzativa responsabile" e una card separata per il campo  "Punti di contatto".

### Motivazione e contesto

I campi dei contatti dei singoli servizi anche se compilati non vengono mostrati completi di tutti i dati, ma solo il nome e indirizzo (mancano telefono e email) dell'Unità Organizzativa responsabile. Per rendere più facile l'utilizzo si potrebbero mostrare direttamente tutti i contatti nella card dell'Unità Organizzativa responsabile della pagina del servizio stesso, senza doversi spostare da una pagina all'altra per recuperarli.
Anche il campo "punti di contatto" non viene mostrato nella pagina del servizio.

**Comment by enrimk** [comment]
Concordo.

Per avere i dati completi di contatto della UO, e non solo l'indirizzo, al posto di [unita-organizzativa/card.php](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/single-servizio.php#L404) potrebbe bastare includere [l'altra ìversione della card ("full")](https://github.com/italia/design-comuni-wordpress-theme/blob/main/template-parts/unita-organizzativa/card-full.php).  Salvo che poi la grafica è un po' diversa da quella [negli statici](https://italia.github.io/design-comuni-pagine-statiche/sito/servizio-dettaglio.html#contacts).  

Comunque, c'è un po' di confusione nei progetti dei layout.
Nella bozza statica la 'UO responsabile sta nella sez. Contatti e ha un layout da _card-teaser_, e mancano i Punti Contatto del Servizio.
![ps-serv contatti_R](https://github.com/italia/design-comuni-wordpress-theme/assets/93265448/56d84446-c9b9-4b6a-a279-4ae5a51273ad)
Però poi vedo che [in Figma c'è una nuova variante del layout Servizio](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/Comuni---Modello-sito-e-servizi?type=design&node-id=3639%3A202799&mode=design&t=urJD9RKnoZ3TxGhT-1), diversa, che ha Contatti e U.O. responsabile in due sezioni distinte.
![f-serv contatti_R](https://github.com/italia/design-comuni-wordpress-theme/assets/93265448/54fd5093-03f8-45c0-a7f4-60513f099139)

Dovendo implementarne una, andiamo con la seconda? Sembra più chiara e completa.

Mi sa che ci sia bisogno di un altro tipo di card UO - o magari è ora di rivedere le card attuali, che in effetti sono strutturate in modo un po' strano. [^1]

[^1]: Peraltro la UO è necessaria alla validazione del Servizio, tramite l'attrib. `data-element="service-area"`, che [ora sta nella card inclusa](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/unita-organizzativa/card.php#L25) e che forse è più appropriato spostare fuori nel template servizio.

Il box contatti del layout Figma nuovo non è proprio chiarissimo come implementarlo a partire da una lista di P.C. (che è quello che abbiamo a backend), perché i PC qui potrebbero essere uno solo, ma anche più di uno. Accodarli tutti senza  titolo (post_name) nello stesso box? Diverse card?

**Comment by Cam-al** [comment]
si ho provato a usare "card_full.php", è molto meglio ma da due errori nell'app di valutazione.
**Errori:**
C.SI.1.3 - SCHEDE INFORMATIVE DI SERVIZIO PER IL CITTADINO - Tutte le schede informative dei servizi per il cittadino devono mostrare le voci segnalate come obbligatorie all'interno dell'architettura dell'informazione, nell'ordine segnalato dal modello.

C.SI.2.2 - RICHIESTA DI ASSISTENZA / CONTATTI - All'interno del sito comunale, nel contenuto della scheda servizio, devono essere comunicati i contatti dell'ufficio preposto all'erogazione del servizio.

**Comment by enrimk** [comment]
È perché il `data-element="service-area"` che convalida la U.O. ora [sta nella card inclusa](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/unita-organizzativa/card.php#L25).
Il che non è ottimale per vari motivi: intanto perché "accoppia" strettamente la card con il suo utilizzo in quella posizione del template servizi. Tanto varrebbe a questo punto non includere una template-part separata, ma mettere direttamente nel template primario tutto l'html della card.
Poi, perché non è necessariamente nel tag `<a>` della UO che andrebbe messo l'attributo, almeno [secondo la documentazione al §C.SI.1.3](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-1-3-schede-informative-di-servizio-per-il-cittadino). Lì dice:

> «Unità organizzativa responsabile»: viene controllata la presenza di un _tag HTML_ con `data-element="service-area"` che identifica l’area responsabile del servizio e che questo abbia almeno 3 caratteri;

E avrebbe anche più senso spostare l'attributo in un tag _contenitore_ della UO inclusa (è la sezione che viene convalidata, non il singolo contatto). Cioè fuori dalla card, e dentro invece al template servizio (che è in realtà l'oggetto della validazione; meglio se ha tutti i suoi data-element in un posto solo).

Lasciamo stare per il momento che rimane l'ambiguità tra "Contatti" e "UO responsabile", visto che per l'indice di pagina abbiamo:

> «Contatti»: viene controllata la presenza di un tag `<div>` con `data-element="service-area"` che identifica i contatti.

...E per giunta, c'è il doppio layout su Figma che dicevo sopra, diverso dal proto statico.
Comunque, nelle pagine statiche ora l'html è effettivamente così, con il data-element sull'`<a>`, e penso che sarebbe da correggere innanzitutto in quel progetto.

Poi c'è un altro tema ancora, sulla struttura php delle card... Ad es. alcune sembra che includano due diverse varianti di layout, distinte da un flag che viene passato via variabile globale [(`$with_border`)](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/unita-organizzativa/card.php#L2C33-L2C33). Non c'è un modo migliore?
Poi nomi a volte diversi, non sempre coerenti. Il che, qualora serva caricare dallo stesso modulo card di tipologie diverse, costringe [a ginnastiche di questo tipo](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/inc/load_more.php#L76). 

Insomma, volendo, tanta carne al fuoco...

**Comment by fabricius4** [comment]
> È perché il `data-element="service-area"` che convalida la U.O. ora [sta nella card inclusa](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/unita-organizzativa/card.php#L25). Il che non è ottimale per vari motivi: intanto perché "accoppia" strettamente la card con il suo utilizzo in quella posizione del template servizi. Tanto varrebbe a questo punto non includere una template-part separata, ma mettere direttamente nel template primario tutto l'html della card. Poi, perché non è necessariamente nel tag `<a>` della UO che andrebbe messo l'attributo, almeno [secondo la documentazione al §C.SI.1.3](https://docs.italia.it/italia/designers-italia/app-valutazione-modelli-docs/it/versione-attuale/requisiti-e-modalita-verifica-comuni.html#criterio-c-si-1-3-schede-informative-di-servizio-per-il-cittadino). Lì dice:
> 
> > «Unità organizzativa responsabile»: viene controllata la presenza di un _tag HTML_ con `data-element="service-area"` che identifica l’area responsabile del servizio e che questo abbia almeno 3 caratteri;
> 
> E avrebbe anche più senso spostare l'attributo in un tag _contenitore_ della UO inclusa (è la sezione che viene convalidata, non il singolo contatto). Cioè fuori dalla card, e dentro invece al template servizio (che è in realtà l'oggetto della validazione; meglio se ha tutti i suoi data-element in un posto solo).
> 
> Lasciamo stare per il momento che rimane l'ambiguità tra "Contatti" e "UO responsabile", visto che per l'indice di pagina abbiamo:
> 
> > «Contatti»: viene controllata la presenza di un tag `<div>` con `data-element="service-area"` che identifica i contatti.
> 
> ...E per giunta, c'è il doppio layout su Figma che dicevo sopra, diverso dal proto statico. Comunque, nelle pagine statiche ora l'html è effettivamente così, con il data-element sull'`<a>`, e penso che sarebbe da correggere innanzitutto in quel progetto.
> 
> Poi c'è un altro tema ancora, sulla struttura php delle card... Ad es. alcune sembra che includano due diverse varianti di layout, distinte da un flag che viene passato via variabile globale [(`$with_border`)](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/template-parts/unita-organizzativa/card.php#L2C33-L2C33). Non c'è un modo migliore? Poi nomi a volte diversi, non sempre coerenti. Il che, qualora serva caricare dallo stesso modulo card di tipologie diverse, costringe [a ginnastiche di questo tipo](https://github.com/italia/design-comuni-wordpress-theme/blob/dfb829169494552936f9d5bd4a8037a241060d82/inc/load_more.php#L76).
> 
> Insomma, volendo, tanta carne al fuoco...

A me ancora oggi da questo errore sia nelle schede informative che nella richiesta contatti. Nella pagina single-servizio.php è presente: get_template_part("template-parts/unita-organizzativa/card");

**Comment by fabricius4** [comment]
ho risolto facendolo puntare a get_template_part("template-parts/unita-organizzativa/card-full"); e modificando la stessa qui: #444
