### ISSUE TITLE
Bug su Posizione GPS del post type luogo

### ISSUE THREAD

**Issue by marcogangemideda** [italia/design-comuni-wordpress-theme#339]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando si cerca un indirizzo nel campo "Posizione GPS" di un luogo, rimane un caricamento infinito.
Il problema sembrano essere le librerie di Open Street Map: bisogna togliere il "/" prima del "?" della query string, altrimenti la chiamata all'url risponde 404.

Ad esempio: 
https://nominatim.openstreetmap.org/search/?q=via indipendenza bologna&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_0 --> 404
https://nominatim.openstreetmap.org/search?q=via indipendenza bologna&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_0 --> 200

### Includi link o screenshot

![Screenshot 2023-08-04 alle 11 07 33](https://github.com/italia/design-comuni-wordpress-theme/assets/119490526/42908c12-1098-4770-83b1-82f3195cea8b)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by fnori77** [comment]
Salve, come hai risolto? Grazie.

**Comment by fnori77** [comment]
Risolto. Il file da modificare è
inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js

**Comment by abmcr** [comment]
https://github.com/italia/design-comuni-wordpress-theme/issues/340#issuecomment-1667770082

**Comment by zetareticoli** [comment]
Chiudo perché risolto in #340

**Comment by enrimk** [comment]
In realtà la commit sopra era una mia patch "privata" che non era stata ancora integrata: adesso ho aperto una PR.
