### ISSUE TITLE
Errore ricerca luogo nelle mappe

### ISSUE THREAD

**Issue by valeriot30** [italia/design-comuni-wordpress-theme#340]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando si prova a cercare un indirizzo nelle mappe, ad esempio nei luoghi, la ricerca va avanti all'infinito, ho già verificato personalmente e semplicemente l'endpoint API è cambiato.

### Includi link o screenshot

https://github.com/italia/design-comuni-wordpress-theme/assets/30567406/f6b3a5b2-33bf-4001-9aec-0e67a7abf8e0

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.2

**Comment by abmcr** [comment]
Il problema è quindi il campo CMB2-field-Leaflet-Geocoder; e a vedere qui https://github.com/villeristi/CMB2-field-Leaflet-Geocoder non pare venga aggiornato
Questo è come fare https://nominatim.openstreetmap.org/search/?q=Roma&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_0

adesso provo a vedere se riesco a integrarlo nel file del tema design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js

**Comment by abmcr** [comment]
Ecco il fix

file design-comuni-wordpress-theme-main/inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js

riga 372 diventa

      L.Control.Geocoder.jsonp(this.options.serviceUrl + 'search', L.extend({
      
riga 399 diventa

     L.Control.Geocoder.jsonp(this.options.serviceUrl + 'reverse', L.extend({
