### ISSUE TITLE
Non si visualizzano tutti i contenuti che inserisco da backend

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#344]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

In molte ITEM TYPE (persona pubblica, lugo, ecc ...)
pur inserendo dei contenuti, tali contenuti poi non vengono vidualizzati nella pagina da frontend.

Esempio PERSONA PUBBLICA:
- se inserisco un immagine nella galleria, non si visualizza
- se inserisco le competenze, non si visualizzano
-responsabile di: associando in questo valore "Giunta Comunale" nel frontend vedo "Responsabile di : Lucia Moscato" e non Giunta Comunale

Il sito al momento è in SVILUPPO dunque non raggiungibile.

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.2

**Comment by Cam-al** [comment]
Molti template sono incompleti o mancanti, e se non gli hai fatti tu questo potrebbe essere il motivo per cui non si vedono , se invece hai già fatto i template ma non si vedono potrebbe esserci qualche errore nel codice

**Comment by zetareticoli** [comment]
Ciao @cristina-pontarolo, l'assenza di alcuni template è già segnalata in #157 #125

Chiudo quindi questa issue perché duplicata.
