### ISSUE TITLE
Errore visualizzazione caratteri speciali in richiesta assistenza

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#346]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nel modulo di richiesta assistenza quando si clicca nel menu a tendina per vedere i servizi disponibili se hanno caratteri speciali vengono rimpiazzati dal codice html per i caratteri speciali, ad esempio l'apostrofo diventa &#8217

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
A quanto pare alla 770124b è avvenuto un revert di #175 (immagino non voluto).
Forse perché nella 6573905 c'è il file js minificato, ma non [il sorgente](https://github.com/italia/design-comuni-wordpress-theme/blob/main/assets-src/js/assistenza.js)?
Sarà stato ricompilato e sovrascritto con la versione vecchia.

**Comment by enrimk** [comment]
> [...] è avvenuto un revert

Per chiarire meglio: per risolvere, dovrebbe bastare riapplicare la 6573905 (che aveva effettivamente già risolto il bug), ma riportando anche la stessa modifica sul file non minificato, [assets-src/js/assistenza.js, alla riga 118](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/assets-src/js/assistenza.js#L118).
Cioè, `option.text = title;` diventa  `option.innerHTML = title;`

Così si evita che una successiva ricompilazione dai sorgenti annulli le modifiche fatte.

**Comment by Cam-al** [comment]
si, queste modifiche hanno funzionato, grazie

**Comment by enrimk** [comment]
"Not planned"?

**Comment by Cam-al** [comment]
perché questa correzione non è stata aggiunta nell'ultimo aggiornamento?
