### ISSUE TITLE
Criterio C.SI.1.2 - Libreria di elementi di interfaccia

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#347]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

L'app di valutazione del sito riporta costantemente questo problema.
Dalla documentazione non si capisce molto.
Potete spiefgarmi come viene effettuato il test?

### Includi link o screenshot

![C SI 1 2-LIBRERIA DI ELEMENTI DI INTERFACCIA](https://github.com/italia/design-comuni-wordpress-theme/assets/118733111/a67ac662-cab7-463b-9f24-4fd06077aa7b)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Il punto su cui il messaggio del validatore non è tanto chiaro, è che le pagine che analizza alla ricerca di Bootstrap devono essere _tutte pagine valide_ per lui, anche secondo altri criteri: in particolare la presenza dei tag data-element, che le inquadra nella struttura del sito. Bootstrap magari c'è, ma se al validatore la pagina non piace, si rifiuta di prenderla in considerazione e di procedere con la verifica.

E non si limita a controllare una pagina sola, ma ne verifica un certo numero, e di un certo tipo.

A seconda dell'accuratezza scelta per il test, vengono controllate 1, 5, 10, o tutte le pagine di primo, secondo e terzo livello (servizi). 
Se non riesce a identificare [almeno una pagina per ciascun livello](https://github.com/italia/pa-website-validator/blob/3e2715678eacb070bae9ed4ba09c1764b3486a17/src/audits/municipality/bootstrapItaliaDoubleCheckAudit.ts#L107), il test si interrompe lì.
Le pagine di primo e secondo livello le cerca prendendole dal menù; i servizi li cerca caricandoli via ajax dalla pagina Servizi, finché ne trova.

**Comment by marco-nanni** [comment]
Guarda quello l'ho risolto cambiando la voce del menu da "Vivere <nome del comune>" con "Vivere il Comune". 
Mancava il data-element "live" a causa del cambio della descrizione del menu.
Nel mio caso.
Cercare un ago in un pagliaio di 50.000m2 sarebbe meno problematico oltre alla valagna enorme di tempo perso.
