### ISSUE TITLE
Attempt to read property "ID" in archive-services.php

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#348]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Riscontro il seguente errore in una qualsiasi pagina di categoria di servizi :
Warning: Attempt to read property "ID" on int in /var/www/vhosts/modelloagid.it/httpdocs/wp-content/themes/design-comuni-wordpress-theme-1.7.1/inc/utils.php on line 1094
L'errore è ripetuto per il numero totale di servizi della categoria, l'errore è collegato alla funzione
`dci_get_related_unita_amministrative()`
richiamata  in archive-servizio.php per mostrare le unità responsabili nell'elenco a destra dei servizi, che attualmente ne mostra solo una e non tutte 

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
C'è in effetti un piccolo bug in `dci_get_related_unita_amministrative()`.
Prima [qui preleva i servizi come lista di ID](https://github.com/italia/design-comuni-wordpress-theme/blob/80f7c859163b19a3e8861596a1bca57d1422bf48/inc/utils.php#L1067), e poi [qui li usa come oggetti post](https://github.com/italia/design-comuni-wordpress-theme/blob/80f7c859163b19a3e8861596a1bca57d1422bf48/inc/utils.php#L1094).

La soluzione è rapida, [questa è una possibile patch](https://github.com/italia/design-comuni-wordpress-theme/commit/3df22bd371aa6f7b3771dc8465f12907c9e1968d).
