### ISSUE TITLE
Gestire autorizzazioni per i ruoli

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#351]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Sto provando a creare nuovi ruoli per mostrare solo determinate tipologie di post agli utenti registrati che dovranno inserire i contenuti però non riesco ad aggiungere "Configurazione", è visibile solo nel ruolo amministratore, ma non è il caso di dare questo ruolo ad altri utenti.
Ho già provato diversi plugin ma non ho risolto

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
Al di là del ruolo dell'utente, le [opzioni](https://github.com/italia/design-comuni-wordpress-theme/tree/main/inc/admin/options) nel control panel del tema vedo che sono [legate alla capability `manage_options`](https://github.com/italia/design-comuni-wordpress-theme/blob/233073ae956e084274c5da9958c57f6e8a4e05d4/inc/admin/options/opzioni_comune.php#L17) - il che ha senso.

Con uno dei vari plugin per la gestione dei ruoli non dovrebbe essere difficile attribuire la capability a utenti non admin.
Naturalmente, poi questi utenti potranno modificare anche tutto quello che normalmente ricade sotto quella capability, come la sez. _Impostazioni_ di WP.

**Comment by mariantanase** [comment]
In effetti ho notato anch'io che con l'aiuto dei plugin si possono assegnare i ruoli ma giustamente quei utenti avranno in mano anche la possibilità di modificare le impostazioni di WP il che non va bene.
Sarebbe meglio se si potesse fare, di spostare tutte le impostazioni/configurazioni del tema, fuori dalle impostazioni di WP, allo stesso livello di Unità Operative, Documenti Pubblici e così via.

**Comment by Cam-al** [comment]
Si, alcuni tab di "Configurazione" come "configurazione comune" e "Footer" si possono anche lasciare solo all'amministratore, ma tutte le altre che devono essere aggiornate frequentemente no.
Io sto provando tutti i plug-in ma non riesco proprio a risolvere.
Non noto nessuna differenza con le altre voci che usano "manage_options" che però riesco a visualizzare con altri ruoli oltre all'amministratore.
Ho provato anche un plugin che mi consentiva di creare nuovi ruoli e assegnarli un livello da 0 a 10 (dieci dovrebbe essere l'amministratore) , e nemmeno cosi visualizzo "configurazione"

**Comment by enrimk** [comment]
In che senso non noti differenze? Ora il cpanel Configurazione è interamente sotto `manage_options`, è l'unica capability usata, e un utente che ce l'ha ne vede tutte le voci.
Per distinguere le voci per ruolo, si dovrà modificarne la dichiarazione nel codice con capability diverse.
Già da ora però, con uno dei vari plugin apposta, si può attribuire la capability a un ruolo che di suo non l'avrebbe, e i relativi utenti il pannello lo vedono.
O se usi wp-cli, anche agire direttamente sull'utente, con qualcosa tipo:
```
$ wp user add-cap <nomeutente> manage_options
```
Solo che poi l'utente vede e può mettere le mani anche su altre cose, come il nome del sito, permalink, ecc.

**Comment by Cam-al** [comment]
Sto riscontrando altri problemi con "tickets" e "valutazioni", non riesco a concedere il permesso tramite plugin sebbene sia già abilitato. 
Sono riuscito ad abilitare "Configurazione" utilizzando il plugin PublishPress Capabilities che mi consente di creare un nuovo ruolo con i permessi di amministratore e poi con un altro plugin  Adminimize tolgo tutti i permessi che non servono.
Non mi piace come soluzione dover usare due plugin sicuramente la cosa migliore sarebbe avere già un ruolo con tutti i permessi corretti già nel tema ma per il momento va bene cosi. 
Adesso mi rimane solo da far funzionare tickets e valutazioni

**Comment by enrimk** [comment]
Non è necessario replicare esattamente un ruolo esistente, e lasciarlo così; _PublishPress Capabilities_ ti consente anche di "comporre" i permessi del nuovo ruolo partendo dalle singole capabilities. Per comodità puoi partire da admin e toglierne, o da editor e aggiungerne, come preferisci.  Si può ricopiare un ruolo esistente su uno nuovo, o modificarlo senza duplicarlo.
Credo si possa fare tutto con un solo plugin.

**Comment by enrimk** [comment]
> tickets e valutazioni

Vedi anche [qui](https://github.com/italia/design-comuni-wordpress-theme/issues/281#issuecomment-1739281339).
