### ISSUE TITLE
problemi aggiornamento da versione 1.2.1 all'ultima versione

### ISSUE THREAD

**Issue by tomasdimaio** [italia/design-comuni-wordpress-theme#352]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nell'aggiornare la versione del tema su csm wordpress, scompaiono gli argomenti, nella sezione Amministrazione

### Includi link o screenshot

[problemi aggiornamento tema.pdf](https://github.com/italia/design-comuni-wordpress-theme/files/12584146/problemi.aggiornamento.tema.pdf)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

ultima ad oggi

**Comment by tomasdimaio** [comment]
Ciao
ho semplicemente aggiornato nel backend di wordpress, come dal file
allegato, appena aggiornato scompaiono gli argomenti correlati ed esce
questo messaggio di attenzione
[image: image.png]


questa era la schermata con la versione precedente
[image: image.png]

Il giorno mar 12 set 2023 alle ore 10:41 Francesco Improta <
***@***.***> ha scritto:

**Comment by enrimk** [comment]
Strano perché, anche se [dalla 1.2.1 di acqua ne è passata parecchia](https://github.com/italia/design-comuni-wordpress-theme/compare/v1.2.1...v1.7.3), i template della pagina Amministrazione non li vedo tra quelli modificati da allora.
La pagina è la stessa di prima, e ha ancora il template "amministrazione"? E ha le stesse sottopagine?

Dallo screenshot parrebbe anche avere un layout leggermente diverso per il titolo, che non corrisponde al template.

**Comment by tomasdimaio** [comment]
Per semplificare ti giro i due link dove sono installati i temi:

1-su questo sito ho installato la versione 1.2.1 e si vede la parte esplora
l'amministrazione:
*https://www.formadist.it/cittadino/amministrazione
<https://www.formadist.it/cittadino/amministrazione>*

[image: image.png]                              [image: image.png]


2-su questo altro ho installato la versione 1.7.3 e compare il messaggio di
attenzione:
*https://cittadino.comune.luogosano.av.it/amministrazione/
<https://cittadino.comune.luogosano.av.it/amministrazione/>*


[image: image.png]   [image: image.png]

il tema l'ho scaricato da questo link
Grazie per la disponibiltà





Il Mar 12 Set 2023, 18:03 enrimk ***@***.***> ha scritto:

**Comment by enrimk** [comment]
Non sono passati gli screenshot allegati, e seguendo i link non vedo nessun messaggio.
Ma vedo anche che, a differenza del primo screenshot, la lista sotto "Esplora l'amministrazione" ora è presente: hai già risolto?

**Comment by tomasdimaio** [comment]
Ciao, grazie della risposta
Ho risolto in parte, seguendo il consiglio trovato su forum italia: "Ciao,
se vuoi ho risolto.

Devi semplicemente andare nella modifica della pagina e selezionare il
template di quella pagina li, al posto di “template predefinito”.

Esempio: se vai nella modifica della pagina “vivere il comune”, dovrai
selezionare il template “vivere il comune”.

Spero sia stato chiaro, buona giornata. [image: :grinning:]"

Questa soluzione pero e limitata solo ad alcune pagine, cmq installando
anche su altri siti il problema non cambia

Veramente non so che fare, cmq continuo a provare

grazie

Il giorno mer 13 set 2023 alle ore 10:03 enrimk ***@***.***>
ha scritto:

**Comment by enrimk** [comment]
Quindi in sostanza, aggiornando il tema non è più selezionato il template corretto nelle pagine predefinite, e ciò succede sempre e regolarmente? E anche in altre pagine oltre ad Amministrazione?

**Comment by tomasdimaio** [comment]
Si praticamente, in tutte le pagine, ho provato, anche a cancellare tutte
le cartelle del tema e reinstallarlo ex novo ma in sostanza non cambia,
niente.
Non è che sbaglio tema

Il Mer 13 Set 2023, 12:35 enrimk ***@***.***> ha scritto:

**Comment by tomasdimaio** [comment]
scusate ma continuo a rilevare problemi con il tema, nell'inserire un luogo si blocca sulla mappa, che , essendo un campo obbligatorio, non pubblica la pagina 
![Immagine1](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/5de95b12-b1a4-437c-bde6-4eab0e50b902)

**Comment by enrimk** [comment]
> scompaiono gli argomenti, nella sezione Amministrazione

> in sostanza, aggiornando il tema non è più selezionato il template corretto

Vedi: #393

**Comment by enrimk** [comment]
@tomasdimaio 
Il bug sui template dovrebbe essere stato risolto nella v1.7.5.

**Comment by astagi** [comment]
Si esattamente, problema risolto sull'ultima versione, grazie @enrimk .
