### ISSUE TITLE
La posizione GPS della mappa nei luoghi non conclude mai la selezione

### ISSUE THREAD

**Issue by danieledexter** [italia/design-comuni-wordpress-theme#354]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Su tutti i siti in cui ho installato il tema comuni, poi anche scuole (solo per verifica) ho notato che la selezione del luogo non funziona. Ho messo lo stesso indirizzo in formati diversi, ma la ricerca non da risultati, resta in caricamento e basta.

In console ho questo errore:
geocoder.js?ver=0.1.3:273     GET https://nominatim.openstreetmap.org/search/?q=Via%20Indipendenza%2C%2041%2C%2035013%20Cittadella%20PD&limit=5&format=json&addressdetails=1&json_callback=_l_geocoder_1 net::ERR_ABORTED 404

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.3

**Comment by emanueleempix** [comment]
Anch'io ho riscontrato il problema. Su istallazione locale

**Comment by danieledexter** [comment]
Aggiornato file js, come da PR, mi sembra ok.

**Comment by zetareticoli** [comment]
@danieledexter hai risolto con la PR #355 ?

**Comment by danieledexter** [comment]
> @danieledexter hai risolto con la PR #355 ?

Si, risolto aggiornando il file indicato.
