### ISSUE TITLE
Impossibile creare un luogo

### ISSUE THREAD

**Issue by tomasdimaio** [italia/design-comuni-wordpress-theme#358]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno ho constatato che  nell'inserire un luogo si blocca sulla mappa, che , essendo un campo obbligatorio, non pubblica la pagina 
![Immagine1](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/5de95b12-b1a4-437c-bde6-4eab0e50b902)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
Probabilmente è lo stesso difetto segnalato in #354, potresti provare ad applicare la patch proposta là.

Se invece, a parte il problema tecnico alla geolocalizzazione, segnali un difetto nella UI dei Luoghi... sì, in effetti, come miglioria,  sarebbe preferibile che i campi delle coordinate fossero visibili e si potessero compilare anche a mano, per non dover necessariamente sottostare ai capricci di Openstreetmap (o della connettività di rete). Oppure, che la loro mancanza rimanesse magari ben evidenziata come errore, ma che non fossero strettamente obbligatori durante l'inserimento.

**Comment by zetareticoli** [comment]
Ciao @tomasdimaio, in base al commento di @enrimk non capisco se c'è una difficoltà nell'uso dell'interfaccia o un bug, nel senso che non funziona proprio.

**Comment by rpiscopo-easyweb** [comment]
Anche io ho riscontrato questo errore, senza errori in console di alcun tipo.
@zetareticoli la difficoltà è nell'utilizzo della mappa, se si cerca un indirizzo, viene soltanto visualizzata una rotellina che gira all'infinito, ma non trova il luogo e non è possibile identificarlo diversamente (magari cliccando sulla mappa). Per cui, il salvataggio è impossibile.

**Comment by tomasdimaio** [comment]
Facendo le modifiche riportate in #354 e cioè modificando il file geodecoder.js, da subito non ha funzionato, ma dopo un po di tempo, è riuscito a funzionare, continuo a testare e vi aggiorno

**Comment by zetareticoli** [comment]
@tomasdimaio hai testato la PR #355 ? Con quella si risolve?
