### ISSUE TITLE
Caricamento documenti pubblici : allegati non presenti

### ISSUE THREAD

**Issue by mirkopeloso** [italia/design-comuni-wordpress-theme#36]
Se si crea un documento pubblico caricando ad esempio un PDF dalla media gallery di WP, il link viene settato correttamente nella relativa input, ma quando si salva il post e si pubblica, nella pagina web non è presente alcun allegato.

Cliccando sul menu "Vedi Azioni"->"scarica", non viene scaricato nulla.

**Comment by astagi** [comment]
@mirkopeloso possiamo provare a replicare. Da link direttamente è possibile raggiungere l'allegato?

**Comment by mirkopeloso** [comment]
Grazie del supporto, vi indico i link e allego uno screenshot (il sito è in costruzione perchè le nomine sono state fatte il 15 settembre):

pagina del sito:
https://unionecomuniarcipelagodelsulcis.it/documento_pubblico/delibera-n-02-del-15-09-2022/

documento pubblico:
http://unionecomuniarcipelagodelsulcis.it/wp-content/uploads/Delibera-2_2022.pdf

Screenshot della parte di backend linkata al doc:
![Screenshot from 2022-09-29 08-32-32](https://user-images.githubusercontent.com/51156052/192956533-7ab7b429-26f2-4404-ac4e-f8b442c1076b.png)

**Comment by astagi** [comment]
@mirkopeloso sembra lo stesso problema riscontrato qui https://github.com/italia/design-comuni-wordpress-theme/issues/67

**Comment by astagi** [comment]
@mirkopeloso la sezione Scarica non sarà più disponibile tra le azioni, l'allegato deve essere visualizzato correttamente nella pagina. Ci sono contribuzioni in corso per risolverlo.

**Comment by astagi** [comment]
@mirkopeloso ti aggiorno che @giannicozzolino sta implementando questa mancanza, appena ci sono news linkiamo la PR :)
