### ISSUE TITLE
numero verde

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#360]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

il comune non ha un numero verde ma un numero telefeonico standard. come posso modificare la dicitura?

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS, Android, iOS, Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
Da backend, non si può.
Modificando i template, ovviamente sì: banalmente, sostituendo la stringa [nei punti dove compare](https://github.com/search?q=repo%3Aitalia%2Fdesign-comuni-wordpress-theme+%22Numero+Verde%22&type=code).

Se lo si vuole togliere del tutto, siccome l'unico template dove non sta dentro un blocco condizionale è [assistenza-contatti.php](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/template-parts/common/assistenza-contatti.php#L33), basta cambiare quello. [^*]
Il modo più pratico è probabilmente con un child theme.

Non sono certo si tratti di un bug.

[^*]: Come proposta di miglioria, si può mettere la voce Nº verde dentro a una condizione anche in assistenza-contatti.php, come è già in [footer.php](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/footer.php#L126).
In effetti non è obbligatorio nelle opzioni, e non mi pare che sia necessario alla validazione (non trovo nulla nei criteri, non ha un data-element associato, ecc.).
