### ISSUE TITLE
Errori di accessibilità

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#362]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Facendo delle verifiche per l'accessibilità con il validatore Mauve++ riscontro diversi errori.
Gli errori presenti nella home (anche nelle altre pagine ci sono errori) : 

1. Criterion: 1.1.1  [Tech: ARIA6](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA6)
Using aria-label to provide labels for objects
principalmente collegato alle icone, riga di empio `<svg class="icon">`

2.  Criterion: 1.3.1 [Tech: H42](https://www.w3.org/WAI/WCAG21/Techniques/html/H42)
Using h1-h6 to identify headings
collegato alla riga : `<h2>Cerca</h2>` delle barra di ricerca nel menu in alto a destra

3. Criterion: 1.3.5 [Tech: H98](https://www.w3.org/WAI/WCAG21/Techniques/html/H98)
Identify the purpose of inputs using the autocomplete value
collegato alla riga: `<input class="form-control" id="formGroupExampleInputWithHelp" aria-describedby="formGroupExampleInputWithHelpDescription" maxlength="200" type="text" data-element="feedback-input-text"> ` che riguarda il form della valutazione della pagina

4. Criterion: 1.4.10  [Tech: C38](https://www.w3.org/WAI/WCAG21/Techniques/css/C38)
Using CSS width, max-width and flexbox to fit labels and inputs
- alla riga `<div class="container">` dentro il form di ricerca del menu
- alla riga `<div class="cmp-input-search">`  dentro il form di ricerca per parola chiave sopra i link utili

5. Criterion: 1.4.11 [Tech: G195](https://www.w3.org/WAI/WCAG21/Techniques/general/G195)
Using an author-supplied, highly visible focus indicator 
in diversi pulsanti che come : `<button type="button" class="btn btn-outline-primary">`

6. Criterion: 4.1.1  [Tech: H93](https://www.w3.org/WAI/WCAG21/Techniques/html/H93)
Ensuring that id attributes are unique on a webpage
- nella riga del form di ricerca del menu : `<form role="search" id="search-form" method="get" class="search-form" action="https://modelloagid.it/">`
-  nella riga del form di ricerca dei link utili: `<form role="search" id="search-form" method="get" class="search-form" action="https://modelloagid.it/">`
-  nella riga: `<main id="main-container" class="main-container redbrown">`
- nella riga: `<h1 class="visually-hidden" id="main-container"> Comune di Loiri Porto San Paolo </h1>`

Per il punto 2 dovrebbe essere sufficiente per correggerlo cambiare l'h2 
Per il punto 4 bisogna dare delle dimensioni
Per il punto 5 qualche problema con il focus che è presente
Per il punto 6 bisogna togliere i doppi ID

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by zetareticoli** [comment]
Ciao @Cam-al , grazie della segnalazione.

Valutiamo quanto da te indicato e proviamo a inserire le correzioni in una prossima release.

**Comment by zetareticoli** [comment]
@Cam-al 

in merito al punto 1, l'attributo `aria-label` dovrebbe essere utilizzato esclusivamente per quelle icone non decorative inserite in un link o call to action. Quali sono quelle che ti ha segnalato il validatore?

**Comment by Cam-al** [comment]
@zetareticoli 

In merito al punto 1, le segnala praticamente tutte in tutte le pagine, se l'icona è irrilevante perché accompagnata dal testo penso si debba mettere `aria-hidden="true"` ma non sono del tutto certo.

In merito al punto 2, cliccando su cerca in alto a destra si apre la sezione "Search modal" che contiene un `<h2>` con scritto "Cerca", probabilmente viene segnalato perché nella struttura della pagina questo `<h2>`  si trova prima del `<h1>`. si potrebbe togliere perche già inserito in grande dentro l'input "Cerca nel sito" oppure mettere in un `<p>` ma senza aumentare troppo `font-size` perché questo potrebbe portare a un altro errore.

Ti consiglio di provare a fare una verifica anche sulla [home statica](https://italia.github.io/design-comuni-pagine-statiche/sito/homepage.html) con [MAUVE++](https://mauve.isti.cnr.it/) per vedere meglio dove e quali errori vengono segnalati, perché quelli che rileva sono diversi ed è un po' impegnativo da riportare tutto qua.

Ci sono anche errori che mauve non può rilevare e per quello andrebbe fatta una verifica manuale.

Tra i criteri di successo mi sembra di aver letto che bisogna consentire la modifica del testo come ad esempio la dimensione o il contrasto, ma non essendo disponibile nel tema ho provato a risolverlo con qualche plugin che però porta ad avere altri errori nel app di valutazione per via del css che non utilizza bootstrap.

**Comment by zetareticoli** [comment]
Faremo ulteriori indagini, non riscontriamo le stesse problematica con altri strumenti di test. Per ora, c'è una PR dedicata al punto 6 #379

**Comment by Cam-al** [comment]
Grazie, posso chiederti che altri strumenti utilizzate per le verifiche?
Anche io ne ho provato diversi ma non trovo altri strumenti per la verifica dell'accessibilità per il livello WCAG 20.1 oltre a [MAUVE++](https://mauve.isti.cnr.it/)

**Comment by cristina-pontarolo** [comment]
> Grazie, posso chiederti che altri strumenti utilizzate per le verifiche? Anche io ne ho provato diversi ma non trovo altri strumenti per la verifica dell'accessibilità per il livello WCAG 20.1 oltre a [MAUVE++](https://mauve.isti.cnr.it/)

puoi installare su CHROME la APP WAVE Web Accessibility Evaluation Tool

**Comment by Cam-al** [comment]
Si l'ho provato e non da quasi nessun errore ma non mi è chiaro in base a quale livello WCAG effettua i controlli, se 2.0 o 2.1 livello A, AA o AAA

**Comment by Cam-al** [comment]
@zetareticoli, io riscontro ancora alcuni degli errori indicati, ad esempio le icone e il focus di alcuni tasti.
Per quanto riguarda le icone ho trovato informazioni in [questa pagina ](https://fontawesome.com/docs/web/dig-deeper/accessibility#icons-used-as-decorative-elements-2), dove spiega che per rendere accessibili le icone decorative bisogna mettere aria-hidden="true"
