### ISSUE TITLE
link footer eliminati

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#363]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ogni volta che passo dal tema child a quello padre e di nuovo al child vengono cancellati tutti i link che ho inserito nel footer, ad esempio:
Amministrazione trasparente, Informativa privacy, Note legali, Dichiarazione di accessibilità, ritornano tutti con il link nella stessa pagina # come nel tema originale .
Questo mi costringe a dover rimettere i link a ogni aggiornamento del tema.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
A quanto pare a ogni (ri)attivazione del tema [vengono resettati tutti i menù](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/activation.php#L404), e [le voci di menù](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/activation.php#L381) sono [sovrascritte dai default](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/activation.php#L418).

A prima vista non vedo un modo rapido di risolvere, senza riscrivere gran parte delle procedure inserendo dappertutto dei controlli, che ora mancano, sugli eventuali elementi già esistenti prima della sovrascrittura. Forse, "staccare" [`dci_theme_activation()` dal suo hook](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/activation.php#L44), e sostituirla con la propria implementazione. Se lo si fa nel child, però, viene tolto un po' lo scopo.

Piuttosto, è proprio necessario "spegnere e riattivare" il tema a ogni aggiornamento? Certo, se cambiano tassonomie, menù, ecc.. Ma si spera che ormai siano relativamente stabili; e nel caso è possibile farlo a mano. Non comodo, d'accordo.

**Comment by enrimk** [comment]
> quelle delle novità e vivere il comune rimangono ma sono sbagliate

Strano: hai per caso più di una pagina con gli stessi titoli?
Magari anche nel cestino, [`get_page_by_title()`](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/activation.php#L428C12-L428C29) non filtra [per _post_status_](https://github.com/WordPress/WordPress/blob/73c8507a847a5e7e0b8773f0854e8517b9f9afcf/wp-includes/deprecated.php#L4573-L4578).

**Comment by Cam-al** [comment]
No, intendo dire che sono sbagliati perché mandano sempre alla stessa pagina "Novità" o "Vivere il comune" anche se clicco su notizie, comunicazioni , avvisi, luoghi e eventi

**Comment by enrimk** [comment]
> mandano sempre alla stessa pagina

Lo noto solo ora...  È vero, sono custom link anche quelli, e [impostati tutti allo stesso url](https://github.com/italia/design-comuni-wordpress-theme/blob/50df1fa9f6f901575622ce5c6e23595b825d897d/inc/activation.php#L340-L342).

Le [righe successive commentate](https://github.com/italia/design-comuni-wordpress-theme/blob/50df1fa9f6f901575622ce5c6e23595b825d897d/inc/activation.php#L344-L346) fanno pensare che fosse stato preso in considerazione di usare degli archivi di tassonomia per quei link, ma poi [qui è stato deciso altrimenti](https://github.com/enrimk/design-comuni-wordpress-theme/commit/f18a837836f187ea2d304f570823297f794d31b1) (e [_tipi_notizia_, l'archivio non l'ha più](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/inc/admin/tassonomie/tassonomia_tipi_notizia.php#L28-L29)).

Mi piacerebbe capire meglio la ratio di quella commit.
Anche e specialmente per la disattivazione degli archivi di Evento e Luogo, che sarebbero così comodi.

**Comment by zetareticoli** [comment]
@Cam-al il problema si manifesta solo quando disattivi e poi attivi il tema o anche quando lo aggiorni solamente?

**Comment by Cam-al** [comment]
anche dopo l'ultimo aggiornamento (1.7.4) il problema si presenta di nuovo, anche senza caricare lo zip, ho inserendo direttamente il tema dentro wp-content/themes e non è cambiato nulla.
Dopo aver caricato il tema sono costretto a disattivare il child e riattivarlo per farlo funzionare (altrimenti vedo solo una schermata bianca), e questo fa perdere i link del footer. Tra le varie modifiche apportate al tema originale (perché non possibili nel child) per l'aggiunta di alcuni template, funzionalità e correzioni di bug... la mancanza del aggiornamento diretto dai temi di WordPress, dover modificare il child per via del nome del tema che contiene anche la versione (facilmente risolvibile anche da parte mia) e in più dover rimettere i link che vanno persi a ogni aggiornamento oltre a dover controllare il corretto funzionamento di tutto il resto fare ogni aggiornamento sta diventando abbastanza scomodo.
Non è per lamentarmi ma per chiedere un consiglio su come stanno facendo gli altri e se ce qualche modo per evitare alcuni di questi passaggi

**Comment by enrimk** [comment]
Credo dovresti investigare un po' più in dettaglio la causa della "schermata bianca", perché non sembra un comportamento normale a seguito della semplice sostituzione di qualche script php.

Sul tuo server c'è qualche tipo di cache che non viene invalidata e aggiornata correttamente al cambio dei file? Non so, zend opcache, o cose analoghe, per caso? Hai provato a riavviare php anziché disattivare il tema?

**Comment by Cam-al** [comment]
Nel server ho attivo opcache, pensi possa essere quello?  no non ho provato a riavviare php, la prossima volta proverò prima quello, grazie
