### ISSUE TITLE
HOME PAGE - TItolo "Argomenti in evidenza" non si vede perchè p stata associata nel codice del tema la calsse "text-white"

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#364]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella home pagie la Sezione "Argomenti in evidenza" non si visualizza più perchè è bianca. Questo accade perchè nel codice del tema è syata associata una classe che rende il titolo bianco:
text-white
<h2 class="**text-white** title-xlarge mb-3">Argomenti in evidenza</h2>

### Includi link o screenshot

![Screenshot 2023-09-25 alle 14 55 24 (2)](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/beff9960-b98f-4f9c-bdc8-61641b97b8a1)

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Il testo lì è bianco perché [lo sfondo](https://wp-dev1.ecohmedia.com/wp-content/themes/design-comuni-wordpress-theme/assets/img/evidenza-header.png) non lo è - o non dovrebbe esserlo.
(V. anche: [statiche](https://italia.github.io/design-comuni-pagine-statiche/sito/homepage.html))

---

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/93265448/eccb57f6-fc8c-4d77-9bf0-a5fabef71c9a)

**Comment by marco-nanni** [comment]
Risolto. Era un problema di reperimento dello sfondo.
