### ISSUE TITLE
C.SI.1.2 - LIBRERIA DI ELEMENTI DI INTERFACCIA

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#365]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Eseguendo l'app di valutazione versione 2.7 appare questa segnalazione.
La libreria di Bootstrap è presente e, come da immagine, è superiore alla versione riportata dalla documentazione dell'app di valutazione. E' per caso un falso positivo o c'è qualche altro problema?
Tenete presente che questa segnalazione, con le versioni precedenti dell'app di valutazione, non appariva.

Grazie.

### Includi link o screenshot

![C SI 1 2](https://github.com/italia/design-comuni-wordpress-theme/assets/118733111/4c718768-1c87-41c8-8e59-bcdb73df6201)

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Sembra che sia stato [aggiunto il controllo sulla percentuale classi css](https://github.com/italia/pa-website-validator/commit/59c0066481d6a04823e8d5bcf8c08c7ef7adfc87) di BI sul totale.
Bootstrap Italia, a quanto pare, è un framework geloso: "Non avrai altro css all'infuori di me". 🤔

**Comment by marco-nanni** [comment]
Ma che senso ha? Il bello che le pagine sono le loro.

**Comment by marco-nanni** [comment]
RISOLTO. Il solito plugin Cookiebot installato dal cliente.
Qui si ripresenta l'annoso problema dell'utilizzo di plugin di terze parti per ovviare a mancanze del tema.
Se si vuole impostare dei controlli cosi serrati sul tema, lo stesso DEVE NECESSARIAMENTE essere completato in tutte le sue parti estensioni comprese. Anche perché non tutte le aziende vogliono o possono sobbarcarsi il costo dello sviluppo per completare parti mancanti o corregge anomalie per ovviare ai riscontri dell'app di valutazione. Quindi si è costretti a ricorrere all'utilizzo di plugin di terze parti che però in certi casi, come questo e l'altro precedente, innescano problemi di questo tipo.
