### ISSUE TITLE
richiesta assistenza: configurare la url di " informativa sulla privacy."

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#367]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Vorrei modificare la URL del link "informativa sulla privacy", ma non so dove si configura.

### Includi link o screenshot

![Screenshot 2023-09-29 at 08-39-00 Assistenza – Comune di Letojanni](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/4b8878ad-2a0e-4ca3-9391-6dfb901196f1)

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Non si configura da nessuna parte: [il link è "finto"](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/page-templates/assistenza.php#L261C45-L261C53).  🤔 
Come d'altra parte anche [il link per l'accesso SPID](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/page-templates/assistenza.php#L55C33-L55C41), ecc. [^*]

[^*]: Immagino ci siano ottime ragioni per queste incompletezze: lo _scope_ del progetto, il livello a cui sarà stato finanziato e "staffed", i tempi; anche il fatto che alcuni moduli, come l'assistenza, sono probabilmente da customizzare comunque... Fatto sta che 1) questi limiti non sono sempre ben chiariti in partenza al pubblico;  2) dove non si può arrivare ci si accontenta di "dare una traccia", e sperare;  3) lo sviluppo anziché accelerare con il pnrr che incalza sembra in stallo...  🙁

**Comment by zetareticoli** [comment]
@cristina-pontarolo devi editare il relativi tag `<a>`(riga 215 del template `assistenza.php`).

Non tutto è configurabile direttamente da _back-office_ di WP.
