### ISSUE TITLE
Icona expand non viene visualizzata negli accordion

### ISSUE THREAD

**Issue by Tizzz-555** [italia/design-comuni-wordpress-theme#370]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno, nei vari accordion del sito, come ad esempio quello della single-servizio, non viene visualizzata l'icona expand
```
<svg class="icon icon-xs right">
<use href="#it-expand"></use>
</svg>
```

### Includi link o screenshot

![Screenshot 2023-10-04 at 16 27 07](https://github.com/italia/design-comuni-wordpress-theme/assets/103275021/e3a07040-9bd0-4e7d-8bc1-78c405a030cd)

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
Curiosamente, questo problema sembra in qualche modo l'_opposto_ di quello nell'issue linkato. Là si segnalava un path in più, sbagliato, qui l'href punta diretto a un fragment nella pagina corrente.

Ma il codice dell'icona riportato sopra non dovrebbe essere sbagliato, in realtà. Le icone sono tutte incluse localmente; è proprio nell'html della pagina che stanno.
[_Single-servizio_ include _header_](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-servizio.php#L11), che [include _template-parts/common/sprites_](<?php get_template_part("template-parts/common/sprites"); ?>), che contiene [l'svg delle icone](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/template-parts/common/sprites.php#L1C9407-L1C9450).

@Tizzz-555, per caso succede qualcosa nelle tue pagine per cui l'svg manca? 

Altrimenti, se il markup è in ordine, sarà magari successo qualcosa al foglio di stile.

**Comment by Tizzz-555** [comment]
Il markup è in ordine, se ispeziono l'html tutti gli elementi compaiono come da codice, stranamente però ho questo problema, un po' con tutti gli svg in realtà, ad esempio anche i bottoncini "condividi" e "vedi azioni" 
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/103275021/45e77db7-a713-4088-bee8-3492060c02dd)

**Comment by Tizzz-555** [comment]
Ho trovato un accordion che non soffre di questo problema comunque, quello di single-documento-pubblico.
In questo caso la classe del svg è:
```
<svg class="icon icon-sm icon-primary align-top">
```
Cambiata in single-servizio.php ed effettivamente in questo modo la freccia compare

**Comment by enrimk** [comment]
Però non credo che sia una soluzione: intanto perché questo non sembra essere un bug del tema, è probabilmente qualcosa nel tuo setup.  
Poi, lì [l'html in single-servizio.php](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-servizio.php#L160-L165) segue pari pari [quello di design-comuni-pagine-statiche](https://github.com/italia/design-comuni-pagine-statiche/blob/3a447b52ee38e969ca5e8162d8d38c09b234b1f6/src/components/cmp-navscroll/cmp-navscroll.hbs#L9-L15).

Ma la tua anomalia può essere sintomo di qualcos'altro. E in effetti, a cercare, qualcosa si trova.

1) A cosa serve la classe css `right` sull'icona? Credo a niente, l'allineamento avviene via flexbox. E non sembra ci siano regole css associate in BI. [ NB: altri framework potrebbero usarla, ha un nome comune. Controlla magari, togliendola, se tu hai avuto interferenze di quel tipo ] 
2) Perché [Documento pubblico](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-documento_pubblico.php#L82-L84) ha una sidebar diversa da Servizio? L'icona dovrebbe essere la stessa. Invece, è più grande, e ha un colore diverso. Anche [il dettaglio novità](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-notizia.php#L86-L88), e quello [dell'evento](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-evento.php#L95-L97), nel tema hanno la stessa sidebar. Ma è quella "sbagliata": [in pagine-statiche, quella "giusta"](https://github.com/italia/design-comuni-pagine-statiche/blob/3a447b52ee38e969ca5e8162d8d38c09b234b1f6/src/components/cmp-navscroll/cmp-navscroll.hbs#L12C31-L12C49) è quella usata nei servizi.  [Il mockup su Figma](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/Comuni---Modello-sito-e-servizi?node-id=33426%3A169510&mode=dev) è un po' più vicino a quello nelle statiche (?), con l'icona piccola e nera (anche se: [l'icona è più spessa](https://www.figma.com/file/WWt2dI4AnnHDj53jHH41ko/Comuni---Libreria-componenti?node-id=2%3A8&mode=dev), e anche il titolo è nero anziché colorato. Mah).
![Screenshot 2023-10-05 115955](https://github.com/italia/design-comuni-wordpress-theme/assets/93265448/38b46725-faef-447e-9c38-aa8e6d3d15b9)

Morale: finché per verificare le specifiche di ogni dettaglio minore si dovranno consultare dieci documenti e prototipi diversi, su diverse piattaforme e spesso incompleti e in disaccordo fra loro, per approdare alla fine a nulla di concreto, non vedo come 'sto progetto possa prendere slancio e arrivare a una conclusione.

**Comment by Tizzz-555** [comment]
Sì senz'altro non è una soluzione, facevo solo notare come hai confermato anche tu che la sidebar di documento pubblico è diversa. 

> 1. A cosa serve la classe css `right` sull'icona? Credo a niente, l'allineamento avviene via flexbox. E non sembra ci siano regole css associate in BI. [ NB: altri framework potrebbero usarla, ha un nome comune. Controlla magari, togliendola, se tu hai avuto interferenze di quel tipo ]

Togliendo right non si è risolto il problema, continuerò ad indagare

Grazie per la tua risposta, hai senz'altro fornito molti spunti e in modo estremamente chiaro.

**Comment by Tizzz-555** [comment]
Segnalo di aver trovato il culprit del problema, come dicevi @enrimk era un problema mio locale, un file css di uno dei plugin custom installati interferiva.
