### ISSUE TITLE
R.SI.1.1 - METATAG - codice json non valido

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#374]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Il codice json contenuto nella pagina `single-servizio.php`, risulta non valido e di conseguenza anche il tool di validazione lo segnala.
Come va modificato per superare la validazione in oggetto ?
```

{
                    "name": "<?php echo esc_js($post->post_title); ?>",
                    "serviceType": "<?php echo esc_js($categoria_servizio); ?>",
                    "serviceOperator": {
                        "name": "<?php echo esc_js($ipa); ?>"
                    },
                    <?php if ( !empty($copertura_geografica) ) : ?>
                    "areaServed": {
                        "name": "<?php echo convertToPlain($copertura_geografica); ?>"
                    },
                    <?php endif; ?>
                    "audience": {
                        "audienceType": "<?php echo convertToPlain($destinatari); ?>"
                    },
                    "availableChannel": {
                        <?php if ( !empty($canale_digitale_link) ) : ?>
                        "serviceUrl": "<?php echo esc_js($canale_digitale_link); ?>",
                        <?php endif; ?>
                        <?php if ( !empty($ufficio) ) : ?>
                        "serviceLocation": {
                            "name": "<?php echo esc_js($ufficio->post_title); ?>",
                            "address": {
                                "streetAddress": "<?php echo esc_js($indirizzo); ?>",
                                "postalCode": "<?php echo esc_js($cap); ?>"
                                <?php if ( !empty($quartiere) ) : ?>,
                                "addressLocality": "<?php echo esc_js($quartiere); ?>"
                                <?php endif; ?>
                            }
                        }
                        <?php endif; ?>
                    }
            }
```
Grazie

### Includi link o screenshot

![Screenshot 2023-10-10 at 14-26-41 Lighthouse Report](https://github.com/italia/design-comuni-wordpress-theme/assets/3976174/142dbc0f-d864-4600-8dc5-2a84d6374926)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
Probabilmente, è a causa dell'apostrofo nel titolo del servizio: "_Carta d'identità..._".
Vedi: #343

**Comment by mariantanase** [comment]
> Probabilmente, è a causa dell'apostrofo nel titolo del servizio: "_Carta d'identità..._". Vedi: #343

La tua pull risolverebbe il problema ?
Grazie

**Comment by mariantanase** [comment]
Con la pull-request il json risulta valido, però ancora non passa la validazione.

![Screenshot 2023-10-10 at 16-32-00 Lighthouse Report](https://github.com/italia/design-comuni-wordpress-theme/assets/3976174/2070002d-3fc4-42e9-9b26-8d5ed6f25504)

**Comment by enrimk** [comment]
È che il Servizio per passare deve essere compilato per filo e per segno, in pratica basta saltare qualcosa, e ciao.
Se poi manca il Luogo, si perde già la metà dei campi obbligatori.
Aggiungiamoci [la grana di `addressLocality`](https://github.com/italia/design-comuni-wordpress-theme/issues/291), e il gioco è fatto...

**Comment by mariantanase** [comment]
Il fatto è che tutti i campi obbligatori sono stati inseriti, non capisco il perché...

**Comment by enrimk** [comment]
Ma nell'html della pagina il tag `ld+json` è completo?

**Comment by mariantanase** [comment]
Sembra di si

```
{
                    "@context": "http://schema.org",
                    "@type": "GovernmentService",
                    "name": "Carta d'identit\u00e0 elettronica (CIE)",
                    "serviceType": "Anagrafe e stato civile",
                    "serviceOperator": {
                        "@type": "GovernmentOrganization",
                        "name": ""                    },
                                        "areaServed": {
                        "@type": "AdministrativeArea",
                        "name": "A tutto il territorio del comune"
                    },
                                        "audience": {
                        "@type": "Audience",
                        "audienceType": "La CIE può essere richiesta da tutti coloro (cittadini italiani, comunitari e non) che risultano iscritti nell'Anagrafe della Popolazione Residente del Comune o che, comunque, abbiano, in tale Comune, la loro dimora.Per i cittadini residenti in altro Comune italiano il rilascio della CIE può essere richiesto solo per sopperire a necessità derivanti da gravi e comprovati motivi che non consentono di recarsi presso il proprio Comune di residenza (Circolare Ministero dell'Interno del 05/11/1999) e solo dopo aver ricevuto, da tale Comune, il relativo nulla osta.Per richiedere il rilascio della carta d'identità a nome di un minore, questi deve essere accompagnato allo sportello comunale da chi ha la responsabilità genitoriale (genitori o tutore), muniti di valido documento di riconoscimento e, nel caso del tutore, anche della sentenza di nomina."
                    },
                    "availableChannel": {
                        "@type": "ServiceChannel",
                        "name": "Dove rivolgersi"
                          ,"serviceLocation": {
                            "name": "Ufficio Anagrafe",
                            "address": {
                                "streetAddress": "Via da qui 21",
                                "postalCode": "01234"                                                            }
                        }
                                            }
                }
```

**Comment by fabricius4** [comment]
nella creazione di un servizio che punta all'esterno per accesso tramite spid, il valutatore rimanda un JSON non valido. Non ci sono apostrofi ecc...ma rimane l'errore. Questo è bloccante ai fini dell'asseverazione oppure solo i metatag dei campi obbligatori? Avete suggerimenti su quale e come risolvere in ogni caso questo problema?

**Comment by enrimk** [comment]
@fabricius4 
Vero: se c'è `serviceUrl` ma manca `serviceLocation`, il json non è valido. C'è [questa virgola](https://github.com/enrimk/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-servizio.php#L84C85-L84C86) di troppo.
La PR di cui sopra dovrebbe risolvere anche quello, comunque.

---
La morale forse è che anche il JSON, come l'XML, non è quasi mai una buona idea formarlo con i template di PHP. La via più sicura sarebbe probabilmente fare una bella _dci_json_servizio()_, in cui tutto viene passato attraverso `json_encode()` in un colpo solo.

**Comment by enrimk** [comment]
@mariantanase 
```
"serviceOperator": {
                        "@type": "GovernmentOrganization",
                        "name": ""
```
Il nome del fornitore è in bianco. 
A quanto pare ciò per il validatore è un peccato mortale, esce subito inorridito e si rifiuta di considerare tutto il resto...

**Comment by danimog** [comment]
@enrimk @mariantanase 
per eludere il controllo di serviceOperator.name io ho compilato il campo (non obbligatorio) Codice dell'Ente erogatore (IPA) nei vari servizi.
ma errori su audience.name e areaServed non sono riuscito a toglierli, idee?

il json è dato come corretto. 

versione 1.7.3 del tema wordpress
versione 2.7.2 del validatore

**Comment by enrimk** [comment]
Sì, infatti è quello, _codice IPA_, il campo che viene [usato per il fornitore](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-servizio.php#L72). Campo che fra parentesi si chiama in modo un po' fuorviante, è più un "nome" che un "codice".
Sul fatto che non sia obbligatorio, ma necessario alla validazione... avevo anche pensato [di metterci un default sensato](https://github.com/italia/design-comuni-wordpress-theme/commit/67f29809f598039b0b81a7b3a6b09cf6c9fea9dc#diff-7eba01a5570f0cd9bd3dfb5a0bc40625fdaecffa0c0044e35d159099fd319974L51), ma poi l'ho tolto, perché mi è venuto in mente che forse, da qualche parte nel vasto mondo, dopotutto possano esistere anche servizi senza fornitore identificato, e _da non validare_, e che questo sia effettivamente stato considerato per questa scelta.
Magari però una nota sul campo IPA, a backoffice, circa il suo ruolo nell'asseverazione, sarebbe utile.

I nomi sono **_audience.audienceType_** per "_A chi è rivolto_" (="`destinatari`"), e **_areaServed.name_** per "`copertura_geografica`".
Questo, anche [secondo la documentazione](https://github.com/italia/design-comuni-docs/blob/99ea5b2c1fd4e9daf03718c469202b8a7bde7c90/modello-sito-comunale/template-dati-strutturati-scheda-servizio.html#L11-L18).
Il validatore cerca proprietà diverse?

**Comment by enrimk** [comment]
> Il validatore cerca proprietà diverse?

In effetti... Non conosco _jsonschema_ e metatagAudit.ts non contiene tutta la procedura, [ma questa cosa qui insospettisce parecchio](https://github.com/italia/pa-website-validator/blob/1e05e8f8d3f5eee92864b3594784e92ec9264309/src/audits/municipality/metatagAudit.ts#L332).

**Comment by danimog** [comment]
@enrimk 
in effetti.. qui dà come  required: ["name"]
ma nel json di single-servizio.php il riferimento a name non c'è..

`"audience": {
                        "audienceType": "<?php echo convertToPlain($destinatari); ?>",`

ovviamente mettendo un attributo name "fake" tipo 

` "audience": {
                        "audienceType": "<?php echo convertToPlain($destinatari); ?>",
                        "name":"all"
                    },`

il validatore passa con il 100%....

**Comment by enrimk** [comment]
Bisogna riconoscere che almeno per il validatore, il team [dimostra una certa prontezza](https://github.com/italia/pa-website-validator/pull/399/commits/72cca611bd58cae2307014c1379f286ee1dd5fc3). È arrivata una PR.

**Comment by fabricius4** [comment]
> Sì, infatti è quello, _codice IPA_, il campo che viene [usato per il fornitore](https://github.com/italia/design-comuni-wordpress-theme/blob/ebd5f73f13b9f00bc0fc83504d6a7ef5f0cb2201/single-servizio.php#L72). Campo che fra parentesi si chiama in modo un po' fuorviante, è più un "nome" che un "codice". Sul fatto che non sia obbligatorio, ma necessario alla validazione... avevo anche pensato [di metterci un default sensato](https://github.com/italia/design-comuni-wordpress-theme/commit/67f29809f598039b0b81a7b3a6b09cf6c9fea9dc#diff-7eba01a5570f0cd9bd3dfb5a0bc40625fdaecffa0c0044e35d159099fd319974L51), ma poi l'ho tolto, perché mi è venuto in mente che forse, da qualche parte nel vasto mondo, dopotutto possano esistere anche servizi senza fornitore identificato, e _da non validare_, e che questo sia effettivamente stato considerato per questa scelta. Magari però una nota sul campo IPA, a backoffice, circa il suo ruolo nell'asseverazione, sarebbe utile.
> 
> I nomi sono **_audience.audienceType_** per "_A chi è rivolto_" (="`destinatari`"), e **_areaServed.name_** per "`copertura_geografica`". Questo, anche [secondo la documentazione](https://github.com/italia/design-comuni-docs/blob/99ea5b2c1fd4e9daf03718c469202b8a7bde7c90/modello-sito-comunale/template-dati-strutturati-scheda-servizio.html#L11-L18). Il validatore cerca proprietà diverse?

invece questo: availableChannel.serviceLocation.address.addressLocality
a cosa corrisponde?

**Comment by danimog** [comment]
> invece questo: availableChannel.serviceLocation.address.addressLocality a cosa corrisponde?

dovrebbe corrispondere al campo del back office "Copertura geografica"

**Comment by enrimk** [comment]
> invece questo: availableChannel.serviceLocation.address.addressLocality a cosa corrisponde?

A... (rullo di tamburi)... a _quartiere_!
...Del Luogo, della Sede principale, del primo degli Uffici (canale fisico), del Servizio. [^1]
[Eh già...](https://github.com/italia/design-comuni-wordpress-theme/issues/291) 😶

[^1]: A questo punto mi sembra sempre di sentire cantare Branduardi in sottofondo...

**Comment by enrimk** [comment]
> al campo del back office "Copertura geografica"

Altri problemi, qua. Ma almeno non coinvolgono la validazione, _solo_ la "semantica".

Infatti, nello [schema di riferimento del json](https://github.com/italia/design-comuni-docs/blob/99ea5b2c1fd4e9daf03718c469202b8a7bde7c90/modello-sito-comunale/template-dati-strutturati-scheda-servizio.html#L11-L14), il campo `areaServed` è un [type AdministrativeArea](https://schema.org/AdministrativeArea).
Che, per schema.org, sembra si riferisca a qualcosa di più ufficiale e giurisdizionalmente definito di "le zone coperte da ZTL", come nell'esempio a backoffice.

Inoltre, `areaServed.name` viene da _Copertura geografica_, che in anagrafica è un campo multiriga, e con un editor richtext. Ciò non corrisponde molto alla proprietà _AdministrativeArea::name_ - che è vero che tecnicamente è indicata solo come [_Text_](https://schema.org/Text), apparentemente senza espliciti vincoli di lunghezza o formato, ma non so se è previsto che contenga addirittura dei capoversi, o della formattazione. Sarebbe allora più appropriato _AdministrativeArea::description_ per un oggetto del genere. [^1]

[^1]: E vedo che può infatti essere un [_TextObject_](https://schema.org/TextObject), a differenza di `name`.

**Comment by tomasdimaio** [comment]
> @enrimk in effetti.. qui dà come required: ["name"] ma nel json di single-servizio.php il riferimento a name non c'è..
> 
> `"audience": { "audienceType": "<?php echo convertToPlain($destinatari); ?>",`
> 
> ovviamente mettendo un attributo name "fake" tipo
> 
> ` "audience": { "audienceType": "<?php echo convertToPlain($destinatari); ?>", "name":"all" },`
> 
> il validatore passa con il 100%....

ciao ho fatto la modifica che proponi ma il validatore mi da sempre zero con la seguente dicitura: 

Risultato 
In almeno una delle schede servizio analizzate meno del 50% dei metatag richiesti sono presenti e corretti. |   |  
Pagine nelle quali meno del 50% dei metatag richiesti sono presenti e corretti: | JSON valido | Metatag non presenti o errati

**Comment by enrimk** [comment]
> > ovviamente mettendo un attributo name "fake" tipo
> > ` "audience": { "audienceType": "...", "name":"all" },`

> ciao ho fatto la modifica che proponi ma il validatore mi da sempre zero con la seguente dicitura:

NB @tomasdimaio: quello di @danimog non era una proposta, era un test - e solo un test di uno specifico bug del validatore.  

Il tuo problema può essere diverso: anche se quel particolare tag ora si valida, può benissimo essere che in uno dei servizi manchino dati, abbastanza per non soddisfare il validatore (che è piuttosto severo). 

Tra parentesi, nel frattempo nell'ultima versione del validatore quel bug di _audience_ è stato corretto.

**Comment by tomasdimaio** [comment]
Salve scusatemi ma non riesco proprio ad uscire da questo problema, nonostante compili tutti campi , così come detto in precedenza, il validatore mi da ancora il js non valido, ma soprattutto non mi segnala quali sono i metatag non presenti
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/b2f53ee5-1dd3-4981-abbd-a7ec010c38ec)

**Comment by enrimk** [comment]
@tomasdimaio 
...E soprattutto: hai applicato la #343 ?
Negli indirizzi dei tuoi luoghi c'è un a-capo, rende invalido il JSON.

**Comment by enrimk** [comment]
@zetareticoli 
Perché l'issue non è più un bug?
