### ISSUE TITLE
Notizie nella home sovrapposte

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#376]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho notato solo oggi che la notizia in evidenza nella home tende ad andare sopra le altre notizie coprendo la categoria, sicuramente questo prima non accadeva ma non so se questo errore possa essere collegato all'ultimo aggiornamento.
Pensavo di avere modificato qualcosa io nel CSS ma non ho trovato nulla, per curiosità sono andato a vedere il comune di Sedriano e ho notato lo stesso errore di visualizzazione.

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
Se la notizia è senza immagine, giusto?

**Comment by enrimk** [comment]
L'html della home di WP è radicalmente diverso da quello nelle statiche. E tra parentesi, la disposizione nelle statiche non mi pare meglio, anzi (le 3 card in evidenza [dentro `section#calendario`](https://github.com/italia/design-comuni-pagine-statiche/blob/c58314ca7a1f094d66b8fef21581cbad70d4975c/src/pages/sito/homepage.hbs#L41)? Perché?).
Quindi un eventuale difetto nel css non viene testato ed evidenziato.

Per ora, io ho semplicemente "risolto" così:
```
/* Fix comuni.css */
.card-wrapper.card-overlapping {
	z-index: 1;
}
```

**Comment by Cam-al** [comment]
si pure io ho risolto così, ma prima si vedeva bene e non ho capito da quando è diventato cosi.

**Comment by enrimk** [comment]
Non credo che sia stata una modifica nel codice, non mi pare che recentemente ci siano stati aggiornamenti delle parti che hanno influenza su quel punto.
È più facile che sia cambiato qualcosa nel browser.
Infatti credo che solo Chrome (ed Edge) manifestino il problema, con Firefox mi sembra che non ci sia.

Dev'essere qualcosa di un po'... _arcano_, legato al rendering dei vari "layer" nel browser. Non sono sicuro, ma mi sa che ci sia  qualche connessione con il fatto che il flexbox nella novità in evidenza usa "order" per riposizionare i suoi elementi nelle viste mobile. Magari questo rimanda o anticipa il painting dei vari blocchi e ne altera l'"impilamento" e lo stacking context, chissà.

**Comment by fabricius4** [comment]
> Non credo che sia stata una modifica nel codice, non mi pare che recentemente ci siano stati aggiornamenti delle parti che hanno influenza su quel punto. È più facile che sia cambiato qualcosa nel browser. Infatti credo che solo Chrome (ed Edge) manifestino il problema, con Firefox mi sembra che non ci sia.
> 
> Dev'essere qualcosa di un po'... _arcano_, legato al rendering dei vari "layer" nel browser. Non sono sicuro, ma mi sa che ci sia qualche connessione con il fatto che il flexbox nella novità in evidenza usa "order" per riposizionare i suoi elementi nelle viste mobile. Magari questo rimanda o anticipa il painting dei vari blocchi e ne altera l'"impilamento" e lo stacking context, chissà.

anche su browser Opera da lo stesso problema ma con il [fix](https://github.com/italia/design-comuni-wordpress-theme/issues/376#issuecomment-1758171808) si risolve

**Comment by enrimk** [comment]
> flexbox nella novità
> altera l'"impilamento" e lo stacking context

Infatti una "correzione" alternativa potrebbe essere così:

```css
#novita-in-evidenza + .row {
	isolation: isolate;
}
```

**Comment by zetareticoli** [comment]
> L'html della home di WP è radicalmente diverso da quello nelle statiche

Questo accade perché l'implementazione del template su WP ha richiesto dei cambiamenti rispetto alla versione statica.

**Comment by zetareticoli** [comment]
@Cam-al potresti allegare screeshots del bug?

**Comment by enrimk** [comment]
> > L'html della home di WP è radicalmente diverso da quello nelle statiche
> 
> Questo accade perché l'implementazione del template su WP ha richiesto dei cambiamenti rispetto alla versione statica.

Si può prendere in considerazione di "sincronizzare" le home aggiornando le statiche e riportando là alcune delle modifiche di WP? Per certi versi la struttura di quella zona della home WP sembra anche più "logica".

**Comment by enrimk** [comment]
> potresti allegare screeshots del bug?

È possibile che si sia risolto da sé - o meglio, con gli ultimi aggiornamenti dei browser, da qualche giorno. 
Infatti io non lo vedo più in nessun sito, compreso Sedriano.
A questo punto, sarà stato davvero solo un bug nel rendering engine.

**Comment by Cam-al** [comment]
@zetareticoli ho provato a commentare 
```
/* Fix comuni.css */
.card-wrapper.card-overlapping {
	z-index: 1;}
```
 e adesso non si verifica più l'errore, come diceva @enrimk potrebbe essere qualcosa nel browser
