### ISSUE TITLE
Ricerca indirizzo nella mappa per la tipologia Luogo

### ISSUE THREAD

**Issue by HshMatera** [italia/design-comuni-wordpress-theme#377]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho riscontrato un errore nella creazione di un nuovo luogo nella sezione Posizione GPS quando si ricerca un indirizzo. 
**File not found: API no longer accessible via this URL.**
Come suggerito l'uso dell'URL /search/ e /reverse/ (con barre) non è più supportato. 
Ho risolto il problema modificando le funzioni geocode e reverse in /inc/lib/CMB2-field-Leaflet-Geocoder/assets/js/geocoder.js
eliminando lo / alle righe 372 e 399
`L.Control.Geocoder.jsonp(this.options.serviceUrl + 'search', L.extend({`
`L.Control.Geocoder.jsonp(this.options.serviceUrl + 'reverse', L.extend({`

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
Vedi: #355.

**Comment by zetareticoli** [comment]
@enrimk la #355 è stata portata su `main`, provvederemo a fare un rilascio quanto prima /cc @astagi
