### ISSUE TITLE
Maggiore scelta di colori per avvisi in home page

### ISSUE THREAD

**Issue by matteoInternav** [italia/design-comuni-wordpress-theme#382]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Sarebbe possibile aggiungere una maggior scelta di colori agli avvisi inseribili in home page? Ad esempio **arancione** 

### Motivazione e contesto

 Questa richiesta ci è giunta da numerosi Comuni, in quanto l'arancione e per loro considerato ottimale per gli avvisi relativi alle allerte meteo, piuttosto frequenti

**Comment by mariantanase** [comment]
Si, è possibile aggiungere un altro colore. Se ho tempo faccio una PR
