### ISSUE TITLE
Il tempalte novità riporta le novità in ordine alfabetico

### ISSUE THREAD

**Issue by malikmalhan** [italia/design-comuni-wordpress-theme#383]
### Descrivi il problema

Nel file https://github.com/italia/design-comuni-wordpress-theme/blob/main/template-parts/novita/tutte-novita.php vengono riportate le notizie in ordine alfabetico, probabilmente non funziona il sorting.

Da specifica in https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/architettura-informazione.html#pagine-lista-di-primo-livello le novità devono essere inserito con ordinamento cronologico, ripoto il punto

«Novità» è una sezione che contiene la tipologia di contenuto «Notizia». Queste possono essere notizie, avvisi e comunicati.La pagina deve contenere:
una sezione «Novità in evidenza»;
una sezione di ricerca con l’elenco delle novità ordinate per data, con paginazione;
l’elenco delle categorie per poter navigare ai sottolivelli.

### Includi link o screenshot

https://github.com/italia/design-comuni-wordpress-theme/blob/main/template-parts/novita/tutte-novita.php

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.3

**Comment by enrimk** [comment]
Suggerirei di concentrare la discussione di questo difetto in un issue solo.

È meglio 1) per non disperdere le informazioni, e raccogliere tutte quelle che servono alla correzione,
e 2) perché è più facile che il suggerimento guadagni visibilità e venga, si spera, accolto.

**Comment by malikmalhan** [comment]
ok continuiamo qui https://github.com/italia/design-comuni-wordpress-theme/issues/296
