### ISSUE TITLE
Ordinamento e formattazione data sbagliato nelle novità

### ISSUE THREAD

**Issue by cristina-pontarolo** [italia/design-comuni-wordpress-theme#384]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nella pagina delle novità https://www.comune.tavigliano.bi.it/novita/
le novita NON SONO IN ORDINE DI DATA come avete indficato nella VOSTRA documentazione

### Includi link o screenshot

![ordine-cronologico](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/6fa113a1-208c-4c2c-aaad-e3d717ee1fec)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Firefox

### Che versione del tema stai utilizzando?

1.7.2

**Comment by enrimk** [comment]
Per la verità, anche in quel sito, è proprio in ordine di data che sembrano essere le news - almeno all'inizio.
Poi, caricando le altre via ajax, le cose cambiano (come è stato segnalato già parecchie volte).

**Comment by cristina-pontarolo** [comment]
NO ASSOLUTAMENTE NON SONO IN ORINE DI DATA. L'ULTIMA NEWS è DEL 16 OPTTOBRE, COME PUPI VEERE IN HOME PAGE. INOLTRE SONO 11 MAG 15 MAGGIO E 12 MAGGIO LA SEQUENZA, E NON MI SEMBRA CORRERTTA PER DATA, AL LIMITE SAREBBERO DOVUTE ESERE 15 MAGGIO 12 MAGGIO E 11 MAGGIO...

**Comment by enrimk** [comment]
Nella pagina Novità che tu hai linkato nell'issue, le tre news sono del 13 ott, 23 giu, 15 mag.
Ordine cronologico inverso.

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/93265448/22eea42e-6051-4466-9d47-e6dcb32f48eb)

Però, caricandone altre via ajax l'ordinamento si perde.

E in homepage, invece, il campo _data_ per cui vengono ordinate non è lo stesso della pagina novità. 

Ma tutto questo è già risaputo, e già segnalato da mesi.

**Comment by cristina-pontarolo** [comment]
peccqto che la news del 23 giungo non la veda.

https://www.comune.tavigliano.bi.it/novita/trasparenza-arera/

**Comment by cristina-pontarolo** [comment]
Ho cpaito, adeso che ho visitato le news le vedo
![Screenshot 2023-10-23 at 11-33-44 Novità – Comune di Tavigliano](https://github.com/italia/design-comuni-wordpress-theme/assets/119422587/aa65b0bb-8ec4-483b-a34a-88bfafb5c0c0)
cosa molto strana

**Comment by cristina-pontarolo** [comment]
Ok grazie mille.

**Comment by cristina-pontarolo** [comment]
> peccqto che la news del 23 giungo non la veda.
> 
> https://www.comune.tavigliano.bi.it/novita/trasparenza-arera/

ok e dunque che si fà? resta cosi???? non è un bug comunque?????

**Comment by enrimk** [comment]
Lo è, ed è pure grave.
Però mi stupirebbe che dopo tanti mesi che l'anomalia viene segnalata in mille modi, il team non ne sia già al corrente.
Non sono le segnalazioni tecniche che mancano.

Riguardo a cosa si dovrà fare, e quando, per lo sviluppo futuro di questo progetto che rimane incompleto e difettoso... Domanda legittima, e ormai anche un po' urgente, da rivolgere sicuramente a chi di dovere, nei luoghi opportuni.

**Comment by cristina-pontarolo** [comment]
Quali sono i luoghi opportuni???

**Comment by enrimk** [comment]
Saperlo... Sul tema delle tempistiche di progetto, forse più slack e i forum, che gli issue.

**Comment by zetareticoli** [comment]
Questa issue è un duplicato di #380.

Stiamo lavorando ad un fix per la sezione notizie.

@enrimk ci sono issue meno recenti che possono essere interessate da un fix?

**Comment by enrimk** [comment]
> ci sono issue meno recenti che possono essere interessate da un fix?

Sul tema dell'ordinamento Notizie, ne vedo parecchi segnalati in passato, sempre per lo stesso difetto.
Iniziando dal #17, che è chiuso ma non risolto; e poi:
#136, #163, #192, #296, #332, #383. [^1]

[^1]: Mia opinione: la chiave della soluzione al problema sta in #332 😁 (ovviamente)

**Comment by zetareticoli** [comment]
Resolved in #387
