### ISSUE TITLE
Aggiornamento tardivo delle modifiche del sito

### ISSUE THREAD

**Issue by tomasdimaio** [italia/design-comuni-wordpress-theme#386]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Ho notato che quando faccio delle modifche sul mio backoffice, queste si vedeno subito se sono loggato come amministratore, se esco sul lato pubblico risultano visibile solo dopo alcune ore.
A qualcuno e capitato qualcosa del genere.

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/ac2cb6b5-0068-461a-8ece-bb88be7a9c2c)
come amministratore
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/bd810832-30bc-44b6-8a1a-0f69203c103c)
lato frontend

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by totolabs** [comment]
Per caso hai installato qualche plugin per la gestione delle cache? Solitamente si riscontrano problemi del genere quando c'è installato un plugin per migliorare le performance e non si cancella la cache precedente.

**Comment by tomasdimaio** [comment]
> Per caso hai installato qualche plugin per la gestione delle cache? Solitamente si riscontrano problemi del genere quando è installato un plugin per migliorare le prestazioni e non si cancella la cache precedente.

Grazie della risposta, non ho nessun plugin per la gestione del cache, incredibilmente il sito si aggiorna solo il giorno seguente alla modifica. Utilizzo l'ultima versione del tema 1.7.3

**Comment by enrimk** [comment]
> non ho nessun plugin per la gestione del cache, 

Eppure, un problema con una cache rimane la spiegazione più probabile. Non necessariamente un plugin, ad es. potrebbe essere un servizio fornito dall'hosting.
È molto molto improbabile che questo effetto nasca da un bug del tema.
