### ISSUE TITLE
passaggio da versione 1.62 a 1.7.3

### ISSUE THREAD

**Issue by tomasdimaio** [italia/design-comuni-wordpress-theme#388]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Salve a tutti ho il seguente problema, nel passaggio dalla versione 1.62 del tema all'ultima versione 1.73 in alcune pagine compare il seguente avviso :

**ATTENZIONE**
Il template di questa pagina non è ancora disponibile.

Nel frattempo, puoi controllare se è disponibile la [versione statica](https://italia.github.io/design-comuni-pagine-statiche/) oppure il [layout hi-fi](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/%5BComuni%5D-Modello-sito-e-servizi?type=design&node-id=1%3A1310&t=T24nHc1gRJzlJ7GH-1) su Figma.

[Consulta il documento di architettura dell'informazione](https://designers.italia.it/files/resources/modelli/comuni/adotta-il-modello-di-sito-comunale/definisci-architettura-e-contenuti/Architettura-informazione-sito-Comuni.ods) per costruire il template in autonomia.
vi posto screenshoot.
Purtroppo solo con l'ultima versione il validatore mi da il 100% sui metatag e quindi devo usarla per forza.
Come posso fare
Grazie

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/9453ecbe-9133-468c-93c6-d21df5cdbad2)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.3

**Comment by tomasdimaio** [comment]
> Il tema ufficiale NON ha tutti i template pagina necessari per sviluppare l'intera alberatura. Devi integrare i template mancanti

Strano perchè nella versione 1.6.2 ci sono tutti i template.

**Comment by abmcr** [comment]
La 1.6.2 non l'avevo scaricato: da quando ho iniziato a usare il tema (aprile) ho sempre trovato dei templates mancanti, oltre ad altre features che ho dovuto implementare

**Comment by tomasdimaio** [comment]
Perdonatemi ,ma ceuncontrosenso di fondo, mi spiego e vi faccio notare che nella versione 1.6.2 ci sono tutti i template, ma non funziona la sezione dei luoghi nella ricerca della mappa, contarriamente nella 1.7.3 funziona la sezione dei luoghi ,ma non ci sono i template, aggiungo anche che nella 1.7.3 le modifiche fatte compaiono nel front end dopo un giorno.
A questo punto dico, non sarebbe il caso di avere una versione stabile in tutto le funzioni.
Grazie

**Comment by enrimk** [comment]
@tomasdimaio
No, non ci sono mai stati tutti i template.
Quello a cui ti riferisci tu, è che [dalla vers. 1.7.0 è stato aggiunto l'avviso](https://github.com/italia/design-comuni-wordpress-theme/commit/50df1fa9f6f901575622ce5c6e23595b825d897d) "template non disponibile" a [single.php](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/single.php#L58-L59) e [page.php](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/page.php#L50-L51).
Quelli sono i template di default di WP per la pagina generica e per il dettaglio di ogni tipo contenuto. Perciò ora, se il tipo contenuto non è già stato esplicitamente implementato, o previsto dal tema, compare l'avviso invece dei suoi dati; e anche in tutte le pagine descrittive.
  
>  [...] dico, non sarebbe il caso

🤷‍♂️

**Comment by zetareticoli** [comment]
@tomasdimaio come riportato da @enrimk , quei templates non sono mai stati rilasciati, difficile potessero esserci nella versione precedete.

Forse li avevi creati autonomamente e aggiornando il tema hai perso qualche file?
