### ISSUE TITLE
All'attivazione tema, le pagine predefinite non hanno il template corretto 

### ISSUE THREAD

**Issue by enrimk** [italia/design-comuni-wordpress-theme#392]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Quando il tema viene attivato, vengono create alcune pagine predefinite (Amministrazione, Novità, Servizi, Vivere il Comune...), la cui lista sta in [comuni_pagine.json](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/inc/comuni_pagine.json).
A ciascuna di queste pagine, dovrebbe venire attribuito il rispettivo template speciale, tra quelli in [page-templates/](https://github.com/italia/design-comuni-wordpress-theme/tree/main/page-templates).   

Questo però non avviene: le pagine sono create, e rimangono con il template di pagina di default.

----

La causa è che nel json, [nella prop. "template_name" è stato erroneamente usato il _titolo_ del template](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/inc/comuni_pagine.json#L55C29-L55C45), invece del _nome del file_ del template (senza estensione). 

Infatti:
- il postmeta `_wp_page_template` [deve contenere il path completo del file](https://developer.wordpress.org/reference/functions/get_page_template_slug/#more-information) del template;
- alla creazione delle pagine, [dci_create_page_template() forma quel path](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/inc/activation.php#L479) usando "template_name".

_NB_
In certe condizioni, il bug potrebbe non apparire in tutte le pagine. Ad esempio, su SO con FS non case-sensitive (Windows, MacOS) e qualora il nome del file non abbia spazi e differisca dal titolo solo per il case (ad es., "Amministrazione").

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.4

**Comment by tomasdimaio** [comment]
Ragazzi, getto la spugna, ho eseguito tutto ciò che avete detto,ma il risultato non cambia
versione 1.7.4
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/dec5a00d-6122-4d48-a2b3-fa8ab8e4cce0)
versione 1.6.2
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/7682eb17-2d74-4355-8218-571cda4db06a)
Io lascerei anche la versione 1.6.2 ma purtroppo non passa il validatore per altri motivi (luogo non funziona ed errore sui metatag)
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/351d896f-be0a-4ae2-9663-68775b19f7e6)

Acetto suggerimenti almeno per toglire quella maledetta scritta dalle pagine in amministrazione
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/5e37c017-50f3-450c-98b0-821cc7a9f3be)

GRAZIE

**Comment by enrimk** [comment]
> ho eseguito tutto ciò che avete detto,ma il risultato non cambia versione 1.7.4 

Il problema che segnali però non c'entra molto con questo issue in particolare, e non fornisce info molto utili ad approfondire il bug descritto qui.

---
La discussione relativa al problema tuo stava in #388?
Valgono ancora [le cose spiegate nel thread di quell'issue](https://github.com/italia/design-comuni-wordpress-theme/issues/388#issuecomment-1785496111).
In particolare: nel tema MANCA ancora un template anche per il dettaglio dell'Unità Organizzativa. Quindi WP usa il template di default, che è [single.php](https://github.com/italia/design-comuni-wordpress-theme/blob/31628b8a3d5806f773e0cb0c6fb7be08d9cd5c76/single.php#L58-L59). In quel template, c'è l'avviso "sito demo" (che a mio parere [è sbagliato che stia lì, ed è sbagliato come è formulato](https://github.com/italia/design-comuni-wordpress-theme/issues/371) - ma è un altro discorso).
Soluzione: implementare _single-unita_organizzativa.php_. A riguardo c'è anche una PR aperta, se credi, da cui magari prendere spunto.
