### ISSUE TITLE
Errore 404 nella pagine di archivio Eventi e Luoghi

### ISSUE THREAD

**Issue by Cam-al** [italia/design-comuni-wordpress-theme#395]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Dopo l'aggiornamento alla versione 1.7.4 non funzionano più le pagine di archivio di Eventi e Luoghi.
I template per le pagine di archivio Eventi e Luoghi che ho realizzato funzionavano fino a l'ultima versione, adesso quando provo a visualizzare la pagina mi da la pagina 404.
Ho modificato /inc/admin/tipologie/tipologia_evento.php cosi
`$args = array(
        'label'                 => __( 'Evento', 'design_comuni_italia' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor' ),
        'hierarchical'          => false,
        'public'                => true,
        'menu_position' => 5,
        'menu_icon'             => 'dashicons-tickets-alt',
        'has_archive'           => true,
        'rewrite' => array('slug' => 'vivere-il-comune/eventi', 'with_front' => false),
        'capability_type' => array('evento', 'eventi'),
        'map_meta_cap'    => true,
        'description'    => __( "Tipologia che struttura le informazioni relative a un evento di interesse pubblico pubblicato sul sito di un comune", 'design_comuni_italia' ),
    );`
lo stesso per la tassonomia che invece funziona ancora correttamente

Invece dentro la pagina Vivere il comune ho modificato /child/template-parts/vivere-comune/eventi.php  per mettere il collegamento alla pagina di archivio così :
`<div class="d-flex justify-content-end">
                <a href="<?php echo get_post_type_archive_link( 'evento' ); ?>" class="btn btn-outline-primary full-mb" aria-label="aria-label" data-element="live-button-events">
                    Tutti gli eventi 
                    <svg class="icon icon-primary icon-xs ml-10">
                      <use href="#it-arrow-right"></use>
                    </svg>
                </a>
            </div> <?php } ?>`
 quando clicco il pulsante "Tutti gli eventi" il percorso è giusto (/vivere-il-comune/eventi/) ma da la pagina 404, ha sempre funzionato ma adesso non riesco a capire cosa sto sbagliando o se manca qualcosa.
Ci sono state modifiche che potrebbero essere collegate a questo problema dalla versione  1.7.1 alla 1.7.4 >(sono quasi certo che funzionasse fino alla 1.7.3)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.4

**Comment by enrimk** [comment]
Be', non proprio un _bug_ del tema, visto che il tema ancora quegli archivi non li implementa, e costringe a una modifica. Il che è il vero difetto, e ormai un difetto grave, ma un "buco", più che un "bug". 

`has_archive => true` dovrebbe essere tutto quello che serve.
Hai provato a fare un refresh dei permalink? Da backoffice, o anche con `wp rewrite flush`? 
Può darsi che prima della tua ri-modifica si siano resettati allo "standard".

**Comment by Cam-al** [comment]
Grazie, ho risolto aggiornando i permalink.
`has_archive => true`  c'era già, e sarebbe utile se fosse già cosi nel tema invece di doverlo mettere ogni volta
