### ISSUE TITLE
Scheda Servizi

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#4]
Ho notato 4 problematiche:
~~1. A prescindere del testo inserito nel campo "**Introduzione canale digitale**", viene mostrato sempre il testo "_Puoi richiedere l’iscrizione alla Scuola dell’infanzia direttamente online tramite identità digitale_";~~
~~2. Lo stessa cosa con il testo "**Introduzione canale fisico**". Al posto del testo personalizzato, viene mostrato "_Puoi prenotare un appuntamento e presentarti presso gli uffici._"~~
3. Nella scheda "Tempi e scadenze" il campo "**Fasi del servizio**" non dovrebbe essere un campo obbligatorio, ad esempio per il rilascio delle CIE.
~~4. L'immagine caricata non viene mostrata (JPG);~~

**Comment by mariantanase** [comment]
Risolto anche il punto 4, non so come fare un nuovo pull-request...

**Comment by zetareticoli** [comment]
Ciao @mariantanase, grazie per le segnalazioni e per aver contribuito alla risoluzione di uno dei problemi indicati. 
Lo spirito con cui questi prodotti sono stati creati è anche quello di ricevere i contributi dalla community.

**Comment by mariantanase** [comment]
Ciao @zetareticoli ,
Capisco benissimo che è stato un grosso lavoro di squadra la creazione di questo tema per WP e lo apprezzo molto.
Purtroppo non conosco WordPress, ma cerco di contribuire anch'io con quello che posso per avere un prodotto più stabile e migliore.
Grazie

**Comment by zetareticoli** [comment]
@mariantanase c'è la PR #23 che correggerà questa issue

**Comment by mariantanase** [comment]
> @mariantanase c'è la PR #23 che correggerà questa issue

No, quella PR correge la issue #15
