### ISSUE TITLE
Il pulsante 'carica altri risultati' non funziona

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#400]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

All'interno della pagina Notizie quando si fa click sulla voce "carica altri risultati" restituisce 'undefined' come da immagine allegata. Ho controllato template-parts/search/more-results.php , inc/load_more.php e risulta tutto corretto. 

### Includi link o screenshot

![Immagine](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/a5f5bb5b-b52c-4410-bbaf-cbe841bff34c)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.1

**Comment by enrimk** [comment]
Però non credo che faccia così nella versione attuale del tema, giusto?

**Comment by fabricius4** [comment]
stessa versione per un altro comune funziona. Non capisco

**Comment by enrimk** [comment]
Prova a vedere nella console del browser se assets/js/load_more.js si lamenta di qualcosa; o anche come si svolge la richiesta ajax verso admin-ajax.php per l'_action_ "load_more" (nel pannello Network dei devtools).

**Comment by enrimk** [comment]
Se il messaggio di errore in console viene effettivamente da load_more.js (dallo screenshot non si vede) e la _promise_ è quella del fetch() che avviene lì, sembrerebbe che ci sia in effetti una qualche interruzione.
Nel pannello network però dovresti cercare admin-ajax.php (nell'altro screenshot che alleghi c'è la request per il file .js, non per la chiamata ajax).

**Comment by fabricius4** [comment]
> Se il messaggio di errore in console viene effettivamente da load_more.js (dallo screenshot non si vede) e la _promise_ è quella del fetch() che avviene lì, sembrerebbe che ci sia in effetti una qualche interruzione. Nel pannello network però dovresti cercare admin-ajax.php (nell'altro screenshot che alleghi c'è la request per il file .js, non per la chiamata ajax).

![ajax](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/72cd4e3c-28ed-49f1-abaf-a0727bb83274)

**Comment by enrimk** [comment]
HTTP status 200. Mi sarei aspettato qualcosa di più anomalo; invece, sembra ok.

Una ricerca veloce sul web su quell'errore non dà niente di solido; c'è chi lo lega alle policy CORS (ma il dominio qui sarà lo stesso) e chi a certe estensioni del browser, o a entrambi...

Per caso, cambia qualcosa con un altro browser? O su una copia in un altro server di sviluppo, o locale?

**Comment by fabricius4** [comment]
> HTTP status 200. Mi sarei aspettato qualcosa di più anomalo; invece, sembra ok.
> 
> Una ricerca veloce sul web su quell'errore non dà niente di solido; c'è chi lo lega alle policy CORS (ma il dominio qui sarà lo stesso) e chi a certe estensioni del browser, o a entrambi...
> 
> Per caso, cambia qualcosa con un altro browser? O su una copia in un altro server di sviluppo, o locale?
> 
> Sarebbe interessante comunque vedere l'effettivo contenuto del risultato della chiamata ajax (il tab Response del dettaglio sopra).
![response](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/5e8d7c74-7be4-4c02-af6b-b0d16127bba1)

**Comment by enrimk** [comment]
La risposta allora c'è, ma è... sbagliata. 😁
Nel senso che la chiamata ajax viene ricevuta e il sito risponde, ma con un esito volutamente "annullato" da qualche tipo di filtro di sicurezza.
Forse c'è qualcosa qui che si aspetta un _[nonce](https://developer.wordpress.org/apis/security/nonces/)_? Anche se probabilmente in questo caso sembrerebbe una precauzione eccessiva. 

In sostanza, dovresti controllare tra i plugin installati nel sito (eventualmente, se non riesci in altro modo, facendo la prova base per individuare il responsabile: disattivarli a uno a uno).

**Comment by fabricius4** [comment]
Beccatto. si tratta di Essentials addons for Elementor. Ora tutto funziona
