### ISSUE TITLE
aggiornamento alla versione 1.7.5

### ISSUE THREAD

**Issue by tomasdimaio** [italia/design-comuni-wordpress-theme#402]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Nell'aggiornare il tema all'ultima versione1.7.5 mi compare di nuovo la scritta "ATTENZIONE Questo è un sito demo e il template di questa pagina non è ancora disponibile."

### Includi link o screenshot

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/849ffe4f-ca96-41a5-b0c3-8152428d852b)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by enrimk** [comment]
Quali sono esattamente le operazioni che hai eseguito per l'aggiornamento?
Hai solo sostituito i file nella cartella, o hai disattivato/riattivato il tema, ecc.?

**Comment by tomasdimaio** [comment]
> disattivato/riattivato il tema

si aveva il modello di pagina corretto

**Comment by tomasdimaio** [comment]
ho installato il tema 1.7.5 da carica tema, e poi  attivato direttamente da aspetto- tema -attiva

**Comment by abmcr** [comment]
ma su che template pagina succede? avrai mica sovrascritto un template pagina che avevi modificato MA direttamente dentro il tema e non un chid?

**Comment by tomasdimaio** [comment]
vi faccio vedere, in tempo reale, la stessa pagina con la versione 1.6.2

![image](https://github.com/italia/design-comuni-wordpress-theme/assets/43476559/a6e8cf26-1d8d-483e-a675-38fed2a5cbf2)

**Comment by abmcr** [comment]
ma che template sta usando quella pagina?

**Comment by enrimk** [comment]
> ma che template sta usando quella pagina?

Di sicuro, non il template "Amministrazione".
Sembra proprio il template di pagina di default. Ovvero, lo stesso che dalla 1.7.0 ha il famigerato avviso "sito demo".

**Comment by totolabs** [comment]
@tomasdimaio non so se hai già risolto, ma per risolverlo credo basti tornare nella pagina col problema, modificare il template utilizzato negli attributi della pagina (selezionandolo dal menù a tendina) ed aggiornare la pagina.

Nel caso della pagina Amministrazione il template è proprio "amministrazione".
![image](https://github.com/italia/design-comuni-wordpress-theme/assets/109132513/7dc57f69-5c01-462f-ab4f-e77f0ec95180)
