### ISSUE TITLE
Template tipi documento

### ISSUE THREAD

**Issue by fed2790** [italia/design-comuni-wordpress-theme#404]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Volevo capire come creare il template per i vari tipi documento come ad esempio Accordo tra enti, Dataset etc

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.5

**Comment by valeriot30** [comment]
In teoria dovrebbe essere sufficiente, a partire dal tema originale, modificare queste righe in "inc/admin/tassonomie/tassonomia_tipi_documento.php"

`$args = array(
        'hierarchical'      => true,
        'labels'            => $labels,
        'public'            => true, //enable to get term archive page
        'show_ui'           => true,
        'show_admin_column' => true,
        'query_var'         => true,
        'has_archive'           => true,    //archive page
        //'rewrite'           => array( 'slug' => 'tipo-documento' ),
        'capabilities'      => array(
            'manage_terms'  => 'manage_tipi_documento',
            'edit_terms'    => 'edit_tipi_documento',
            'delete_terms'  => 'delete_tipi_documento',
            'assign_terms'  => 'assign_tipi_documento'
        )
    );`

E creare un file nella root directory denominato "taxonomy-tipi_documento.php" con il seguente contenuto:
`<?php
/**
 * Archivio tassonomia Tipi Documento
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/#custom-taxonomies
 * @link https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse.html
 *
 * @package Design_Comuni_Italia
 */

get_header();
?>

<main>
	<div class="container" id="main-container">
		<div class="row justify-content-center">
			<div class="col-12 col-lg-10">
				<?php get_template_part("template-parts/common/breadcrumb"); ?>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row justify-content-center row-shadow">
			<div class="col-12 col-lg-10">
				<div class="cmp-hero">
					<section class="it-hero-wrapper bg-white align-items-start">
						<div class="it-hero-text-wrapper pt-0 ps-0 pb-4 pb-lg-60">
							<h1 class="text-black" data-element="page-name"><?php echo single_term_title( '', false ); ?></h1>
							<?php the_archive_description('<div class="hero-text"> <p>','</p> </div>'); ?>
						</div>
					</section>
				</div>
			</div>
		</div>
	</div>

	<div class="bg-grey-card py-5">
		<div class="container">

			<?php if ( have_posts() ) : ?>
			<div class="row g-4">
				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'template-parts/' . 'documento/cards-list' ); ?>

				<?php endwhile; ?>
			</div>

			<div class="row my-4">
				<nav class="pagination-wrapper justify-content-center col-12" aria-label="Navigazione pagine">
					<?php echo dci_bootstrap_pagination(); ?>
				</nav>
			</div>
			<?php else : ?>
				<?php get_template_part( 'template-parts/content', 'none' ); ?>
			<?php endif; ?>

		</div>
	</div>

	<?php get_template_part("template-parts/common/valuta-servizio"); ?>
	<?php get_template_part("template-parts/common/assistenza-contatti"); ?>

</main>

<?php
get_footer();`

Spero sia di aiuto.
