### ISSUE TITLE
Creare sottocategorie

### ISSUE THREAD

**Issue by luciox96** [italia/design-comuni-wordpress-theme#406]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno a tutti, 

Volevo chiedervi se fosse possibile creare delle sottocategorie.
Cioè, andare per in "Servizi" avere le varie categorie e cliccando per esempio su "Ambiente" avere altre 3 o 4 sottocategorie come ad esempio: Ambiente 1, ambiente 2, ambiente 3, ec... (ognuna con i vari servizi assegnati)

### Includi link o screenshot

![screen servizi](https://github.com/italia/design-comuni-wordpress-theme/assets/128592652/2a227a7d-6379-459b-a541-3c2220a48598)
![screen servizi](https://github.com/italia/design-comuni-wordpress-theme/assets/128592652/009561e2-dfd5-4ae7-8a3f-d12032b6290e)

### Su quale sisitema operativo stai riscontrando il problema?

Windows, macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.6.2

**Comment by zetareticoli** [comment]
Ciao @luciox96 , non credo che si possano creare sottocategorie di terzo livello
