### ISSUE TITLE
Segnalazione asseveratori

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#408]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Riporto la segnalazione di non conformità da parte degli asseveratori:
La pagina https://www.comune.XXX.XX.it/novita/orizzonte-savuto/ non rispetta il criterio Buone pratiche in quanto la posizione indicata dalla breadcrumb non è coerente con il contenuto della pagina e con l’organizzazione delle informazioni richiesta dal modello dell'architettura dei siti comunali. La pagina dovrebbe essere contenuta nella sezione Home / Novità / Notizie / e la breadcrumb dovrebbe ad esempio essere: Home / Novità / Notizie / Orizzonte Savuto

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.4

**Comment by claudiopizzillo** [comment]
Lo avevo notato. Ho dovuto modificare il file breadcrumb.php in inc aggiungendo questo codice dopo la lina 379:

`				if (get_post_type() == 'notizia') {
					$this->items[] =  "<a href='".home_url("notizia")."'>".__("Notizie", "design_comuni_italia")."</a>";
					$terms = get_the_terms(get_the_ID(),'tipi_notizia');
					if($terms){
					  foreach ($terms as $term) {
						  $this->items[] = sprintf( '<a href="%s">%s</a>', esc_url( get_term_link( $term, 'tipi_notizia' ) ), $term->name );
					  }
					}
					$this->items[] = get_the_title();
					return;
				}
`

**Comment by fabricius4** [comment]
> Lo avevo notato. Ho dovuto modificare il file breadcrumb.php in inc aggiungendo questo codice dopo la lina 379:
> 
> ` if (get_post_type() == 'notizia') { $this->items[] = "<a href='".home_url("notizia")."'>".__("Notizie", "design_comuni_italia")."</a>"; $terms = get_the_terms(get_the_ID(),'tipi_notizia'); if($terms){ foreach ($terms as $term) { $this->items[] = sprintf( '<a href="%s">%s</a>', esc_url( get_term_link( $term, 'tipi_notizia' ) ), $term->name ); } } $this->items[] = get_the_title(); return; } `
> 
> Però sto lavorando sul tema e non nel child. Soluzione per il child?

grazie mille, si io utilizzo il tema genitore.

**Comment by claudiopizzillo** [comment]
Bug trovato, il codice deve esssere così:
`				if (get_post_type() == 'notizia') {
					$this->items[] =  "<a href='".home_url("novita")."'>".__("Novit&agrave;", "design_comuni_italia")."</a>";
`

**Comment by zetareticoli** [comment]
@fabricius4 la PR #409 incude il fix indicato da @claudiopizzillo ?

**Comment by Cam-al** [comment]
Il breadcrumb sembra sbagliato anche in uffici , luoghi ed eventi. Qualcuno ha riscontrato problemi per queste sezioni in fase di asseverazione ? 
Se si, come avete risolto ?

**Comment by tomasdimaio** [comment]
> Il breadcrumb sembra sbagliato anche in uffici , luoghi ed eventi. Qualcuno ha riscontrato problemi in queste sezioni in fase di asseverazione? Se sì, come hai risolto?

Mi accodo alla richiesta , qualcuno ha risolto, grazie?

**Comment by enrimk** [comment]
> modificare il file breadcrumb.php in inc aggiungendo questo codice dopo la lina 379:

Ho paura che si sia arrivati a questo punto, con dei breadcrumb del tutto difettosi, anche perché si è pensato di correggere aggiungendo, strato su strato, invece di cominciare a togliere (i difetti nelle modifiche iniziali al modulo originario).

> Però sto lavorando sul tema e non nel child. Soluzione per il child?

Probabilmente da un child la cosa meno invasiva è sfruttare [questo filtro](https://github.com/italia/design-comuni-wordpress-theme/blob/c88ddf906164b612b0edcf14bca4675f0d5d2e24/inc/breadcrumb.php#L36C31-L36C56), e sostituire l'intera classe - con una che ne deriva e che in override corregge i metodi ereditati.

[Un altro filtro](https://github.com/italia/design-comuni-wordpress-theme/blob/c88ddf906164b612b0edcf14bca4675f0d5d2e24/inc/breadcrumb.php#L492C48-L492C70) che in origine era disponibile non lo è praticamente più perché spesso non ci si arriva.
[Un altro ancora](https://github.com/italia/design-comuni-wordpress-theme/blob/c88ddf906164b612b0edcf14bca4675f0d5d2e24/inc/breadcrumb.php#L253C33-L253C49) filtra tutta la stringa di html, il che è scomodo.
