### ISSUE TITLE
design italia tema comuni

### ISSUE THREAD

**Issue by rietivincenzo** [italia/design-comuni-wordpress-theme#414]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Proposta

Del tema wordpress design italia tema comuni è possibile fare un'istallazione senza i contenuti dimostrativi?
La presenza di content type articoli , pagine e quanto di altro già presente possono rappresentare un problema quando esistono siti già sviluppati in prercedenza con wordpress.
In oltre il tema può essere utilizzato per creare siti legati al comune ma che non siano il sito principale del Comune e in questi casi i contenuti di esempio o sono poco utili.
Vi ringrazio per l'attenzione sperando in una soluzione al mio problema

### Motivazione e contesto

La corrente versione del tema comuni si presta a molti altri usi legati all'informazione del comune tuttavia i dati di esempio possono rappresentare un limite

**Comment by zetareticoli** [comment]
Ciao @rietivincenzo , il tema WP in questione è stato sviluppato adhoc per i siti dei Comuni. 

Nulla vieta di prenderlo _as is_ e di riadattarlo ad un'altra tipologia di sito, perché il codice è pubblico e open.

In questo caso comunque l'onere del _porting_ è a carico di chi deve implementare un progetto diverso da quello per cui è stato creato.
