### ISSUE TITLE
Numero notizie in home 

### ISSUE THREAD

**Issue by lucianoviro** [italia/design-comuni-wordpress-theme#416]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Sia dal pannello in configurazione che dal file tutte-novita.php modificando il parametro del numero di post il caricamento rimane continuo fino a 100post per poi entrare "Carica altri risultati"

<?php
global $the_query, $load_posts, $load_card_type;

	$max_posts = isset($_GET['max_posts']) ? $_GET['max_posts'] : 6;
    $load_posts = 6;
    $query = isset($_GET['search']) ? dci_removeslashes($_GET['search']) : null;
    $args = array(
        's'         => $query,
        'post_type' => 'notizia',
        'orderby' => 'date',
        'order' => 'DESC'
    );

    $the_query = new WP_Query( $args );
    $posts = $the_query->posts;

 
?>

Qualcuno ha già riscontrato il problema? come posso fixarlo?

Grazie mille
Luciano

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Chrome

### Che versione del tema stai utilizzando?

1.7.5

**Comment by mariantanase** [comment]
In 'home' possono essere visualizzate (come impostazione predefinita) 0, 3 o 6 notizie. 
Non esiste alcun "Carica altri risultati".
