### ISSUE TITLE
Attivazione Tema, pagine senza template predefinito non assegnate correttamente.

### ISSUE THREAD

**Issue by xenio** [italia/design-comuni-wordpress-theme#425]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

All'attivazione del tema le pagine che non hanno un template assegnato su: https://github.com/italia/design-comuni-wordpress-theme/blob/60b9764d72751d10328f2237091e717cf7ca3e25/inc/comuni_pagine.json#L13

effettivamente non gli viene assegnato un template predefinito per via della verifica non corretta su:

https://github.com/italia/design-comuni-wordpress-theme/blob/60b9764d72751d10328f2237091e717cf7ca3e25/inc/activation.php#L495

La if per la verifica dovrebbe essere con il parametro $template passato dalla funzione non $new_page_template che non sarà mai empty.

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.7.5

**Comment by enrimk** [comment]
Vero!
Però più che il confronto nell'`if`, è l'assegnazione di `$new_page_template` che va corretta?
Cioè, gli dovrebbe essere consentito di essere vuota.
Mentre ora, come tu dici, si assegna sempre un template, anche se inesistente.

https://github.com/italia/design-comuni-wordpress-theme/blob/60b9764d72751d10328f2237091e717cf7ca3e25/inc/activation.php#L479
Meglio se fosse:
```php
     $new_page_template = $template? 'page-templates/'.$template.'.php' : '';
```

Nel json i `template_name` contengono solo lo slug del template, non l'intero path come richiesto dal postmeta '_wp_page_template', e dunque un path deve pur essere formato. Solo se il template c'è, però.
