### ISSUE TITLE
Documenti collegati (in documento pubblico) non funzionanti

### ISSUE THREAD

**Issue by Lucafe1311** [italia/design-comuni-wordpress-theme#430]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
all'interno della pagina single-documento-pubblico, la sezione dei documenti collegati presenta un bug: le card mostrano tutte il titolo del documento pubblico attualmente aperto e anche il collegamento punta al documento attualmente aperto.

La pagina genera un numero di card pari al numero dei documenti collegati, ma ogni card punta alla stessa pagina (quella attuale)

### Includi link o screenshot

![300027835-f5d628e4-23ef-4819-b4de-c8f1e92cdaef](https://github.com/italia/design-comuni-wordpress-theme/assets/166508344/1a268fa2-5252-4416-aa82-2c3eae86cde0)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.9.0

**Comment by enrimk** [comment]
Segnalato anche nel #294.
A quanto pare, _wontfix_.
