### ISSUE TITLE
Ancora errore di breadcrumb segnalate da asseveratori

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#436]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

gli asseveratori hanno indicato errori sulle breadcrumb come di seguito:
1. Buone pratiche - attributi obbligatori DOCUMENTO: La pagina https://www.comune.xxx.xx.it/documento_pubblico/documento-pubblico-inizio-mandato/ ha come breadcrumb Home/Documenti pubblici/Modulistica/Documento Pubblico Inizio Mandato mentre dovrebbe essere Home/Amministrazione/Documenti/Modulistica/Documento Pubblico Inizio Mandato nella pagina
2. Buone pratiche - attributi obbligatori LUOGO: Nella pagina https://www.comune.xxx.xx.it/vivere-il-comune/luoghi/centro-storico/ la breadcrumb è "Home/Vivere il Comune/Centro Storico" mentre dovrebbe essere "Home/Vivere il Comune/Luoghi/Centro Storico" e così anche per gli altre pagine della sezione Luoghi nella pagina
3. Buone pratiche - attributi obbligatori UFFICIO: La breadcrumb riporta "Home/Amministrazione/Ufficio Ragioneria" mentre dovrebbe essere "Home/Amministrazione/Ufficio/Ufficio Ragioneria" nella pagina

e così via. 
E' possibile risolvere definitivamente questo problema? Altrimenti c'è il rischio di non passare

Allego un solo screen come esempio

### Includi link o screenshot

![Immagine](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/a9d29a4a-80f0-432f-b484-67e4bbf0b86c)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.10

**Comment by fabricius4** [comment]
questa la possibile soluzione che al momento funziona [https://github.com/fabricius4/design-comuni-wordpress-theme/commit/56fd59901152aec6b46da02e3bb3579b61b77d4a](url)

**Comment by enrimk** [comment]
Difetto annoso (#398, #408).

La soluzione, a quanto pare, viene complicata da almeno un paio di fattori.

Il primo e principale è che la libreria BreadcrumbTrail è stata integrata inizialmente con delle modifiche che la snaturano e ne rompono il comportamento originario - come correttamente puntualizzato anche [nel primo degli issue](https://github.com/italia/design-comuni-wordpress-theme/issues/398#issue-1983954632) citati sopra. Con il corollario che tutte le ulteriori toppe e aggiunte per adattarla a tutti i singoli casi particolari confondono il quadro e non ne migliorano l'ordine del codice.

L'altro fattore, penso, è che ad oggi non sono state ancora definite al 100% tutte le pagine che compaiono nei path, come tipo di _vista_ in Wordpress. Cos'è "Luoghi", o "Uffici"? Una _page_, un archivio? Interpretazione libera?
E comunque, il problema tecnico dipende da scelte diverse in diversi punti, alcune ancora ambigue, ed è difficilmente risolvibile con una singola correzione a un singolo modulo (e infatti le correzioni qui sono... personali, e difficili da condividere su GH).

**Comment by enrimk** [comment]
Riassumendo: personalmente, ho risolto togliendo quasi tutte le customizzazioni a BreadcrumbTrail, e correggendone i parametri di configurazione. Ma funziona _nel mio setup_. Ad esempio, per me "Luoghi" ecc. sono archivi di tassonomia.

**Comment by fabricius4** [comment]
case 'Vivere il comune' :
                        $this->items[] =  "<a href='".home_url("vivere-il-comune")."'>".__("Vivere il Comune", "design_comuni_italia")."</a>";
						$this->items[] = "<a href='".home_url("vivere-il-comune/luoghi")."'>".__("Luoghi", "design_comuni_italia")."</a>";
                        $this->items[] = get_the_title();
                        return;
                        break; 
come si può adattare questo pezzo di codice a seconda che sia un evento o un luogo?

**Comment by enrimk** [comment]
> come si può adattare questo pezzo di codice a seconda che sia un evento o un luogo?

Non si può, senza pasticciare e complicare ulteriormente. Per questo, _io lì ho cavato via tutto o quasi_, [da qui a qui](https://github.com/italia/design-comuni-wordpress-theme/blob/e7268848af0f57029b787d457abf3752e2079eb6/inc/breadcrumb.php#L362-L409). Perché oltretutto, a ben guardare, è anche codice inutile. Ho lasciato giusto i casi delle U.O. e dell'Amministrazione, che sono gruppi "misti".

Per me i tipi luogo ed evento sono semplici archivi di tassonomie, che vengono gestite nativamente da BreadcrumbTrail, basta dichiararle nei parametri:
```diff
--- a/inc/breadcrumb.php
+++ b/inc/breadcrumb.php
@@ -139,1 +139,7 @@ class Breadcrumb_Trail {
-			'post_taxonomy'   => array(),
+			'post_taxonomy'   => array(
+				'notizia' => 'tipi_notizia',
+				'servizio' => 'categorie_servizio',
+				'documento_pubblico' => 'tipi_documento',
+				'luogo' => 'tipi_luogo',
+				'evento' => 'tipi_evento',
+			),
```

**Comment by fabricius4** [comment]
ti ringrazio per tutte le dritte. Come dicevi tu ho dovuto customizzare il file functions.php e relativi template implementando le nuova breadcrumb personalizzate;  inc/breadcrumb.php e cosi via. Lavoraccio ma al momento sembra girare.
