### ISSUE TITLE
ERRORE C.SI 1.3 E C.SI. 2.2 Validatore

### ISSUE THREAD

**Issue by fabricius4** [italia/design-comuni-wordpress-theme#437]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

l'app di validazione riporta queste due non conformità quando in realtà le schede servizio sono compilate in tutti i loro campi. 

### Includi link o screenshot

![Immagine2](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/d040c908-a97e-4283-9fcf-1b66e37ca9f9)
![Immagine](https://github.com/italia/design-comuni-wordpress-theme/assets/128590137/21fffc7d-f2da-4d47-942f-a1fd88580e10)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.10

**Comment by fabricius4** [comment]
ho risolto facendo puntare a unità-organizzativa/card-full.php dove è presente il data-element

**Comment by enrimk** [comment]
> ho risolto facendo puntare a unità-organizzativa/card-full.php dove è presente il data-element

Fatto sta però che il bug è reale, ed è nella versione attuale del tema.
Per ora, non chiuderei questo issue.

La 1.10.0, un po' di soppiatto, [ha introdotto un decisa ristrutturazione della card U.O.](https://github.com/italia/design-comuni-wordpress-theme/commit/96278a5ccf576a1884a93fe6582d710960167f73?diff=unified&w=1#diff-cd897e75bd1326b6265035a92a963d622f1e6de9f31db86fef60f69790785300), forse non tenendo pienamente conto che oltre che nel Luogo viene usata altrove, e in particolare nei Servizi.

La cosa un po' particolare del template della card, è che ne contiene due versioni diverse, distinte con un flag "`$with_border`"  (che, tra parentesi, è di per sé una cosa molto discutibile, e andrebbe proprio corretta - qui e nelle altre card analoghe).
Nella 1.10, in mezzo agli altri cambiamenti non documentati sulla card, il _data-element_, che [prima stava in una delle due versioni](https://github.com/italia/design-comuni-wordpress-theme/blob/f47a5c59fb563f98fbd311de546f6e206cc91d0a/template-parts/unita-organizzativa/card.php#L25), per qualche motivo è stato [spostato nell'altra](https://github.com/italia/design-comuni-wordpress-theme/blob/96278a5ccf576a1884a93fe6582d710960167f73/template-parts/unita-organizzativa/card.php#L43). Che è quella che [il template single-servizio.php NON usa](https://github.com/italia/design-comuni-wordpress-theme/blob/e841b4685839358127ade07cb449a3c0cc3130f2/single-servizio.php#L412).
