### ISSUE TITLE
Spiegazioni nuovi assets

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#455]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Buongiorno,
Vedo che nell'ultimo rilascio, nel `comuni.css` sono state inserite le classi di **bootstrap 2.9.1** mente  il `bootstrap-italia.min.css` che e presente mantiene le vecchie classi di **bootstrap 2.5.1**.
Finora io ho sempre personalizzato il mio `bootstrap-italia.min.css` con l'aiuto di [bootstrap italia playground](https://github.com/italia/bootstrap-italia-playground). Grazie Andrea!
Adesso, dato che alcune classi di bootstrap sono presenti in tutti e due file, mi sa che `comuni.css` ha la precedenza.
Dunque, le personalizzazioni dove si devono fare adesso ? Grazie

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.10.3

**Comment by astagi** [comment]
@mariantanase abbiamo mergiato su main la modifica, lato nostro è tutto ok
