### ISSUE TITLE
Problema di compatibilità versione 1.10.4 con la libreria bootstrap-italia-playground

### ISSUE THREAD

**Issue by marco-nanni** [italia/design-comuni-wordpress-theme#458]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Installando l'ultima versione del tema (1.10.4) alcuni CSS cambiano.
Il fatto è che noi utilizziamo la versione "bootstrap-italia-playground" per adottare il colore BLU anziché il VERDE di default.
Ho letto, in un altra issue, che è stato cambiata la libreria Bootstrap di riferimento. 
Mi potete cortesemente indicare come aggiornare la libreria "bootstrap-italia-playground" per renderla compatibile?!

Grazie.

### Su quale sisitema operativo stai riscontrando il problema?

Linux

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.10.4

**Comment by mariantanase** [comment]
Ho notato anch'io questo.
Visto che adesso esiste un unico file **bootstrap-italia-comuni.min.css** che ragruppa `bootstrap-italia.min.css` e `comuni.css`, non so se funziona più il discorso del playground.

**Comment by marco-nanni** [comment]
Ok, @mariantanase fammi sapere.
Anche, se non ricordo male visto che l'ho fatto molto tempo fa, non funzionava.

**Comment by mariantanase** [comment]
@marco-nanni io ho fatto una prova veloce e mi sembra che funziona.

Nel `style.css` del child definisci le variabili personalizzate come in questo esempio:
```
:root {
	--bs-primary-dark: #036;
}
```
e poi definisi le classi che ti servono, in questo modo:
```
.it-header-slim-wrapper,
.bg-main-dark-primary,
.u-main-dark-primary{
	background: var(--bs-primary-dark);
}
```

**Comment by astagi** [comment]
Grazie @mariantanase ! @marco-nanni se provi e ti torna tutto facci sapere. Credo sia più semplice la personalizzazione in questo modo. CC @zetareticoli

**Comment by marco-nanni** [comment]
@astagi Non sembra funzionare. Questo è il risultato:
![Immagine 2024-10-18 121229](https://github.com/user-attachments/assets/a88952fe-0e65-4655-bfe6-e54caae90863)

**Comment by marco-nanni** [comment]
Scusate, però non è che io, e penso questo valga per tutti gli sviluppatori delle aziende coinvolte che utilizzano questa distribuzione, possa perdere vagonate di tempo a cercare le variabili CSS da ottimizzare. Se fate delle modifiche di questo tipo è buona norma rilasciare una documentazione accurata necessaria per agirare il problema del non utilizzo del playground. O in alternativa aggiornare il playground di conseguenza. Altrimenti non andava impostato il playground sin dall'inizio.

**Comment by mariantanase** [comment]
@marco-nanni Si vede dall'immagine che hai postato che il codice funziona. Il colore di sfondo (369) è applicato alla sezione slim-header, e interpretato correttamente.
Quello che ho postato io era solo un inizio.
> @astagi Non sembra funzionare. Questo è il risultato: ...

**Comment by marco-nanni** [comment]
@mariantanase  si questo mi era chiaro però poi nel post successivo ho spiegato la cosa.

**Comment by zetareticoli** [comment]
ciao @marco-nanni, i file CSS di questo repo sono sempre stati `.css` compilati e minificati.

Ogni personalizzazione colori richiede l'utilizzo dei file `.scss` che sono disponibili [nell'omologo repository dei templates statici](https://github.com/italia/design-comuni-pagine-statiche/tree/main/src/stylesheets)

**Comment by marco-nanni** [comment]
No, scusate. Noi abbiamo sempre utilizzato il playground nel quale era spiegato come cambiare i colori al tema e agganciato al child. COsa che ha funzionato perfettamente per ben due anni.
Quindi non ho capito questa cosa dei file .scss e non esiste nessuna documentazione in merito e per quale motivo dovrei prendere i file dal template statico quando stiamo utilizzando il template per WordPress.

**Comment by zetareticoli** [comment]
@marco-nanni il repo playground con il tema WP Comuni non c'entra nulla.

Quel repo è solo per testare e "giocare" con i componenti nativi di Bootstrap Italia.

**Comment by marco-nanni** [comment]
Certo peccato che sia stato utilizzato per due anni e non c'era scritto da nessuna èarte che fosse "per gioco".

**Comment by astagi** [comment]
Vero @zetareticoli non lo ricordo come procedimento consigliato. Come tool per personalizzare Bootstrap Italia è utile ma è uno dei tanti modi. 

Concordo sul documentare un processo di personalizzazione per quanto riguarda il css @marco-nanni , il cambiamento dell'import dei css purtroppo ha cambiato anche questo problema ma non è stato voluto, ad ogni modo siamo qua per trovare una soluzione che non sconvolga il lavoro di nessuno. Chiedo, portare le modifiche fatte su playground altrove è un problema? Alla fine il lavoro di customizzazione che viene fatto non si perde, va solo spostato. cc @mariantanase

**Comment by mariantanase** [comment]
Concordo con quanto detto da Andrea, anzi il playground per la personalizzazione della libreria bootstrap-italia lo utilizzo su altri progetti, non WP, anche semplici pagine html. 
Tornando all'argomento, per quanto mi riguarda, mi sono definito solamente 4 colori (`bs-primary, bs-primary-dark, bs-link-color, bs-link-hover-color`) e ho scovato le classi necessarie per la personalizzazione dei colori su un sito esistente (queste sono circa 160 righe di codice).

**Comment by astagi** [comment]
Grazie @mariantanase! Sul README c'è scritto poco sulla personalizzazione css (https://github.com/italia/design-comuni-wordpress-theme/blob/main/README.md?plain=1#L157) ti andrebbe se puoi di integrare magari la tua esperienza di personalizzazione? Anche con qualche riferimento al codice, potrebbe essere di aiuto a chiarire la questione.

**Comment by enrimk** [comment]
Per facilitare gli override via child theme (che, devo dire, anch'io ho usato più spesso della ricompilazione totale via scss), sarebbe utile ricorrere di più alle _custom properties_, sia nella base BI sia nella patch Comuni, e meno ai valori letterali (di colori o altro).

Così, idealmente, basterebbe davvero reimpostare alcune poche variabili alla radice, e si avrebbe un effetto a cascata abbastanza sicuro senza dovere andare a caccia delle singole regole da sovrascrivere coi DevTools.
È facile saltarne qualcuna, nei casi meno usati, e quando meno ce lo si aspetta poi sbuca "qualcosa di verde". 🙂

**Comment by astagi** [comment]
> Andrea ciao, Oltre a quanto già detto in precedenza, posso aggiungere che è molto utilie lo strumento DevTools (F12) del browser per analizzare il codice e un ColorPicker per i codici HEX dei colori. Per il resto servono le conoscenze base di html, css e magari le basi su php.

si assolutamente, grazie!

**Comment by zetareticoli** [comment]
> Per facilitare gli override via child theme (che, devo dire, anch'io ho usato più spesso della ricompilazione totale via scss), sarebbe utile ricorrere di più alle _custom properties_, sia nella base BI sia nella patch Comuni, e meno ai valori letterali (di colori o altro).
> 
> Così, idealmente, basterebbe davvero reimpostare alcune poche variabili alla radice, e si avrebbe un effetto a cascata abbastanza sicuro senza dovere andare a caccia delle singole regole da sovrascrivere coi DevTools. È facile saltarne qualcuna, nei casi meno usati, e quando meno ce lo si aspetta poi sbuca "qualcosa di verde". 🙂

è un tema che conosciamo e che speriamo di affrontare presto
