### ISSUE TITLE
Shortcode non si visualizzano in Notizie

### ISSUE THREAD

**Issue by lucianoviro** [italia/design-comuni-wordpress-theme#462]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Shortcode (ne ho provati di diversi plugin), ma anche anteprime video non vengono mostrate nella sezione notizie.

### Includi link o screenshot

<img width="1362" alt="Screenshot 2024-11-21 alle 10 50 50" src="https://github.com/user-attachments/assets/099e69d7-411f-4aa6-a265-5f16a414f89a">

### Su quale sisitema operativo stai riscontrando il problema?

macOS

### Su quale browser stai riscontrando il problema?

Qualsiasi, Chrome

### Che versione del tema stai utilizzando?

1.11.0

**Comment by abmcr** [comment]
Si: il campo non è il classico post_content.. per cui devi implementarlo.. cerca nelle issue chiuse un mio post con la soluzione
