### ISSUE TITLE
C.SI.1.1 - COERENZA DELL'UTILIZZO DEI FONT (librerie di caratteri)

### ISSUE THREAD

**Issue by thedigitalworld-agency** [italia/design-comuni-wordpress-theme#464]
### Prerequisiti

- [X] Ho già [cercato](https://github.com/italia/design-comuni-wordpress-theme/issues?utf8=%E2%9C%93&q=is%3Aissue) tra le issue la presenza di un problema simile
- [X] Ho letto le [linee guida di contribuzione](https://github.com/italia/design-comuni-wordpress-theme/blob/main/CONTRIBUTING.md)

### Descrivi il problema

Non capisco come mai il validatore mi riconosce un font che io non ho mai inserito e quindi di conseguenza non mi convalida correttamente tutto.

Allego di seguito uno screen

![Screenshot 2024-12-23 111833](https://github.com/user-attachments/assets/66a7c0a2-c9ff-41aa-8063-16382ac75273)

### Su quale sisitema operativo stai riscontrando il problema?

Windows

### Su quale browser stai riscontrando il problema?

Qualsiasi

### Che versione del tema stai utilizzando?

1.11

**Comment by enrimk** [comment]
Cookie banner?

**Comment by VinsMach** [comment]
questo errore capita solitamente quando si utilizza iubenda o come riportato da @enrimk (cookie banner) 
@thedigitalworld-agency  potresti riportare il portale in questione?
