### ISSUE TITLE
Persone pubbliche: dopo aver pubblicato la scheda dal backend, sul frontend viene visualizzata in "bozza automatica" ed il contenuto è vuoto

### ISSUE THREAD

**Issue by mirkopeloso** [italia/design-comuni-wordpress-theme#47]
Buongiorno, ho creato nel backend di WP 3 schede di persone pubbliche, con tanto di foto , descrizione, ruolo e altro.
aggiungendo queste tre schede come contenuti in evidenza nella pagina "Amministrazione" e cliccando su di esse, non viene mostrata la scheda persona pubblicata ma una bozza generata in automatico.
Vi allego i link come prova:

https://unionecomuniarcipelagodelsulcis.it/amministrazione/ 

Cliccando sui nomi dei tre sindaci (Ignazio Locci, Stefano Rombi o claudia Mura) si va a pagine in bozza, non a quelle pubblicate:

https://unionecomuniarcipelagodelsulcis.it/persona_pubblica/bozza-automatica/
https://unionecomuniarcipelagodelsulcis.it/persona_pubblica/bozza-automatica-2/
https://unionecomuniarcipelagodelsulcis.it/persona_pubblica/bozza-automatica-3/

**Comment by LovatoTomas** [comment]
Buongiorno, anche io ho lo stesso problema con le Persone Pubbliche.

**Comment by astagi** [comment]
Chiudo come duplicato https://github.com/italia/design-comuni-wordpress-theme/issues/71
