### ISSUE TITLE
Post type "luogo" senza dati visibili nel frontend

### ISSUE THREAD

**Issue by duttoluca** [italia/design-comuni-wordpress-theme#6]
Inserendo da backend un post type di tipo "luogo" (Menu "Luoghi" -> "Aggiungi un Luogo") non sono visibili nel frontend i dati inseriti (indirizzo, punto di contatto, GPS, etc...) .
Viene visualizzato soltanto il titolo e la descrizione breve (2 volte).

Testato su Wordpress 6.0.1, PHP 7.4.29, template 1.0.1
![luogo](https://user-images.githubusercontent.com/1429325/182368834-932e128a-e3e2-480a-9638-3bf2111b56de.png)

**Comment by zetareticoli** [comment]
Ciao @duttoluca,
ad oggi non è stato implementato il template per questo _content-type_.

È possibile crearlo in autonomia adattando il template previsto per il _content-type_ [notizia](https://github.com/italia/design-comuni-wordpress-theme/blob/main/single-notizia.php) in base ai contenuti previsti dal [relativo documento di architettura dell'informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit?usp=sharing&ouid=114978373497590601993&rtpof=true&sd=true)

**Comment by HshMatera** [comment]
Buongiorno @zetareticoli, 
mi potresti indicare come creare un nuovo template per i vari content-type non implementati?
single-notizia.php dove viene definito? 
Ho creato per esempio single-documento.php ma dove lo devo richiamare o definire?

Grazie

**Comment by vincenzo-72** [comment]
> Ciao @duttoluca, ad oggi non è stato implementato il template per questo _content-type_.
> 
> È possibile crearlo in autonomia adattando il template previsto per il _content-type_ [notizia](https://github.com/italia/design-comuni-wordpress-theme/blob/main/single-notizia.php) in base ai contenuti previsti dal [relativo documento di architettura dell'informazione](https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit?usp=sharing&ouid=114978373497590601993&rtpof=true&sd=true)

Non sapendo la gerarchia del template, come si fa a creare un template? Non mi sembra una cosa semplice non avendo una guida su come comporre i template di pagina.

**Comment by vincenzo-72** [comment]
> > Non sapendo la gerarchia del template, come si fa a creare un template?
> 
> Tecnicamente, in questo caso basterebbe creare un file single-luogo.php nella directory base del tema, e Wordpress si occupa lui di instradare lì il corrispondente tipo di post. Però, appunto:
> 
> > Non mi sembra una cosa semplice non avendo una guida su come comporre i template di pagina.
> 
> Anche perché il template Notizia, ad esempio, mi pare avere qualche problema come struttura html, che credo sarebbe opportuno risolvere prima di prenderlo a campione per crearne altri.

All'intero del _content-type_ 'notizia' ci sono voci che non sono presenti in 'luogo' e viceversa, quindi il codice php dovrà essere sempre modificato in base al tipo di _content-type_ da creare.
Inoltre tutto il template ha molti problemi di collegamenti generali, un esempio, se inserisco un nuovo incarico e flaggo la voce politico, in automatico la pagina 'politico' dovrebbe visualizzarla, cosa che non succede.

**Comment by danieledexter** [comment]
> Contributor

Anch'io sono interessato a capire come aggiungere un template nuovo da poter modificare ed utilizzare.

**Comment by zetareticoli** [comment]
Ciao @duttoluca,

volevo avvisarti che ieri abbiamo pubblicato su Figma il [layout per il content-type Luogo](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/%5BComuni%5D-Modello-sito-e-servizi?node-id=19%3A199961&t=gyNuZrSUG13FLBu8-1)

È quindi possibile seguire la struttura del layout per la realizzazione del template per il tema.
