### ISSUE TITLE
Nuova funzionalità messaggi di avviso in homepage

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#62]
Sulla versione 1.2 del tema non stati integrate le classi su comuni.css di questa nuova funzionalità. Pertanto i messaggi risultano tutti senza formattazione a meno di integrare le classi mancanti sul tema child @mariantanase @astagi

**Comment by mariantanase** [comment]
@astagi puoi verificare il perchè ? Nel file comuni.css della PR sono state aggiunte le classi ma per qualche ragione viene utilizzato il vecchio comuni.css.

**Comment by astagi** [comment]
@mariantanase @garagiu vero! il file comuni.css viene sovrascritto a tutti gli effetti da quello generato negli statici. Direi che puoi riaprire la modifica del css sul repository https://github.com/italia/design-comuni-pagine-statiche così poi rigeneriamo il tutto! Grazie!

**Comment by mariantanase** [comment]
> @mariantanase @garagiu vero! il file comuni.css viene sovrascritto a tutti gli effetti da quello generato negli statici. Direi che puoi riaprire la modifica del css sul repository https://github.com/italia/design-comuni-pagine-statiche così poi rigeneriamo il tutto! Grazie!

Quindi creare un fork della repository design-comuni-pagine-statiche, è aprire una PR li con la sola modifica del css ?
Ho capito bene ?

**Comment by astagi** [comment]
in alternativa @mariantanase puoi inserire gli stili nello `style.css` di wordpress, ancora meglio!

**Comment by astagi** [comment]
@mariantanase grazie della PR! Potresti spostare il tuo codice custom alla fine del file? Così dividiamo le customizzazioni.. Grazie!
