### ISSUE TITLE
Sezione contatti e footer

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#65]
Nellla sezione Contatti del Footer, anche se i campi non sono compilati, compaiono comunque le etichette :

- Numero verde:
- SMS e WhatsApp:
- Centralino unico: 

Inoltre compilando il campo posta elettronica certificata compare solo una label con il link all'indirizzo senza mostrare l'indirizzo in chiaro all'utente.
Il valore della posta certificata non può esser cancellato una volta inserito se non tramite una cancellazione via database

Anche i link sottostanti Media Policy e Mappa del Sito compaiono anche se non sono compilati
Non sarebbe meglio inserire un box di testo in questa area e un ulteriore posizione di menu potendo inserire Privacy Policy, Cookie Policy, Mappa del sito ecc?

**Comment by astagi** [comment]
Grazie @mariantanase del fix, giro ai colleghi
