### ISSUE TITLE
Azioni Scarica e Ascolta

### ISSUE THREAD

**Issue by garagiu** [italia/design-comuni-wordpress-theme#67]
Le azioni di Scarica e Ascolta a fianco della barra di condivisione social sono prive di script collegati pertanto non eseguono nulla
![immagine](https://user-images.githubusercontent.com/26837134/196363751-7e04dcf6-7987-4021-b68c-d7632b653261.png)

**Comment by astagi** [comment]
@garagiu abbiamo deciso di togliere la funzionalità Scarica (allo stesso modo si può stampare salvando il PDF). La funzionalità ascolta è attualmente in lavorazione sulla parte degli statici.

**Comment by astagi** [comment]
@garagiu se già vuoi vedere un anteprima la PR in questione è questa: https://github.com/italia/design-comuni-pagine-statiche/pull/64

Una preview: https://design-comuni-pagine-statiche-ab4xr4e08.vercel.app/sito/template-novita-notizia.html

**Comment by astagi** [comment]
Implementata nella nuova versione disponibile nell'area release
