### ISSUE TITLE
Domande varie

### ISSUE THREAD

**Issue by nomissor** [italia/design-comuni-wordpress-theme#8]
Salve,
ho scaricato ed installato il tema per i comuni ma ho alcune domande:

1) Nel post type novità alcuni campi inseriti dal CMS, non vengono visualizzati sul sito (Gallery, Allegati, ..)
2) Nel menu principale non è possibile avere menu a tendina? ( o Megamenu )
3) Nella scheda di un servizio, nella sezione "Accedi al Servizio" la descrizione prima del bottone per accedere al servizio digitale non è collegata a quanto inserito nel CMS ma è statica _"Puoi richiedere l’iscrizione alla Scuola dell’infanzia direttamente online tramite identità digitale"_ 

Questi FIX li devo gestire io tramite un child theme? 
O pensate di rilasciare un tema che possa essere utilizzato out of the box?

**Comment by zetareticoli** [comment]
Ciao @nomissor,
in merito al punto 3, la PR #5 ha corretto il problema. Grazie per la segnalazione.

In merito al punto 2, ti consiglio di leggere il capitolo ["Conformità del Modello" al punto 3 ](https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/v2022.1/modello-sito-comunale/conformita-modello-sito.html#conformita-al-modello-di-sito-comunale)

La scelta di non usare menu a tendina è stata presa in seguito a fase di ricerca con gli utenti.

Sul punto 1 stiamo facendo delle verifiche e ti aggiorneremo.

Grazie

**Comment by zetareticoli** [comment]
Ciao @nomissor,
ti aggiorno in base al punto 1 da te segnalato.

In base alle nostre verifiche abbiamo riscontrato che il field "Documenti" funziona correttamente. Allego screens 👇
![Schermata 2022-09-13 alle 12 27 21](https://user-images.githubusercontent.com/69706/189878538-35c06719-693a-4a0b-9acf-fba28735b82a.png)
![Schermata 2022-09-13 alle 12 27 16](https://user-images.githubusercontent.com/69706/189878551-21b894e0-ff0f-41c0-96bf-902b948ae060.png)

Confermo invece che il field "Gallerie multimediali" non funziona. Le immagini che vengono caricate non compaiono a front-end.

Se invece provi ad allegare un'immagine nel field "Corpo" tramite il pulsante "Aggiungi medi", si riescono ad inserire in nel testo.

Apriremo comunque una issue relativa al funzionamento delle Gallerie. 

Se non c'è altro, chiudo intanto questa issue di domande.

Grazie

**Comment by mariantanase** [comment]
Scusami @zetareticoli ,
Vedo nel tuo esempio che il campo "Documenti" crea un link ad una pagina "Accorpamento allogi". 
Ma il file allegato "**circolare-77.pdf**" dove sta ?
In quella pagina non compaiono allegati.
