### ISSUE TITLE
Sezione Siti tematici

### ISSUE THREAD

**Issue by mariantanase** [italia/design-comuni-wordpress-theme#80]
Nella home page vengono mostrati attualmente un massimo di 3 siti tematici.
Voglio chiedervi, non dovrebbe contenere anche un pulsante tipo "Vedi tutti siti tematici" che punta ad una pagina con tutti i siti tematici ?

**Comment by astagi** [comment]
Ciao @mariantanase! Immagini un pulsante `Vedi tutti` come già presente sulla homepage per altre sezioni, corretto? 

Taggo @zetareticoli

**Comment by mariantanase** [comment]
> Ciao @mariantanase! Immagini un pulsante `Vedi tutti` come già presente sulla homepage per altre sezioni, corretto?
> 
> Taggo @zetareticoli

Esatto !

**Comment by mariantanase** [comment]
Up
