### ISSUE TITLE
Incongruenze pagina Amministrazione rispetto alle specifiche

### ISSUE THREAD

**Issue by duttoluca** [italia/design-comuni-wordpress-theme#82]
Rileviamo parecchie incongruenze nella pagina di primo livello Amministrazione per come è implementata nel tema rispetto a come è descritta nella documentazione ufficiale.

Nella sezione https://docs.italia.it/italia/designers-italia/design-comuni-docs/it/versione-corrente/modello-sito-comunale/architettura-informazione.html#pagine-lista-di-primo-livello la pagina Amministrazione viene descritta come segue:

> Amministrazione è una sezione che contiene elementi di 3 tipologie di contenuto:
> persone;
> unità organizzative;
> documenti e dati.
> Ogni tipologia deve avere una propria sezione nella pagina. Ogni sezione potrà avere fino a 3 contenuti in evidenza (persone in evidenza, unità organizzative in evidenza, documenti e dati in evidenza) e l’elenco delle categorie non vuote della specifica tassonomia:
> per le persone, la tassonomia «Tipi di incarico»: politici, amministrativi, altri incarichi;
> per le unità organizzative la tassonomia «Tipi di unità organizzativa»: organi di governo, aree amministrative, uffici, enti e fondazioni;
> per documenti e dati: Documenti albo pretorio, Modulistica, Documenti funzionamento interno, Normative, Accordi tra enti, Documenti attività politica, Rapporti tecnici, Istanze, Documenti di programmazione e rendicontazione, Dataset.

Il tema Wordpress invece prevede:

- una sola sezione evidenza (condivisa tra tutte le tipologie) con 3 elementi in totale;
- la visualizzazione di qualsiasi sottopagina figlia della pagina Amministrazione, senza considerare quindi se siano tassonomie e se siano vuote o meno (senza contare che visualizzare delle sottopagine impone poi di implementare dei template specifici che visualizzino le relative tassonomie, invece di mostrare direttamente la pagina di tassonomia...).

Qual è l'interpretazione corretta per restare coerenti al modello?

**Comment by duttoluca** [comment]
Aggiungo: nella documentazione viene richiesto di stampare:

> per le unità organizzative la tassonomia «Tipi di unità organizzativa»: organi di governo, aree amministrative, uffici, enti e fondazioni;

Tale suddivisione però non rispecchia la struttura della tassonomia "tipi di unità organizzativa" definita nella documentazione ( https://docs.google.com/spreadsheets/d/1D4KbaA__xO9x_iBm08KvZASjrrFLYLKX/edit#gid=1190038254 )

**Comment by cristina-pontarolo** [comment]
Condivido i dubbi sollevati da duttoluca.

inutile avere una pagina di dettaglio, per esempio, degli uffici o del personale amministrativo, se poi non vedo l'elenco di tali contenuti "figli". speriamo risolvino presto.
