### ISSUE TITLE
Scheda servizio / notizia / evento: progress bar nel menu non funzionante

### ISSUE THREAD

**Issue by duttoluca** [italia/design-comuni-wordpress-theme#9]
Nei template dei post type servizio / notizia / evento, nel codice del menu sulla sinistra (indice della pagina) è impostata una progress bar.
Immagino dovrebbe funzionare come in [questo esempio](https://italia.github.io/bootstrap-italia/docs/esempi/navscroll/) man mano che si fa lo scroll della pagina, ma in realtà non succede nulla.

**Comment by zetareticoli** [comment]
Ciao @duttoluca, grazie per la segnalazione, correggeremo il bug quanto prima.

**Comment by zetareticoli** [comment]
Il bug è stato corretto sui template statici https://github.com/italia/design-comuni-pagine-statiche/pull/29

Il fix va riportato anche su questo repository e quello Drupal suppongo. Giusto @GiandonatoGreco ?

**Comment by GiandoG17** [comment]
@zetareticoli Si, l'attività è in lavorazione e verrà rilasciata entro Giovedì EOD.

**Comment by astagi** [comment]
Funzionalità presente nelle ultime versioni @duttoluca
