### ISSUE TITLE
Modifica Breadcrumb

### ISSUE THREAD

**Issue by mattiadevigus** [italia/design-comuni-wordpress-theme#91]
Buongiorno
Avrei la necessità di modificare la struttura della breadcrumb nella pagina "Tipi Eventi".
La struttura è la seguente:
Home / Eventi /Evento sociale
Avrei bisogno di modificare il link presente in "Eventi" puntandolo ad una pagina creata da me.
Modificando il codice che genera la breadcrumb dal tema padre, sono riuscito a farlo senza grosse difficoltà. Esiste però un modo per andare a modificare le breadcrumb dal tema child, senza dover modificare direttamente il padre?

![image](https://user-images.githubusercontent.com/57149074/202720010-843250a0-9f0c-4d47-8ccb-ed981fde27f7.png)

**Comment by techdesignadmin** [comment]
Mi accodo alla richiesta.
Dovrei modificare le breadcrumb ma sembra che tutto il codice sia scolpito nel tema padre.
Non mi è chiaro se ci sia qualche evento a cui agganciarsi o meno dal tema figlio... c'è un modo di agganciarsi da qualche parte? O fare l'override di qualche funzione del padre nel figlio?
L'alternativa è modificare direttamente il tema padre, ma è un po' una porcata per la mantenibilità del tutto.

**Comment by LucaDuttoTD** [comment]
Mi accodo alla richiesta.
Dovrei modificare le breadcrumb ma sembra che tutto il codice sia scolpito nel tema padre.
Non mi è chiaro se ci sia qualche evento a cui agganciarsi o meno dal tema figlio... c'è un modo di agganciarsi da qualche parte? O fare l'override di qualche funzione del padre nel figlio?
L'alternativa è modificare direttamente il tema padre, ma è un po' una porcata per la mantenibilità del tutto.
